import 'all_app_strings.dart';

mixin AppLocaleCzech {
  static const Map<String, dynamic> czech = {
    AppStrings.somethingwentwrong: 'Něco se pokazilo',
    AppStrings.nothingtodisplay: 'Nic k zobrazení...',
    AppStrings.chat: 'Chat',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Video',
    AppStrings.active: 'Aktivní',
    AppStrings.inactive: 'Neaktivní',
    AppStrings.edit: 'Upravit',
    AppStrings.yes: 'Ano',
    AppStrings.no: 'Ne',
    AppStrings.settings: 'Nastavení',
    AppStrings.getcoins: 'Získat mince',
    AppStrings.promotions: 'Promoce',
    AppStrings.errorloadingvideo: 'Chyba při načítání videa',
    AppStrings.errorloadingpage: 'Chyba při načítání stránky',
    AppStrings.comments: 'Komentáře',
    AppStrings.replyto: 'Odpovědět na',
    AppStrings.replytonamecomment: 'Odpovědět na komentář jménem',
    AppStrings.replies: 'Odpovědi',
    AppStrings.post: 'Příspěvek',
    AppStrings.nocommentsyet: 'Žádné komentáře zatím',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Napište zprávu',
    AppStrings.nomessagesfound: 'Žádné zprávy nenalezeny',
    AppStrings.failedtoloadthechatrroms: 'Nepodařilo se načíst chatovací místnosti',
    AppStrings.typeheretheusername: 'Zadejte uživatelské jméno zde',
    AppStrings.lockscreen: 'Uzamknutá obrazovka',
    AppStrings.logout: 'Odhlásit se',
    AppStrings.darkmode: 'Tmavý režim',
    AppStrings.followers: 'Sledující',
    AppStrings.followings: 'Sledující osoby',
    AppStrings.recentfollowings: 'Nedávní sledující',
    AppStrings.recentfollowers: 'Nedávní sledující',
    AppStrings.groupnmae: 'Název skupiny',
    AppStrings.required: 'Povinné',
    AppStrings.website: 'Webová stránka',
    AppStrings.category: 'Kategorie',
    AppStrings.validwebsiteurl: 'Platná URL webové stránky',
    AppStrings.aboutthisgroup: 'O této skupině',
    AppStrings.areyousureyouwanttologout: 'Jste si jisti, že se chcete odhlásit?',
    AppStrings.writemoreaboutthisgroup: 'Napište více o této skupině',
    AppStrings.sociallinks: 'Sociální odkazy',
    AppStrings.facebookprofilelink: 'Odkaz na profil na Facebooku',
    AppStrings.xprofilelink: 'Odkaz na profil na X',
    AppStrings.instagramprofilelink: 'Odkaz na profil na Instagramu',
    AppStrings.tiktokprofilelink: 'Odkaz na profil na TikToku',
    AppStrings.pinterestprofilelink: 'Odkaz na profil na Pinterestu',
    AppStrings.steamprofilelink: 'Odkaz na profil na Steamu',
    AppStrings.linkedInprofilelink: 'Odkaz na profil na LinkedInu',
    AppStrings.selectprivacy: 'Vyberte soukromí',
    AppStrings.groupwillbepublic: 'Skupina bude veřejná',
    AppStrings.submitgroup: 'Odeslat skupinu',
    AppStrings.allrequiredfieldsshouldbefilled: 'Všechna povinná pole musí být vyplněna',
    AppStrings.errorloadinggroupdata: 'Chyba při načítání dat skupiny',
    AppStrings.artAndCulture: 'Umění a kultura',
    AppStrings.scienceAndTechnology: 'Věda a technologie',
    AppStrings.sport: 'Sport',
    AppStrings.music: 'Hudba',
    AppStrings.gastronomy: 'Gastronomie',
    AppStrings.fashionAndStyle: 'Móda a styl',
    AppStrings.travelAndPlaces: 'Cestování a místa',
    AppStrings.education: 'Vzdělání',
    AppStrings.career: 'Kariéra',
    AppStrings.businessAndFinance: 'Byznys a finance',
    AppStrings.entertainment: 'Zábava',
    AppStrings.environmentAndEcology: 'Životní prostředí a ekologie',
    AppStrings.agricultureAndHorticulture: 'Zemědělství a zahradnictví',
    AppStrings.languagesAndCommunication: 'Jazyky a komunikace',
    AppStrings.technologyAndDigital: 'Technologie a digitál',
    AppStrings.architectureAndDesign: 'Architektura a design',
    AppStrings.mediaAndJournalism: 'Média a žurnalistika',
    AppStrings.buyAndSell: 'Koupit a prodat',
    AppStrings.selectacategory: 'Vyberte kategorii',
    AppStrings.groupprofilepicture: 'Profilová fotka skupiny',
    AppStrings.selectaimage: 'Vyberte obrázek',
    AppStrings.groupcoverpicture: 'Obrázek na pozadí skupiny',
    AppStrings.createpost: 'Vytvořit příspěvek',
    AppStrings.writesomething: 'Napište něco...',
    AppStrings.createapoll: 'Vytvořit anketu',
    AppStrings.pollquestion: 'Otázka ankety',
    AppStrings.polloption: 'Možnost ankety',
    AppStrings.addoption: '+ Přidat možnost',
    AppStrings.checkin: 'Check-in',
    AppStrings.current: 'Aktuální',
    AppStrings.customLocation: 'Vlastní místo',
    AppStrings.onlyforclosefriend: 'Pouze pro blízké přátele?',
    AppStrings.newsfeed: 'Zpravodaj',
    AppStrings.story: 'Příběh',
    AppStrings.contentmustbefilled: 'Obsah musí být vyplněn',
    AppStrings.polloptions: 'Možnosti ankety:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions: 'Anketa musí mít otázku a alespoň dvě možnosti',
    AppStrings.firstofallselectanimage: 'Nejprve vyberte obrázek',
    AppStrings.browseondevice: 'Procházet v zařízení',
    AppStrings.joinedgroup: 'Připojená skupina',
    AppStrings.leavegroupsuccessfully: 'Skupinu opustíte úspěšně',
    AppStrings.joingroup: 'Připojit se ke skupině',
    AppStrings.groupjoinedsuccessfully: 'Skupina byla úspěšně přidána',
    AppStrings.postdeletedsuccessfully: 'Příspěvek byl úspěšně smazán',
    AppStrings.deleteallusersposts: 'Smazat všechny příspěvky uživatele',
    AppStrings.deletealluserscomments: 'Smazat všechny komentáře uživatele',
    AppStrings.deleteposts: 'Smazat příspěvky',
    AppStrings.deletecomments: 'Smazat komentáře',
    AppStrings.removethisuser: 'Odebrat tohoto uživatele',
    AppStrings.delete: 'smazat',
    AppStrings.editmemberdetails: 'Upravit údaje o členu',
    AppStrings.availableroles: 'Dostupné role',
    AppStrings.groupmanger: 'Manažer skupiny',
    AppStrings.pagemanger: 'Manažer stránky',
    AppStrings.pagemangerdescription: 'Upravit údaje stránky, upravit členy stránky, upravit příspěvky stránky, upravit komentáře příspěvků stránky',
    AppStrings.groupmangerdescription: 'Upravit údaje skupiny, upravit členy skupiny, upravit příspěvky skupiny, upravit komentáře příspěvků skupiny',
    AppStrings.groupmoderatord: 'Moderátor skupiny',
    AppStrings.pagemoderatord: 'Moderátor stránky',
    AppStrings.pagemoderatorddescription: 'Upravit příspěvky stránky, upravit komentáře příspěvků stránky',
    AppStrings.groupmoderatorddescription: 'Upravit příspěvky skupiny, upravit komentáře příspěvků skupiny',
    AppStrings.none: 'Žádný',
    AppStrings.availablepermission: 'Dostupná oprávnění',
    AppStrings.altergroupdetails: 'Upravit údaje skupiny',
    AppStrings.altergroupmembers: 'Upravit členy skupiny',
    AppStrings.altergroupposts: 'Upravit příspěvky skupiny',
    AppStrings.altergrouppostscomments: 'Upravit komentáře příspěvků skupiny',
    AppStrings.alterpagedetails: 'Upravit údaje stránky',
    AppStrings.alterpagemembers: 'Upravit členy stránky',
    AppStrings.alterpageposts: 'Upravit příspěvky stránky',
    AppStrings.alterpagepostscomments: 'Upravit komentáře příspěvků stránky',
    AppStrings.updateuser: 'Aktualizovat uživatele',
    AppStrings.editgroup: 'Upravit skupinu',
    AppStrings.editpage: 'Upravit stránku',
    AppStrings.deletegroup: 'Smazat skupinu',
    AppStrings.deletepage: 'Smazat stránku',
    AppStrings.groupmembers: 'Členové skupiny',
    AppStrings.pagemembers: 'Členové stránky',
    AppStrings.report: 'Hlášení',
    AppStrings.areyousureyouwanttodeletegroup: 'Jste si jisti, že chcete smazat skupinu?',
    AppStrings.areyousureyouwanttodeletepage: 'Jste si jisti, že chcete smazat stránku?',
    AppStrings.youremailisnotverified: 'Vaše e-mailová adresa není ověřena',
    AppStrings.unauthenticated: 'Neověřeno',
    AppStrings.failedtodeletepost: 'Nepodařilo se smazat příspěvek',
    AppStrings.addingapost: 'Přidávání příspěvku',
    AppStrings.golive: 'Jít naživo',
    AppStrings.location: 'Místo',
    AppStrings.timestamp: 'Časová značka',
    AppStrings.votes: 'Hlasování',
    AppStrings.short: 'krátký',
    AppStrings.reply: 'odpovědět',
    AppStrings.shortvideopost: 'Krátký video příspěvek',
    AppStrings.shares: 'Sdílení',
    AppStrings.share: 'Sdílet',
    AppStrings.comment: 'komentář',
    AppStrings.hidecomments: 'Skrýt komentáře',
    AppStrings.viewmorecomments: 'Zobrazit více komentářů',
    AppStrings.replytonamepost: 'Odpovědět na příspěvek jména',
    AppStrings.name: 'jméno',
    AppStrings.onedayago: 'Před 1 dnem',
    AppStrings.promote: 'Propagovat',
    AppStrings.increaseyourpopularity: 'Zvyšte svou popularitu',
    AppStrings.allocatecoinsforpromotions: 'Přidělit mince na propagaci',
    AppStrings.like: 'Líbí se',
    AppStrings.viewpost: 'Zobrazit příspěvek',
    AppStrings.replypost: 'Odpovědět na příspěvek',
    AppStrings.submitanewpost: 'ODESLAT NOVÝ PŘÍSPĚVEK',
    AppStrings.submitanewpostdescription: 'Přidejte tento příspěvek s podrobným obsahem. Uveďte co nejvíce podrobností ve všech možných formách, aby byla zajištěna správná řešení.',
    AppStrings.content: 'obsah',
    AppStrings.reportnow: 'Nahlásit nyní',
    AppStrings.failedtoremovelock: 'Nepodařilo se odstranit zámek',
    AppStrings.password: 'Heslo',
    AppStrings.unlock: 'Odemknout',
    AppStrings.thesecredentialsdonotmatch: 'Tato přihlašovací údaje neodpovídají',
    AppStrings.login: 'Přihlásit se',
    AppStrings.signin: 'Přihlásit se',
    AppStrings.signup: 'Registrovat',
    AppStrings.email: 'E-mailem',
    AppStrings.rememberme: 'Zapamatovat si mě',
    AppStrings.forgetpassword: 'Zapomněli jste heslo',
    AppStrings.notifications: 'Oznámení',
    AppStrings.pages: 'Stránky',
    AppStrings.createnewpage: 'VYTVOŘIT NOVOU STRÁNKU',
    AppStrings.members: 'Členové',
    AppStrings.creators: 'Tvořitelé',
    AppStrings.page: 'Stránka',
    AppStrings.submitpage: 'Odeslat stránku',
    AppStrings.aboutthispage: 'O této stránce',
    AppStrings.writemoreaboutthispage: 'Napište více o této stránce',
    AppStrings.pagename: 'Název stránky',
    AppStrings.private: 'soukromé',
    AppStrings.public: 'veřejné',
    AppStrings.invite: 'POZVAT',
    AppStrings.about: 'O',
    AppStrings.photos: 'FOTKY',
    AppStrings.events: 'UDÁLOSTI',
    AppStrings.pagewillbepublic: 'Stránka bude veřejná',
    AppStrings.pagefollowed: 'Stránka sledována',
    AppStrings.joinpage: 'Připojit se k stránce',
    AppStrings.pageleavedsuccessfully: 'Úspěšně opustil stránku',
    AppStrings.pagejoinedsuccessfully: 'Úspěšně připojeno ke stránce',
    AppStrings.userspage: 'Uživatelská stránka',
    AppStrings.paymentcompletedsuccessfully: 'Platba byla úspěšně dokončena!',
    AppStrings.stripepayment: 'Platba Stripe',
    AppStrings.myphotos: 'Moje fotografie',
    AppStrings.recentphotos: 'Nedávné fotografie',
    AppStrings.recentposts: 'Nedávné příspěvky',
    AppStrings.savedshorts: 'Uložené krátké videa',
    AppStrings.seeall: 'Zobrazit vše',
    AppStrings.groups: 'Skupiny',
    AppStrings.errorloadingaccountdetails: 'Chyba při načítání detailů účtu',
    AppStrings.errorloadingprofile: 'Chyba při načítání profilu',
    AppStrings.timeline: 'Časová osa',
    AppStrings.saved: 'Uloženo',
    AppStrings.restricted: 'Omezeno',
    AppStrings.blocked: 'Zablokováno',
    AppStrings.register: 'Registrovat',
    AppStrings.date: 'Datum',
    AppStrings.find: 'Najít',
    AppStrings.users: 'Uživatelé',
    AppStrings.status: 'Stav',
    AppStrings.open: 'Otevřít',
    AppStrings.closed: 'Uzavřeno',
    AppStrings.title: 'Název',
    AppStrings.edittickets: 'Upravit vstupenky',
    AppStrings.postareply: 'Přidat odpověď',
    AppStrings.createdat: 'Vytvořeno dne',
    AppStrings.lastreplyby: 'Poslední odpověď od',
    AppStrings.repliesintotal: 'Celkový počet odpovědí',
    AppStrings.supportTickets: 'Podpůrné vstupenky',
    AppStrings.ticketsummary: 'Shrnutí vstupenky',
    AppStrings.availableactions: 'Dostupné akce',
    AppStrings.retypepassword: 'Zadejte heslo znovu',
    AppStrings.yourname: 'Vaše jméno',
    AppStrings.selectyourcountry: 'Vyberte svou zemi',
    AppStrings.username: 'Uživatelské jméno',
    AppStrings.searchby: 'Hledat podle',
    AppStrings.searchresults: 'Výsledky hledání',
    AppStrings.searchpeoplegrouporpage: 'Hledat osoby, skupiny nebo stránky',
    AppStrings.followaddedsuccessfully: 'Sledování úspěšně přidáno',
    AppStrings.followremovedsuccessfully: 'Sledování úspěšně odstraněno',
    AppStrings.pleaseverifyyuouremail: 'Prosím ověřte svůj e-mail',
    AppStrings.verifyyouraccount: 'Ověřte svůj účet',
    AppStrings.sendverificationlink: 'Odeslat ověřovací odkaz',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
    'Pokud jste již obdrželi odkaz nebo máte účet, přihlaste se nyní',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere:
    'Pokud jste neobdrželi odkaz, klikněte zde',
    AppStrings.videos: 'Videa',
    AppStrings.videoselected: 'Video vybráno!',
    AppStrings.donate: 'Darovat',
    AppStrings.recentvideos: 'Nedávná videa',
    AppStrings.firstofallselectvideo: 'Nejprve vyberte video',
    AppStrings.shortdescriprtiontags: 'Krátký popis, #tagy',
    AppStrings.postshort: '↑ Přidat krátký příspěvek',
    AppStrings.pleaseselectavideofile: 'Prosím vyberte video soubor',
    AppStrings.donations: 'Dary',
    AppStrings.topdonations: 'Nejvyšší dary',
    AppStrings.helptheshortcreator: 'Pomozte tvůrci krátkého videa.',
    AppStrings.sharethispostto: 'Sdílet tento příspěvek do',
    AppStrings.copylink: 'Kopírovat odkaz',
    AppStrings.selectanuser: 'Vyberte uživatele',
    AppStrings.user111: 'uživatel111',
    AppStrings.sharenow: 'Sdílet nyní',
    AppStrings.reopenticket: 'Znovu otevřít vstupenku',
    AppStrings.closeticket: 'Uzavřít vstupenku',
    AppStrings.supportsticket: 'Podpůrné vstupenky',
    AppStrings.totalticket: 'CELKOVÉ VSTUPENKY',
    AppStrings.solvedticket: 'VYŘEŠENÉ VSTUPENKY',
    AppStrings.openedissues: 'OTEVŘENÉ PROBLÉMY',
    AppStrings.sendemail: 'Odeslat e-mail',
    AppStrings.support: 'Podpora',
    AppStrings.openticket: 'Otevřít vstupenku',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
    'Pokud byste raději kontaktovali nás e-mailem, pošlete nám svou žádost na:',
    AppStrings
        .ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
    'Pokud čtete tuto větu, vypadá to, že váš problém je opravdu vážný... prosím dejte nám vědět více o tomto, určitě vám pomůžeme.',
    AppStrings.createanewsupportticket: 'Vytvořit novou podpůrnou vstupenku',
    AppStrings.newintervention: 'Nová intervence',
    AppStrings.interventiontitle: 'Název intervence',
    AppStrings.typeherethetitle: 'Zadejte název zde',
    AppStrings.submitticket: 'Odeslat vstupenku',
    AppStrings.submitcomment: 'Odeslat komentář',
    AppStrings.contentmustnotbelessthentencharacters:
    'Obsah nesmí být kratší než deset znaků',
    AppStrings.completeinterventiontitle:
    'Uveďte tuto intervenci s podrobným obsahem. Prosím zahrňte co nejvíce podrobností ve všech možných formách, abyste získali správné řešení.',
    AppStrings.updatecomment: 'Aktualizovat komentář',
    AppStrings.updatethereply: 'Aktualizovat odpověď',
    AppStrings.commentcontent:
    'Uveďte tuto odpověď s podrobným obsahem. Prosím zahrňte co nejvíce podrobností ve všech možných formách, abyste získali správné řešení.',
    AppStrings.thereisopeninterventionticketcloseitfirst:
    'Existuje otevřená intervence vstupenka, prosím nejprve ji uzavřete.',
    AppStrings.addanewcomment: 'Přidat nový komentář',
    AppStrings.billingarea: 'Fakturační oblast',
    AppStrings.billingareacap: 'FAKTURAČNÍ OBLAST',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount:
    'Procházejte transakce a přidejte více mincí do svého účtu',
    AppStrings.topup: 'DOPLNIT',
    AppStrings.gotopayment: 'Přejít na platbu',
    AppStrings.paymentfailed: 'Platba se nezdařila',
    AppStrings.pleaseselectanamount: 'Vyberte částku',
    AppStrings.showlatesttransactionscap: 'ZOBRAZIT NEJNOVĚJŠÍ TRANSAKCE',
    AppStrings.transactionscap: 'TRANSAKCE',
    AppStrings.transactionnote: 'Sledujte a zobrazujte příchozí nebo odchozí transakce a připravte se na své příští úspěchy.',
    AppStrings.searchtransactionsby: 'Hledat transakce podle',
    AppStrings.searchtransactions: 'Hledat transakce',
    AppStrings.alltransactions: 'Všechny transakce',
    AppStrings.transactionname: 'Název transakce',
    AppStrings.transactionid: 'ID transakce',
    AppStrings.querytobeexecuted: 'Dotaz k provedení',
    AppStrings.settingssaved: 'Nastavení uloženo',
    AppStrings.general: 'Obecné',
    AppStrings.failedtosavesettigns: 'Nepodařilo se uložit nastavení',
    AppStrings.emailpreferences: 'Nastavení e-mailu',
    AppStrings.emailnotificationscap: 'E-MAILOVÉ NOTIFIKACE',
    AppStrings.savepreferences: 'Uložit nastavení',
    AppStrings.sendmeemailsaboutmyentireactivity: 'Posílejte mi e-maily o mé celé aktivitě',
    AppStrings.selectpushandemailnotificationyouliketorecieve: 'Vyberte push a e-mailové notifikace, které chcete dostávat',
    AppStrings.onlysendmerequiredemails: 'Posílejte mi pouze povinné e-maily',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges: 'Poznámka: Vždy obdržíte notifikace o individuálních změnách účtu.',
    AppStrings.enablefollowmecap: 'POVOLIT SLEDOVÁNÍ',
    AppStrings.sendmenotificationscap: 'POSÍLAT MI NOTIFIKACE',
    AppStrings.enablethisifyouwantpeopletofollowyou: 'Povolte to, pokud chcete, aby vás lidé sledovali',
    AppStrings.sendmenotificationaboutmyfriendlike: 'Posílejte mi notifikace o oblíbených příspěvcích mých přátel',
    AppStrings.shareormessageme: 'Sdílet nebo mě kontaktovat',
    AppStrings.hideyourprofilefromsearchengine: 'Skrýt váš profil před vyhledávači',
    AppStrings.searchprivacycap: 'PRIVÁTNOST VYHLEDÁVÁNÍ',
    AppStrings.hidegendercap: 'SKRÝT PŘÍSLOVNÍ',
    AppStrings.hideagecap: 'SKRÝT VĚK',
    AppStrings.hidelocationcap: 'SKRÝT LOKALITU',
    AppStrings.profilecap: 'PROFIL',
    AppStrings.editprofilecap: 'UPRAVIT PROFIL',
    AppStrings.changecap: 'ZMĚNIT',
    AppStrings.displaynamecap: 'ZOBRAZIT JAK',
    AppStrings.peopleongenixwillgettoknowbybelowinfo: 'Lidé v Genixu se dozvědí následující informace o vás',
    AppStrings.showingname: 'Zobrazené jméno',
    AppStrings.usernamecap: 'UŽIVATELSKÉ JMÉNO',
    AppStrings.emailaddressecap: 'E-MAILOVÁ ADRESA',
    AppStrings.youremailaddress: 'Vaše e-mailová adresa',
    AppStrings.gendercap: 'PŘÍSLOVNÍ',
    AppStrings.male: 'Muž',
    AppStrings.female: 'Žena',
    AppStrings.bio: 'Bio',
    AppStrings.tellusmoreaboutyou: 'Povězte nám více o sobě',
    AppStrings.socialprofilelinks: 'Odkazy na sociální profil',
    AppStrings.citycap: 'MĚSTO',
    AppStrings.countrycap: 'ZEMĚ',
    AppStrings.yourcity: 'Vaše město',
    AppStrings.paypalemailaddress: 'E-MAILOVÁ ADRESA PAYPAL',
    AppStrings.enteryourpaypalemailaddress: 'Zadejte svou e-mailovou adresu PayPal',
    AppStrings.security: 'Bezpečnost',
    AppStrings.accountpasswordcap: 'HESLO ÚČTU',
    AppStrings.changeyourpasswordandalterothersecurityoptions: 'Změňte své heslo a upravte další bezpečnostní možnosti',
    AppStrings.currentpasswordcap: 'SOUČASNÉ HESLO',
    AppStrings.currentpassword: 'Současné heslo',
    AppStrings.newpassword: 'Nové heslo',
    AppStrings.confirmpassword: 'Potvrďte heslo',
    AppStrings.repeatnewpassword: 'Opakujte nové heslo',
    AppStrings.mineightcharacters: 'MIN. 8 ZNAKŮ',
    AppStrings.twofactorauthenticationcap: 'DVOJFÁZOVÉ ODVĚTÍ',
    AppStrings.twofactorauthentication: 'Dvojfaktorové ověření',
    AppStrings.enable: 'Povolit',
    AppStrings.enablecap: 'POVOLIT',
    AppStrings.accountclosure: 'ZRUŠENÍ ÚČTU',
    AppStrings.deleteyouraccountanddata: 'Smazat účet a data',
    AppStrings.areyousureyouwanttodeleteyouraccount: 'Jste si jistý, že chcete smazat svůj účet?',
    AppStrings.deletecap: 'SMAŽTE',
    AppStrings.settingscap: 'Nastavení',
    AppStrings.emails: 'E-maily',
    AppStrings.billings: 'Fakturace',
    AppStrings.profile: 'Profil',
    AppStrings.currentbalancecap: 'SOUČASNÁ BILANCE',
    AppStrings.revenuefromshortscap: 'PŘÍJMY Z KRÁTKÝCH VIDEO',
    AppStrings.withdrawcap: 'VÝBĚR',
    AppStrings.coins: 'Mince',
    AppStrings.customamount: 'Vlastní částka',
    AppStrings.selectlanguage: "Vyberte jazyk",
    AppStrings.languagecap: "JAZYK",
    AppStrings.changinglanguage: "Změna jazyka...",
  };}