import 'all_app_strings.dart';

mixin AppLocaleDutch {
  static const Map<String, dynamic> dutch = {
    AppStrings.somethingwentwrong: 'Er ging iets mis',
    AppStrings.nothingtodisplay: 'Niets om weer te geven...',
    AppStrings.chat: 'Chat',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Video',
    AppStrings.active: 'Actief',
    AppStrings.inactive: 'Inactief',
    AppStrings.edit: 'Bewerken',
    AppStrings.yes: 'Ja',
    AppStrings.no: 'Nee',
    AppStrings.settings: 'Instellingen',
    AppStrings.getcoins: 'Krijg Munten',
    AppStrings.promotions: 'Promoties',
    AppStrings.errorloadingvideo: 'Fout bij het laden van video',
    AppStrings.errorloadingpage: 'Fout bij het laden van de pagina',
    AppStrings.comments: 'Reacties',
    AppStrings.replyto: 'Beantwoorden aan',
    AppStrings.replytonamecomment: 'Beantwoorden aan Naam Commentaar',
    AppStrings.replies: 'Antwoorden',
    AppStrings.post: 'Bericht',
    AppStrings.nocommentsyet: 'Nog geen reacties',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Typ een bericht',
    AppStrings.nomessagesfound: 'Geen berichten gevonden',
    AppStrings.failedtoloadthechatrroms: 'Fout bij het laden van de chatrooms',
    AppStrings.typeheretheusername: 'Typ hier de gebruikersnaam',
    AppStrings.lockscreen: 'Vergrendelscherm',
    AppStrings.logout: 'Uitloggen',
    AppStrings.darkmode: 'Donkere modus',
    AppStrings.followers: 'Volgers',
    AppStrings.followings: 'Gevolgden',
    AppStrings.recentfollowings: 'Recente gevolgden',
    AppStrings.recentfollowers: 'Recente volgers',
    AppStrings.groupnmae: 'Groepsnaam',
    AppStrings.required: '  vereist',
    AppStrings.website: 'Website',
    AppStrings.category: 'Categorie',
    AppStrings.validwebsiteurl: 'Geldige website-URL',
    AppStrings.aboutthisgroup: 'Over deze groep',
    AppStrings.areyousureyouwanttologout:
        'Weet je zeker dat je wilt uitloggen?',
    AppStrings.writemoreaboutthisgroup: 'Schrijf meer over deze groep',
    AppStrings.sociallinks: 'Sociale links',
    AppStrings.facebookprofilelink: 'Facebook-profiel link',
    AppStrings.xprofilelink: 'X-profiel link',
    AppStrings.instagramprofilelink: 'Instagram-profiel link',
    AppStrings.tiktokprofilelink: 'TikTok-profiel link',
    AppStrings.pinterestprofilelink: 'Pinterest-profiel link',
    AppStrings.steamprofilelink: 'Steam-profiel link',
    AppStrings.linkedInprofilelink: 'LinkedIn-profiel link',
    AppStrings.selectprivacy: 'Selecteer privacy',
    AppStrings.groupwillbepublic: 'De groep wordt openbaar',
    AppStrings.submitgroup: 'Dien groep in',
    AppStrings.allrequiredfieldsshouldbefilled:
        'Alle verplichte velden moeten worden ingevuld',
    AppStrings.errorloadinggroupdata: 'Fout bij het laden van groepsgegevens',
    AppStrings.artAndCulture: 'Kunst en Cultuur',
    AppStrings.scienceAndTechnology: 'Wetenschap en Technologie',
    AppStrings.sport: 'Sport',
    AppStrings.music: 'Muziek',
    AppStrings.gastronomy: 'Gastronomie',
    AppStrings.fashionAndStyle: 'Mode en Stijl',
    AppStrings.travelAndPlaces: 'Reizen en Plaatsen',
    AppStrings.education: 'Onderwijs',
    AppStrings.career: 'Carrière',
    AppStrings.businessAndFinance: 'Zakelijk en Financiën',
    AppStrings.entertainment: 'Entertainment',
    AppStrings.environmentAndEcology: 'Milieu en Ecologie',
    AppStrings.agricultureAndHorticulture: 'Landbouw en Tuinbouw',
    AppStrings.languagesAndCommunication: 'Talen en Communicatie',
    AppStrings.technologyAndDigital: 'Technologie en Digitaal',
    AppStrings.architectureAndDesign: 'Architectuur en Design',
    AppStrings.mediaAndJournalism: 'Media en Journalistiek',
    AppStrings.buyAndSell: 'Kopen en Verkopen',
    AppStrings.selectacategory: 'Selecteer een Categorie',
    AppStrings.groupprofilepicture: 'Groepsprofielafbeelding',
    AppStrings.selectaimage: 'Selecteer een Afbeelding',
    AppStrings.groupcoverpicture: 'Groepsomslagfoto',
    AppStrings.createpost: 'Maak Bericht',
    AppStrings.writesomething: 'Schrijf iets...',
    AppStrings.createapoll: 'Maak een Poll',
    AppStrings.pollquestion: 'Poll Vraag',
    AppStrings.polloption: 'Poll Optie',
    AppStrings.addoption: '+ Voeg Optie Toe',
    AppStrings.checkin: 'Inchecken',
    AppStrings.current: 'Huidig',
    AppStrings.customLocation: 'Aangepaste Locatie',
    AppStrings.onlyforclosefriend: 'Alleen voor Dichte Vrienden?',
    AppStrings.newsfeed: 'Nieuwsfeed',
    AppStrings.story: 'Verhaal',
    AppStrings.contentmustbefilled: 'Inhoud moet ingevuld zijn',
    AppStrings.polloptions: 'Poll Opties:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions:
        'Poll moet een vraag hebben en minstens twee opties',
    AppStrings.firstofallselectanimage: 'Selecteer eerst een afbeelding',
    AppStrings.browseondevice: 'Bladeren op apparaat',
    AppStrings.joinedgroup: 'Groep Toegetreden',
    AppStrings.leavegroupsuccessfully: 'Groep Verlaten Succesvol',
    AppStrings.joingroup: 'Doe mee met groep',
    AppStrings.groupjoinedsuccessfully: 'Groep Succesvol Toegetreden',
    AppStrings.postdeletedsuccessfully: 'Bericht Succesvol Verwijderd',
    AppStrings.deleteallusersposts: 'Verwijder alle berichten van de gebruiker',
    AppStrings.deletealluserscomments:
        'Verwijder alle opmerkingen van de gebruiker',
    AppStrings.deleteposts: 'Verwijder berichten',
    AppStrings.deletecomments: 'Verwijder opmerkingen',
    AppStrings.removethisuser: 'Verwijder deze gebruiker',
    AppStrings.delete: 'Verwijderen',
    AppStrings.editmemberdetails: 'Bewerk lidgegevens',
    AppStrings.availableroles: 'Beschikbare rollen',
    AppStrings.groupmanger: 'Groepbeheerder',
    AppStrings.pagemanger: 'Pagina Beheerder',
    AppStrings.pagemangerdescription:
        'Verander paginagegevens, verander paginaleden, verander pagina berichten, verander pagina opmerkingen',
    AppStrings.groupmangerdescription:
        'Verander groepsgegevens, verander groepsleden, verander groepsberichten, verander groepsberichten opmerkingen',
    AppStrings.groupmoderatord: 'Groep Moderator',
    AppStrings.pagemoderatord: 'Pagina Moderator',
    AppStrings.pagemoderatorddescription:
        'Verander pagina berichten, verander pagina opmerkingen',
    AppStrings.groupmoderatorddescription:
        'Verander groepsberichten, verander groepsberichten opmerkingen',
    AppStrings.none: 'Geen',
    AppStrings.availablepermission: 'Beschikbare toestemming',
    AppStrings.altergroupdetails: 'Wijzig groepsgegevens',
    AppStrings.altergroupmembers: 'Wijzig groepsleden',
    AppStrings.altergroupposts: 'Wijzig groepsberichten',
    AppStrings.altergrouppostscomments: 'Wijzig groepsberichten opmerkingen',
    AppStrings.alterpagedetails: 'Wijzig paginagegevens',
    AppStrings.alterpagemembers: 'Wijzig paginaleden',
    AppStrings.alterpageposts: 'Wijzig pagina berichten',
    AppStrings.alterpagepostscomments: 'Wijzig pagina opmerkingen',
    AppStrings.updateuser: 'Werk gebruiker bij',
    AppStrings.editgroup: 'Bewerk groep',
    AppStrings.editpage: 'Bewerk pagina',
    AppStrings.deletegroup: 'Verwijder groep',
    AppStrings.deletepage: 'Verwijder pagina',
    AppStrings.groupmembers: 'Groepsleden',
    AppStrings.pagemembers: 'Paginaleden',
    AppStrings.report: 'Rapporteer',
    AppStrings.areyousureyouwanttodeletegroup:
        'Weet je zeker dat je de groep wilt verwijderen?',
    AppStrings.areyousureyouwanttodeletepage:
        'Weet je zeker dat je de pagina wilt verwijderen?',
    AppStrings.youremailisnotverified: 'Je e-mail is niet geverifieerd',
    AppStrings.unauthenticated: 'Niet geverifieerd',
    AppStrings.failedtodeletepost: 'Het verwijderen van het bericht is mislukt',
    AppStrings.addingapost: 'Een bericht toevoegen',
    AppStrings.golive: 'Ga live',
    AppStrings.location: 'Locatie',
    AppStrings.timestamp: 'Tijdstempel',
    AppStrings.votes: 'stemmen',
    AppStrings.short: 'kort',
    AppStrings.reply: 'antwoord',
    AppStrings.shortvideopost: 'korte videobericht',
    AppStrings.shares: 'Deelacties',
    AppStrings.share: 'Deel',
    AppStrings.comment: 'opmerking',
    AppStrings.hidecomments: 'Verberg opmerkingen',
    AppStrings.viewmorecomments: 'Bekijk meer opmerkingen',
    AppStrings.replytonamepost: 'antwoord op naam bericht',
    AppStrings.name: 'naam',
    AppStrings.onedayago: '1 dag geleden',
    AppStrings.promote: 'Promoot',
    AppStrings.increaseyourpopularity: 'Verhoog je populariteit',
    AppStrings.allocatecoinsforpromotions: 'Wijs munten toe voor promoties',
    AppStrings.like: 'Vind ik leuk',
    AppStrings.viewpost: 'Bekijk bericht',
    AppStrings.replypost: 'Beantwoord bericht',
    AppStrings.submitanewpost: 'DIEN EEN NIEUW BERICHT IN',
    AppStrings.submitanewpostdescription:
        'Vul dit rapport in met uitgebreide inhoud. Voeg zoveel mogelijk details toe in alle mogelijke vormen om een goede oplossing te krijgen.',
    AppStrings.content: 'inhoud',
    AppStrings.reportnow: 'Rapporteer nu',
    AppStrings.failedtoremovelock: 'Verwijderen van vergrendeling mislukt',
    AppStrings.password: 'Wachtwoord',
    AppStrings.unlock: 'Ontgrendelen',
    AppStrings.thesecredentialsdonotmatch:
        'Deze inloggegevens komen niet overeen',
    AppStrings.login: 'Inloggen',
    AppStrings.signin: 'aanmelden',
    AppStrings.signup: 'registreren',
    AppStrings.email: 'E-mail',
    AppStrings.rememberme: 'Onthoud mij',
    AppStrings.forgetpassword: 'Wachtwoord vergeten',
    AppStrings.notifications: 'Meldingen',
    AppStrings.pages: 'Pagina\'s',
    AppStrings.createnewpage: 'MAAK NIEUWE PAGINA',
    AppStrings.members: 'Leden',
    AppStrings.creators: 'Oprichters',
    AppStrings.page: 'Pagina',
    AppStrings.submitpage: 'Verstuur pagina',
    AppStrings.aboutthispage: 'Over deze pagina',
    AppStrings.writemoreaboutthispage: 'Schrijf meer over deze pagina',
    AppStrings.pagename: 'Paginanaam',
    AppStrings.private: 'privé',
    AppStrings.public: 'openbaar',
    AppStrings.invite: 'UITNODIGEN',
    AppStrings.about: 'OVER',
    AppStrings.photos: 'FOTO\'S',
    AppStrings.events: 'EVENEMENTEN',
    AppStrings.pagewillbepublic: 'Pagina zal openbaar zijn',
    AppStrings.pagefollowed: 'Pagina gevolgd',
    AppStrings.joinpage: 'Word lid van pagina',
    AppStrings.pageleavedsuccessfully: 'Pagina succesvol verlaten',
    AppStrings.pagejoinedsuccessfully: 'Pagina succesvol toegevoegd',
    AppStrings.userspage: 'Pagina van gebruiker',
    AppStrings.paymentcompletedsuccessfully: 'Betaling succesvol afgerond!',
    AppStrings.stripepayment: 'Stripe Betaling',
    AppStrings.myphotos: 'Mijn Foto\'s',
    AppStrings.recentphotos: 'Recente Foto\'s',
    AppStrings.recentposts: 'Recente Berichten',
    AppStrings.savedshorts: 'Opgeslagen Shorts',
    AppStrings.seeall: 'Bekijk Alles',
    AppStrings.groups: 'Groepen',
    AppStrings.errorloadingaccountdetails: 'Fout bij het laden van accountgegevens',
    AppStrings.errorloadingprofile: 'Fout bij het laden van profiel',
    AppStrings.timeline: 'Tijdlijn',
    AppStrings.saved: 'Opgeslagen',
    AppStrings.restricted: 'Beperkt',
    AppStrings.blocked: 'Geblokkeerd',
    AppStrings.register: 'Registreren',
    AppStrings.date: 'Datum',
    AppStrings.find: 'Zoeken',
    AppStrings.users: 'Gebruikers',
    AppStrings.status: 'Status',
    AppStrings.open: 'Open',
    AppStrings.closed: 'Gesloten',
    AppStrings.title: 'Titel',
    AppStrings.edittickets: 'Bewerk tickets',
    AppStrings.postareply: 'Plaats een antwoord',
    AppStrings.createdat: 'Gemaakt op',
    AppStrings.lastreplyby: 'Laatste antwoord door',
    AppStrings.repliesintotal: 'Aantal antwoorden',
    AppStrings.supportTickets: 'Support Tickets',
    AppStrings.ticketsummary: 'Ticket Samenvatting',
    AppStrings.availableactions: 'Beschikbare Acties',
    AppStrings.retypepassword: 'Herhaal wachtwoord',
    AppStrings.yourname: 'Jouw Naam',
    AppStrings.selectyourcountry: 'Selecteer jouw land',
    AppStrings.username: 'Gebruikersnaam',
    AppStrings.searchby: 'Zoeken op',
    AppStrings.searchresults: 'Zoekresultaten',
    AppStrings.searchpeoplegrouporpage: 'Zoeken naar mensen, groepen of pagina\'s',
    AppStrings.followaddedsuccessfully: 'Volgen succesvol toegevoegd',
    AppStrings.followremovedsuccessfully: 'Volgen succesvol verwijderd',
    AppStrings.pleaseverifyyuouremail: 'Verifieer alstublieft je e-mail',
    AppStrings.verifyyouraccount: 'Verifieer je account',
    AppStrings.sendverificationlink: 'Verzend verificatielink',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow: 'Als je al een link hebt ontvangen of als je een account hebt, log dan nu in',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere: 'Als je de link niet hebt ontvangen, klik dan hier',
    AppStrings.videos: 'Video\'s',
    AppStrings.videoselected: 'Video geselecteerd!',
    AppStrings.donate: 'Doneren',
    AppStrings.recentvideos: 'Recente Video\'s',
    AppStrings.firstofallselectvideo: 'Selecteer eerst een video',
    AppStrings.shortdescriprtiontags: 'Korte Beschrijving, #tags',
    AppStrings.postshort: '↑ Plaats short',
    AppStrings.pleaseselectavideofile: 'Selecteer een videobestand',
    AppStrings.donations: 'Donaties',
    AppStrings.topdonations: 'Top Donaties',
    AppStrings.helptheshortcreator: 'Help de creator van de short.',
    AppStrings.sharethispostto: 'Deel dit bericht naar',
    AppStrings.copylink: 'Kopieer link',
    AppStrings.selectanuser: 'SELECTEER EEN GEBRUIKER',
    AppStrings.user111: 'gebruiker111',
    AppStrings.sharenow: 'Deel nu',
    AppStrings.reopenticket: 'Heropen ticket',
    AppStrings.closeticket: 'Sluit ticket',
    AppStrings.supportsticket: 'Support ticket',
    AppStrings.totalticket: 'TOTALE TICKETS',
    AppStrings.solvedticket: 'OPGELOSTE TICKETS',
    AppStrings.openedissues: 'GEOPEND ISSUES',
    AppStrings.sendemail: 'Stuur e-mail',
    AppStrings.support: 'Ondersteuning',
    AppStrings.openticket: 'Open ticket',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto: 'Als je liever contact met ons wilt opnemen via e-mail, stuur dan je vraag naar:',
    AppStrings.ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure: 'Als je deze regel leest, lijkt het erop dat je probleem echt serieus is... laat het ons meer weten, we helpen je zeker.',
    AppStrings.createanewsupportticket: 'Maak een nieuw support ticket aan',
    AppStrings.newintervention: 'Nieuwe interventie',
    AppStrings.interventiontitle: 'Titel van interventie',
    AppStrings.typeherethetitle: 'Typ hier de titel',
    AppStrings.submitticket: 'Indienen ticket',
    AppStrings.submitcomment: 'Indienen commentaar',
    AppStrings.contentmustnotbelessthentencharacters: 'Inhoud mag niet minder zijn dan 10 tekens',
    AppStrings.completeinterventiontitle: 'Vul deze interventie in met uitgebreide inhoud. Voeg zoveel mogelijk details toe in alle mogelijke vormen voor een goede oplossing.',
    AppStrings.updatecomment: 'Werk commentaar bij',
    AppStrings.updatethereply: 'Werk het antwoord bij',
    AppStrings.commentcontent: 'Vul dit antwoord in met uitgebreide inhoud. Voeg zoveel mogelijk details toe in alle mogelijke vormen voor een goede oplossing.',
    AppStrings.thereisopeninterventionticketcloseitfirst: 'Er is een open interventie ticket, sluit het eerst.',
    AppStrings.addanewcomment: 'Voeg een nieuw commentaar toe',
    AppStrings.billingarea: 'Facturatiegebied',
    AppStrings.billingareacap: 'FACTURATIEGEBIED',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount: 'Blader door transacties en voeg meer munten toe aan je account',
    AppStrings.topup: 'Oplaad',
    AppStrings.gotopayment: 'Ga naar betaling',
    AppStrings.paymentfailed: 'Betaling mislukt',
    AppStrings.pleaseselectanamount: 'Selecteer een bedrag',
    AppStrings.showlatesttransactionscap: 'TONEN LAATSTE TRANSACTIES',
    AppStrings.transactionscap: 'TRANSACTIES',
    AppStrings.transactionnote: 'Volg en bekijk inkomende of uitgaande transacties en bereid je voor op je volgende prestaties.',
    AppStrings.searchtransactionsby: 'Zoek transacties op',
    AppStrings.searchtransactions: 'Zoek transacties',
    AppStrings.alltransactions: 'Alle transacties',
    AppStrings.transactionname: 'Transactienaam',
    AppStrings.transactionid: 'Transactie-ID',
    AppStrings.querytobeexecuted: 'Uit te voeren query',
    AppStrings.settingssaved: 'Instellingen opgeslagen',
    AppStrings.general: 'Algemeen',
    AppStrings.failedtosavesettigns: 'Fout bij het opslaan van instellingen',
    AppStrings.emailpreferences: 'E-mail voorkeuren',
    AppStrings.emailnotificationscap: 'E-MAIL NOTIFICATIES',
    AppStrings.savepreferences: 'Sla voorkeuren op',
    AppStrings.sendmeemailsaboutmyentireactivity: 'Stuur mij e-mails over mijn gehele activiteit',
    AppStrings.selectpushandemailnotificationyouliketorecieve: 'Selecteer push- en e-mailmeldingen die je wilt ontvangen',
    AppStrings.onlysendmerequiredemails: 'Stuur alleen noodzakelijke e-mails',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges: 'Let op: Je krijgt altijd meldingen voor individuele accountwijzigingen.',
    AppStrings.enablefollowmecap: 'ZET VOLG MIJ IN',
    AppStrings.sendmenotificationscap: 'STUUR MIJ MELDINGEN',
    AppStrings.enablethisifyouwantpeopletofollowyou: 'Zet dit in als je wilt dat mensen je volgen',
    AppStrings.sendmenotificationaboutmyfriendlike: 'Stuur mij een melding over de like van mijn vriend',
    AppStrings.shareormessageme: 'Deel of stuur mij een bericht.',
    AppStrings.hideyourprofilefromsearchengine: 'Verberg je profiel voor zoekmachines',
    AppStrings.searchprivacycap: 'ZOEK PRIVACY',
    AppStrings.hidegendercap: 'VERBERG GESLACHT',
    AppStrings.hideagecap: 'VERBERG LEEFTIJD',
    AppStrings.hidelocationcap: 'VERBERG LOCATIE',
    AppStrings.profilecap: 'PROFIEL',
    AppStrings.editprofilecap: 'Bewerk profiel',
    AppStrings.changecap: 'WIJZIG',
    AppStrings.displaynamecap: 'WEERGAVENAAM',
    AppStrings.peopleongenixwillgettoknowbybelowinfo: 'Mensen op Genix zullen je leren kennen via de onderstaande info',
    AppStrings.showingname: 'Weergavenaam',
    AppStrings.usernamecap: 'GEBRUIKERSNAAM',
    AppStrings.emailaddressecap: 'E-MAILADRES',
    AppStrings.youremailaddress: 'Je e-mailadres',
    AppStrings.gendercap: 'GESLACHT',

    AppStrings.male: 'Man',
    AppStrings.female: 'Vrouw',
    AppStrings.bio: 'Bio',
    AppStrings.tellusmoreaboutyou: 'Vertel ons meer over jou',
    AppStrings.socialprofilelinks: 'Sociale profiel links',
    AppStrings.citycap: 'STAD',
    AppStrings.countrycap: 'LAND',
    AppStrings.yourcity: 'Jouw stad',
    AppStrings.paypalemailaddress: 'PAY-PAL E-mailadres',
    AppStrings.enteryourpaypalemailaddress: 'Voer je PAY-PAL e-mailadres in',
    AppStrings.security: 'Beveiliging',
    AppStrings.accountpasswordcap: 'ACCOUNTWACHTWOORD',
    AppStrings.changeyourpasswordandalterothersecurityoptions: 'Wijzig je wachtwoord en pas andere beveiligingsopties aan',
    AppStrings.currentpasswordcap: 'HUIDIG WACHTWOORD',
    AppStrings.currentpassword: 'Huidig wachtwoord',
    AppStrings.newpassword: 'Nieuw wachtwoord',
    AppStrings.confirmpassword: 'Bevestig wachtwoord',
    AppStrings.repeatnewpassword: 'Herhaal nieuw wachtwoord',
    AppStrings.mineightcharacters: 'MIN 8 TEKENS',
    AppStrings.twofactorauthenticationcap: 'TWEE FACTOR AUTHENTICATIE',
    AppStrings.twofactorauthentication: 'Twee-factor authenticatie',
    AppStrings.enable: 'Inschakelen',
    AppStrings.enablecap: 'INSCHAKELEN',
    AppStrings.accountclosure: 'Accountsluiting',
    AppStrings.deleteyouraccountanddata: 'Verwijder je account en gegevens',
    AppStrings.areyousureyouwanttodeleteyouraccount: 'Weet je zeker dat je je account wilt verwijderen?',
    AppStrings.deletecap: 'VERWIJDEREN',
    AppStrings.settingscap: 'INSTELLINGEN',
    AppStrings.emails: 'E-mails',
    AppStrings.billings: 'Facturering',
    AppStrings.profile: 'Profiel',
    AppStrings.currentbalancecap: 'HUIDIG BALANS',
    AppStrings.revenuefromshortscap: 'OMZET VAN SHORTS',
    AppStrings.withdrawcap: 'OPNEMEN',
    AppStrings.coins: 'Munten',
    AppStrings.customamount: 'Aangepast bedrag',
    AppStrings.selectlanguage: "Taal selecteren",
    AppStrings.languagecap: "TAAL",
    AppStrings.changinglanguage: "Taal wijzigen...",
  };
}
