import 'package:genix/core/localization/all_app_strings.dart';

mixin AppLocaleEnglish {
  static const Map<String, dynamic> english = {
    AppStrings.somethingwentwrong: 'Something went wrong',
    AppStrings.nothingtodisplay: "Nothing to display...",
    AppStrings.chat: 'Chat',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Video',
    AppStrings.active: 'Active',
    AppStrings.inactive: 'Inactive',
    AppStrings.edit: 'Edit',
    AppStrings.yes: 'Yes',
    AppStrings.no: 'No',
    AppStrings.settings: 'Settings',
    AppStrings.getcoins: 'Get Coins',
    AppStrings.promotions: 'Promotions',
    AppStrings.errorloadingvideo: "Error loading video",
    AppStrings.errorloadingpage: "Error loading page",
    AppStrings.comments: 'Comments',
    AppStrings.replyto: 'Reply To',
    AppStrings.replytonamecomment: 'Reply To Name Comment',
    AppStrings.replies: 'Replies',
    AppStrings.post: 'post',
    AppStrings.nocommentsyet: 'No Comments Yet',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Type a message',
    AppStrings.nomessagesfound: "No messages found",
    AppStrings.failedtoloadthechatrroms: "Failed to load chat rooms",
    AppStrings.typeheretheusername: 'Type here the user name',
    AppStrings.lockscreen: 'Lock Screen',
    AppStrings.logout: 'Logout',
    AppStrings.darkmode: 'Dark Mode',
    AppStrings.followers: 'Followers',
    AppStrings.followings: 'Followings',
    AppStrings.recentfollowings: 'Recent Followings',
    AppStrings.recentfollowers: 'Recent Followers',
    AppStrings.groupnmae: 'Group Name',
    AppStrings.required: '  required',
    AppStrings.website: 'Website',
    AppStrings.category: 'Category',
    AppStrings.validwebsiteurl: 'Valid Website Url',
    AppStrings.aboutthisgroup: 'About This Group',
    AppStrings.areyousureyouwanttologout: 'Are You Sure You Want To Logout',
    AppStrings.writemoreaboutthisgroup: 'Write MOre about this group',
    AppStrings.sociallinks: 'Social Links',
    AppStrings.facebookprofilelink: 'Facebook Profile Link',
    AppStrings.xprofilelink: 'X Profile Link',
    AppStrings.instagramprofilelink: 'Instagram Profile Link',
    AppStrings.tiktokprofilelink: 'Tik Tok Profile Link',
    AppStrings.pinterestprofilelink: 'Pinterest Profile Link',
    AppStrings.steamprofilelink: 'Steam Profile Link',
    AppStrings.linkedInprofilelink: 'LinkedIn Profile Link',
    AppStrings.selectprivacy: 'Select Privacy',
    AppStrings.groupwillbepublic: 'Group Will be public',
    AppStrings.submitgroup: 'Submit group',
    AppStrings.allrequiredfieldsshouldbefilled:
        'All required fields should be filled',
    AppStrings.errorloadinggroupdata: 'Error Loading Group Data',
    AppStrings.artAndCulture: 'Art and Culture',
    AppStrings.scienceAndTechnology: 'Science and Technology',
    AppStrings.sport: 'Sport',
    AppStrings.music: 'Music',
    AppStrings.gastronomy: 'Gastronomy',
    AppStrings.fashionAndStyle: 'Fashion and Style',
    AppStrings.travelAndPlaces: 'Travel and Places',
    AppStrings.education: 'Education',
    AppStrings.career: 'Career',
    AppStrings.businessAndFinance: 'Business and Finance',
    AppStrings.entertainment: 'Entertainment',
    AppStrings.environmentAndEcology: 'Environment and Ecology',
    AppStrings.agricultureAndHorticulture: 'Agriculture and Horticulture',
    AppStrings.languagesAndCommunication: 'Languages and Communication',
    AppStrings.technologyAndDigital: 'Technology and Digital',
    AppStrings.architectureAndDesign: 'Architecture and Design',
    AppStrings.mediaAndJournalism: 'Media and Journalism',
    AppStrings.buyAndSell: 'Buy & Sell',
    AppStrings.selectacategory: 'Selecy A Category',
    AppStrings.groupprofilepicture: 'Group Profile Picture',
    AppStrings.selectaimage: 'Select A Image',
    AppStrings.groupcoverpicture: 'Group Cover Picture',
    AppStrings.createpost: 'Create Post',
    AppStrings.writesomething: ' Write Something...',
    AppStrings.createapoll: 'Create A Poll',
    AppStrings.pollquestion: 'Poll Questtion',
    AppStrings.polloption: 'Poll Option',
    AppStrings.addoption: '+ Add Option',
    AppStrings.checkin: 'Check In',
    AppStrings.current: 'Current',
    AppStrings.customLocation: 'custom location',
    AppStrings.onlyforclosefriend: 'Only For Close Friends?',
    AppStrings.newsfeed: 'News Feed',
    AppStrings.story: 'Story',
    AppStrings.contentmustbefilled: 'Content Must Be Filled',
    AppStrings.polloptions: 'Poll Options:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions:
        'Poll Must Have A Question And Atleast Two Options',
    AppStrings.firstofallselectanimage: 'First of all, select an image',
    AppStrings.browseondevice: 'Browse on device',
    AppStrings.joinedgroup: 'Joined Group',
    AppStrings.leavegroupsuccessfully: 'Leave Group Successfully',
    AppStrings.joingroup: 'Join Group',
    AppStrings.groupjoinedsuccessfully: 'Group Joined Successfully',
    AppStrings.postdeletedsuccessfully: 'Post deleted Successfully',
    AppStrings.deleteallusersposts: 'Delete all user\'s posts',
    AppStrings.deletealluserscomments: 'Delete all user\'s comments',
    AppStrings.deleteposts: 'Delete Posts',
    AppStrings.deletecomments: 'Delete Comments',
    AppStrings.removethisuser: 'Remove this user',
    AppStrings.delete: 'delete',
    AppStrings.editmemberdetails: 'EDIT MEMBER DETAILS',
    AppStrings.availableroles: 'Available Roles',
    AppStrings.groupmanger: 'Group Manager',
    AppStrings.pagemanger: 'Page Manager',
    AppStrings.pagemangerdescription:
        'alter page details, alter page members, alter page posts, alter page posts comments',
    AppStrings.groupmangerdescription:
        'alter group details, alter group members, alter group posts, alter group posts comments',
    AppStrings.groupmoderatord: 'Group Moderator',
    AppStrings.pagemoderatord: 'Page Moderator',
    AppStrings.pagemoderatorddescription:
        'alter page posts, alter page posts comments',
    AppStrings.groupmoderatorddescription:
        'alter group posts, alter group posts comments',
    AppStrings.none: 'None',
    AppStrings.availablepermission: 'Available Permission',
    AppStrings.altergroupdetails: 'Alter group details',
    AppStrings.altergroupmembers: 'Alter group members',
    AppStrings.altergroupposts: 'Alter group posts',
    AppStrings.altergrouppostscomments: 'Alter group posts comments',
    AppStrings.alterpagedetails: 'Alter page details',
    AppStrings.alterpagemembers: 'Alter page members',
    AppStrings.alterpageposts: 'Alter page posts',
    AppStrings.alterpagepostscomments: 'Alter page posts comments',
    AppStrings.updateuser: 'Update User',
    AppStrings.editgroup: 'Edit Group',
    AppStrings.editpage: 'Edit Page',
    AppStrings.deletegroup: 'Delete Group',
    AppStrings.deletepage: 'Delete Page',
    AppStrings.groupmembers: 'Group Members',
    AppStrings.pagemembers: 'Page Members',
    AppStrings.report: 'Report',
    AppStrings.areyousureyouwanttodeletegroup:
        'Are you sure you want to delete group?',
    AppStrings.areyousureyouwanttodeletepage:
        'Are you sure you want to delete page?',
    AppStrings.youremailisnotverified: 'Your email is not verified',
    AppStrings.unauthenticated: 'Unauthenticated',
    AppStrings.failedtodeletepost: 'Failed to delete post',
    AppStrings.addingapost: 'adding a post',
    AppStrings.golive: 'Go Live',
    AppStrings.location: 'Location',
    AppStrings.timestamp: 'Timestamp',
    AppStrings.votes: 'votes',
    AppStrings.short: 'short',
    AppStrings.reply: 'reply',
    AppStrings.shortvideopost: 'short video post',
    AppStrings.shares: 'Shares',
    AppStrings.share: 'Share',
    AppStrings.comment: 'comment',
    AppStrings.hidecomments: 'Hide Comments',
    AppStrings.viewmorecomments: 'View More Comments',
    AppStrings.replytonamepost: 'reply to name post',
    AppStrings.name: 'name',
    AppStrings.onedayago: '1 day ago',
    AppStrings.promote: 'Promote',
    AppStrings.increaseyourpopularity: 'Increase your popularity',
    AppStrings.allocatecoinsforpromotions: 'Allocate coins for promotions',
    AppStrings.like: 'Like',
    AppStrings.viewpost: 'View Post',
    AppStrings.replypost: 'Reply Post',
    AppStrings.submitanewpost: 'SUBMIT A NEW POST',
    AppStrings.submitanewpostdescription:
        'Feed this report with a comprehensive content. please include as many details as you can, in all the possible forms to get a proper resolution.',
    AppStrings.content: 'content',
    AppStrings.reportnow: 'reportnow',
    AppStrings.failedtoremovelock: 'Failed to remove lock',
    AppStrings.password: 'Password',
    AppStrings.unlock: 'Unlock',
    AppStrings.thesecredentialsdonotmatch: 'These credentials do not match',
    AppStrings.login: 'Log In',
    AppStrings.signin: 'sign in',
    AppStrings.signup: 'signup',
    AppStrings.email: 'E-Main',
    AppStrings.rememberme: 'Remember Me',
    AppStrings.forgetpassword: 'Forget Password',
    AppStrings.notifications: 'Notifications',
    AppStrings.pages: 'pages',
    AppStrings.createnewpage: 'CREATE NEW PAGE',
    AppStrings.members: 'Members',
    AppStrings.creators: 'Creators',
    AppStrings.page: 'Page',
    AppStrings.submitpage: 'Submit Page',
    AppStrings.aboutthispage: 'About this Page',
    AppStrings.writemoreaboutthispage: 'Write More About this Page',
    AppStrings.pagename: 'Page Name',
    AppStrings.private: 'private',
    AppStrings.public: 'public',
    AppStrings.invite: 'INVITE',
    AppStrings.about: 'ABOUT',
    AppStrings.photos: 'PHOTOS',
    AppStrings.events: 'EVENTS',
    AppStrings.pagewillbepublic: 'Page will be public',
    AppStrings.pagefollowed: 'Page Followed',
    AppStrings.joinpage: 'Join Page',
    AppStrings.pageleavedsuccessfully: 'Page Leaved Successfully',
    AppStrings.pagejoinedsuccessfully: 'Page Joined Successfully',
    AppStrings.userspage: 'User\'s page',
    AppStrings.paymentcompletedsuccessfully: 'Payment completed successfully!',
    AppStrings.stripepayment: 'Stripe Payment',
    AppStrings.myphotos: 'My Photos',
    AppStrings.recentphotos: 'Recent Photos',
    AppStrings.recentposts: 'Recent Posts',
    AppStrings.savedshorts: 'Saved Shorts',
    AppStrings.seeall: 'See All',
    AppStrings.groups: 'Groups',
    AppStrings.errorloadingaccountdetails: 'Error Loading Account Details',
    AppStrings.errorloadingprofile: 'Error Loading Profile',
    AppStrings.timeline: 'Timeline',
    AppStrings.saved: 'Saved',
    AppStrings.restricted: 'Restricted',
    AppStrings.blocked: 'Blocked',
    AppStrings.register: 'Register',
    AppStrings.date: 'Date',
    AppStrings.find: 'Find',
    AppStrings.users: 'Users',
    AppStrings.status: 'Status',
    AppStrings.open: 'Open',
    AppStrings.closed: 'Closed',
    AppStrings.title: 'Title',
    AppStrings.edittickets: 'Edit tickets',
    AppStrings.postareply: 'Post a reply',
    AppStrings.createdat: 'Created At',
    AppStrings.lastreplyby: 'Last reply By',
    AppStrings.repliesintotal: 'Replies in total',
    AppStrings.supportTickets: 'Support Tickets',
    AppStrings.ticketsummary: 'Ticket Summary',
    AppStrings.availableactions: 'Available Actions',
    AppStrings.retypepassword: 'Retype Password',
    AppStrings.yourname: 'Your Name',
    AppStrings.selectyourcountry: 'Select Your Country',
    AppStrings.username: 'User Name',
    AppStrings.searchby: 'Search By',
    AppStrings.searchresults: 'Search Results',
    AppStrings.searchpeoplegrouporpage: 'Search People, group or pages',
    AppStrings.followaddedsuccessfully: 'Follow Added Successfully',
    AppStrings.followremovedsuccessfully: 'Follow Removed Successfully',
    AppStrings.pleaseverifyyuouremail: 'Please Verify Your email',
    AppStrings.verifyyouraccount: 'verify your account',
    AppStrings.sendverificationlink: 'Send Verification Link',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
        'if you have already received a link or if you have an account , log in now',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere:
        'if you have\'t received a link please click here',
    AppStrings.videos: 'Videos',
    AppStrings.videoselected: 'Video Selected!',
    AppStrings.donate: 'Donate',
    AppStrings.recentvideos: 'Recent Videos',
    AppStrings.firstofallselectvideo: 'First of all, select a video',
    AppStrings.shortdescriprtiontags: 'Short Description,  #tags',
    AppStrings.postshort: '↑ Post short',
    AppStrings.pleaseselectavideofile: '',
    AppStrings.donations: 'Donations',
    AppStrings.topdonations: 'Top Donations',
    AppStrings.helptheshortcreator: 'Help the short creator.',
    AppStrings.sharethispostto: 'Share this post to',
    AppStrings.copylink: 'copy link',
    AppStrings.selectanuser: 'SELECT AN USER',
    AppStrings.user111: 'user111',
    AppStrings.sharenow: 'Share Now',
    AppStrings.reopenticket: 'Reopen ticket',
    AppStrings.closeticket: 'Close ticket',
    AppStrings.supportsticket: 'Supports ticket',
    AppStrings.totalticket: 'TOTAL TICKETS',
    AppStrings.solvedticket: 'SOLVED TICKETS',
    AppStrings.openedissues: 'OPENED ISSUES',
    AppStrings.sendemail: 'Send email',
    AppStrings.support: 'Support',
    AppStrings.openticket: 'Open ticket',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
        'If you would prefer to contact us by email, please send us your inquiry to:',
    AppStrings
            .ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
        'If you read this line it looks like your issue is really serious.. please let us know more about this, we will help you for sure.',
    AppStrings.createanewsupportticket: 'Create a new support ticket',
    AppStrings.newintervention: 'New Intervention',
    AppStrings.interventiontitle: 'Intervention title',
    AppStrings.typeherethetitle: 'Type here the title',
    AppStrings.submitticket: 'submit ticket',
    AppStrings.submitcomment: 'submit comment',
    AppStrings.contentmustnotbelessthentencharacters:
        'Content must not be less then 10 characters',
    AppStrings.completeinterventiontitle:
        'Feed this intervention with a comprehensive content. please include as many details as you can, in all the possible forms to get a proper resolution.',
    AppStrings.updatecomment: 'update comment',
    AppStrings.updatethereply: 'update the reply',
    AppStrings.commentcontent:
        'Feed this reply with a comprehensive content. please include as many details as you can, in all the possible forms to get a proper resolution.',
    AppStrings.thereisopeninterventionticketcloseitfirst:
        'There is an open intervention ticket, please close it first.',
    AppStrings.addanewcomment: 'Add a new comment',
    AppStrings.billingarea: 'Billing area',
    AppStrings.billingareacap: 'BILLING AREA',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount:
        'Browse transactions, and add more coins into your account',
    AppStrings.topup: 'TOP UP',
    AppStrings.gotopayment: 'Go to payment',
    AppStrings.paymentfailed: 'Payment failed',
    AppStrings.pleaseselectanamount: 'Please select an amount',
    AppStrings.showlatesttransactionscap: 'SHOW LATEST TRANSACTIONS',
    AppStrings.transactionscap: 'TRANSACTIONS',
    AppStrings.transactionnote:
        'Track and view inbound or outbound transactions and get ready for your next achievements.',
    AppStrings.searchtransactionsby: 'Search Transactions by',
    AppStrings.searchtransactions: 'Search Transactions',
    AppStrings.alltransactions: 'All transactions',
    AppStrings.transactionname: 'Transaction name',
    AppStrings.transactionid: 'Transaction id',
    AppStrings.querytobeexecuted: 'Query to be executed',
    AppStrings.settingssaved: 'Settings Saved',
    AppStrings.general: 'General',
    AppStrings.failedtosavesettigns: 'Failed to save settings',
    AppStrings.emailpreferences: 'Email Preferences',
    AppStrings.emailnotificationscap: 'EMAIL NOTIFICATIONS',
    AppStrings.savepreferences: 'Save Preferences',
    AppStrings.sendmeemailsaboutmyentireactivity:
        'Send me emails about my entire activity',
    AppStrings.selectpushandemailnotificationyouliketorecieve:
        'Select push and email notifications you\'d like to receive',
    AppStrings.onlysendmerequiredemails: 'Only send me required emails',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges:
        'Note: You will always get notifications for individual account changes.',
    AppStrings.enablefollowmecap: 'ENABLE FOLLOW ME',
    AppStrings.sendmenotificationscap: 'SEND ME NOTIFICATIONS',
    AppStrings.enablethisifyouwantpeopletofollowyou:
        'Enable this if you want people to follow you',
    AppStrings.sendmenotificationaboutmyfriendlike:
        'Send me notification about my friend like',
    AppStrings.shareormessageme: 'Share or message me.',
    AppStrings.hideyourprofilefromsearchengine:
        'Hide your profile from search engine',
    AppStrings.searchprivacycap: 'SEARCH PRIVACY',
    AppStrings.hidegendercap: 'HIDE GENDER',
    AppStrings.hideagecap: 'HIDE AGE',
    AppStrings.hidelocationcap: 'HIDE LOCATION',
    AppStrings.profilecap: 'PROFILE',
    AppStrings.editprofilecap: 'EDIT PROFILE',
    AppStrings.changecap: 'CHANGE',
    AppStrings.displaynamecap: 'DISPLAY NAME',
    AppStrings.peopleongenixwillgettoknowbybelowinfo:
        'People on Genix will get to know by below info',
    AppStrings.showingname: 'Showing name',
    AppStrings.usernamecap: 'USERNAME',
    AppStrings.emailaddressecap: 'EMAIL ADDRESS',
    AppStrings.youremailaddress: 'Your email address',
    AppStrings.gendercap: 'GENDER',
    AppStrings.male: 'Male',
    AppStrings.female: 'Female',
    AppStrings.bio: 'Bio',
    AppStrings.tellusmoreaboutyou: 'Tell us more about you',
    AppStrings.socialprofilelinks: 'Social Profile Links',
    AppStrings.citycap: 'CITY',
    AppStrings.countrycap: 'COUNTRY',
    AppStrings.yourcity: 'Your city',
    AppStrings.paypalemailaddress: 'PAY-PAL Email Address',
    AppStrings.enteryourpaypalemailaddress: 'Enter your PAY-PAL Email Address',
    AppStrings.security: 'Security',
    AppStrings.accountpasswordcap: 'ACCOUNT PASSWORD',
    AppStrings.changeyourpasswordandalterothersecurityoptions:
        'Change your password and alter other security options',
    AppStrings.currentpasswordcap: 'CURRENT PASSWORD',
    AppStrings.currentpassword: 'Current Password',
    AppStrings.newpassword: 'New Password',
    AppStrings.confirmpassword: 'Confirm Password',
    AppStrings.repeatnewpassword: 'Repeat New Password',
    AppStrings.mineightcharacters: 'MIN 8 CHARACTERS',
    AppStrings.twofactorauthenticationcap: 'TWO FACTOR AUTHENTICATION',
    AppStrings.twofactorauthentication: 'Two factor authentication',
    AppStrings.enable: 'Enable',
    AppStrings.enablecap: 'ENABLE',
    AppStrings.accountclosure: 'Account Closure',
    AppStrings.deleteyouraccountanddata: 'Delete Your Account And Data',
    AppStrings.areyousureyouwanttodeleteyouraccount:
        'Are you sure you want to delete your account?',
    AppStrings.deletecap: 'DELETE',
    AppStrings.settingscap: 'SETTINGS',
    AppStrings.emails: 'Emails',
    AppStrings.billings: 'Billings',
    AppStrings.profile: 'Profile',
    AppStrings.currentbalancecap: 'CURRENT BALANCE',
    AppStrings.revenuefromshortscap: 'REVENUE FROM SHORTS',
    AppStrings.withdrawcap: 'WITHDRAW',
    AppStrings.coins: 'Coins',
    AppStrings.customamount: 'Custom amount',
    AppStrings.selectlanguage: "Select Language",
    AppStrings.languagecap: "LANGUAGE",
    AppStrings.changinglanguage: "Changing Language...",
  };
}
