import 'package:genix/core/localization/all_app_strings.dart';

mixin AppLocaleSpanish {
  static const Map<String, dynamic> spanish = {
    AppStrings.somethingwentwrong: 'Algo salió mal',
    AppStrings.nothingtodisplay: "Nada que mostrar...",
    AppStrings.chat: 'Chat',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Video',
    AppStrings.active: 'Activo',
    AppStrings.inactive: 'Inactivo',
    AppStrings.edit: 'Editar',
    AppStrings.yes: 'Sí',
    AppStrings.no: 'No',
    AppStrings.settings: 'Configuración',
    AppStrings.getcoins: 'Obtener Monedas',
    AppStrings.promotions: 'Promociones',
    AppStrings.errorloadingvideo: "Error al cargar el video",
    AppStrings.errorloadingpage: "Error al cargar la página",
    AppStrings.comments: 'Comentarios',
    AppStrings.replyto: 'Responder a',
    AppStrings.replytonamecomment: 'Responder al comentario de',
    AppStrings.replies: 'Respuestas',
    AppStrings.post: 'Publicación',
    AppStrings.nocommentsyet: 'Aún no hay comentarios',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Escribe un mensaje',
    AppStrings.nomessagesfound: "No se encontraron mensajes",
    AppStrings.failedtoloadthechatrroms:
        "No se pudieron cargar las salas de chat",
    AppStrings.typeheretheusername: 'Escribe aquí el nombre de usuario',
    AppStrings.lockscreen: 'Bloquear Pantalla',
    AppStrings.logout: 'Cerrar Sesión',
    AppStrings.darkmode: 'Modo Oscuro',
    AppStrings.followers: 'Seguidores',
    AppStrings.followings: 'Siguiendo',
    AppStrings.recentfollowings: 'Seguimientos Recientes',
    AppStrings.recentfollowers: 'Seguidores Recientes',
    AppStrings.groupnmae: 'Nombre del Grupo',
    AppStrings.required: '  requerido',
    AppStrings.website: 'Sitio Web',
    AppStrings.category: 'Categoría',
    AppStrings.validwebsiteurl: 'URL de Sitio Web Válida',
    AppStrings.aboutthisgroup: 'Sobre Este Grupo',
    AppStrings.areyousureyouwanttologout:
        '¿Está seguro que desea cerrar sesión?',
    AppStrings.writemoreaboutthisgroup: 'Escriba más sobre este grupo',
    AppStrings.sociallinks: 'Enlaces Sociales',
    AppStrings.facebookprofilelink: 'Enlace de Perfil de Facebook',
    AppStrings.xprofilelink: 'Enlace de Perfil de X',
    AppStrings.instagramprofilelink: 'Enlace de Perfil de Instagram',
    AppStrings.tiktokprofilelink: 'Enlace de Perfil de TikTok',
    AppStrings.pinterestprofilelink: 'Enlace de Perfil de Pinterest',
    AppStrings.steamprofilelink: 'Enlace de Perfil de Steam',
    AppStrings.linkedInprofilelink: 'Enlace de Perfil de LinkedIn',
    AppStrings.selectprivacy: 'Seleccionar Privacidad',
    AppStrings.groupwillbepublic: 'El grupo será público',
    AppStrings.submitgroup: 'Enviar Grupo',
    AppStrings.allrequiredfieldsshouldbefilled:
        'Todos los campos requeridos deben ser llenados',
    AppStrings.errorloadinggroupdata: 'Error al cargar datos del grupo',
    AppStrings.artAndCulture: 'Arte y Cultura',
    AppStrings.scienceAndTechnology: 'Ciencia y Tecnología',
    AppStrings.sport: 'Deporte',
    AppStrings.music: 'Música',
    AppStrings.gastronomy: 'Gastronomía',
    AppStrings.fashionAndStyle: 'Moda y Estilo',
    AppStrings.travelAndPlaces: 'Viajes y Lugares',
    AppStrings.education: 'Educación',
    AppStrings.career: 'Carrera',
    AppStrings.businessAndFinance: 'Negocios y Finanzas',
    AppStrings.entertainment: 'Entretenimiento',
    AppStrings.environmentAndEcology: 'Medio Ambiente y Ecología',
    AppStrings.agricultureAndHorticulture: 'Agricultura y Horticultura',
    AppStrings.languagesAndCommunication: 'Idiomas y Comunicación',
    AppStrings.technologyAndDigital: 'Tecnología y Digital',
    AppStrings.architectureAndDesign: 'Arquitectura y Diseño',
    AppStrings.mediaAndJournalism: 'Medios y Periodismo',
    AppStrings.buyAndSell: 'Compra y Venta',
    AppStrings.selectacategory: 'Seleccione una Categoría',
    AppStrings.groupprofilepicture: 'Imagen de Perfil del Grupo',
    AppStrings.selectaimage: 'Seleccione una Imagen',
    AppStrings.groupcoverpicture: 'Imagen de Portada del Grupo',
    AppStrings.createpost: 'Crear Publicación',
    AppStrings.writesomething: 'Escribe algo...',
    AppStrings.createapoll: 'Crear una Encuesta',
    AppStrings.pollquestion: 'Pregunta de Encuesta',
    AppStrings.polloption: 'Opción de Encuesta',
    AppStrings.addoption: '+ Agregar Opción',
    AppStrings.checkin: 'Registrarse',
    AppStrings.current: 'Actual',
    AppStrings.customLocation: 'ubicación personalizada',
    AppStrings.onlyforclosefriend: '¿Solo para amigos cercanos?',
    AppStrings.newsfeed: 'Noticias',
    AppStrings.story: 'Historia',
    AppStrings.contentmustbefilled: 'El contenido debe ser llenado',
    AppStrings.polloptions: 'Opciones de Encuesta:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions:
        'La encuesta debe tener una pregunta y al menos dos opciones',
    AppStrings.firstofallselectanimage: 'Primero, seleccione una imagen',
    AppStrings.browseondevice: 'Examinar en el dispositivo',
    AppStrings.joinedgroup: 'Grupo Unido',
    AppStrings.leavegroupsuccessfully: 'Grupo Abandonado Exitosamente',
    AppStrings.joingroup: 'Unirse al Grupo',
    AppStrings.groupjoinedsuccessfully: 'Grupo Unido Exitosamente',
    AppStrings.postdeletedsuccessfully: 'Publicación Eliminada Exitosamente',
    AppStrings.deleteallusersposts:
        'Eliminar todas las publicaciones del usuario',
    AppStrings.deletealluserscomments:
        'Eliminar todos los comentarios del usuario',
    AppStrings.deleteposts: 'Eliminar Publicaciones',
    AppStrings.deletecomments: 'Eliminar Comentarios',
    AppStrings.removethisuser: 'Eliminar este usuario',
    AppStrings.delete: 'eliminar',
    AppStrings.editmemberdetails: 'EDITAR DETALLES DE MIEMBRO',
    AppStrings.availableroles: 'Roles Disponibles',
    AppStrings.groupmanger: 'Administrador de Grupo',
    AppStrings.pagemanger: 'Administrador de Página',
    AppStrings.pagemangerdescription:
        'modificar detalles de página, modificar miembros de página, modificar publicaciones de página, modificar comentarios de publicaciones de página',
    AppStrings.groupmangerdescription:
        'modificar detalles de grupo, modificar miembros de grupo, modificar publicaciones de grupo, modificar comentarios de publicaciones de grupo',
    AppStrings.groupmoderatord: 'Moderador de Grupo',
    AppStrings.pagemoderatord: 'Moderador de Página',
    AppStrings.pagemoderatorddescription:
        'modificar publicaciones de página, modificar comentarios de publicaciones de página',
    AppStrings.groupmoderatorddescription:
        'modificar publicaciones de grupo, modificar comentarios de publicaciones de grupo',
    AppStrings.none: 'Ninguno',
    AppStrings.availablepermission: 'Permisos Disponibles',
    AppStrings.altergroupdetails: 'Modificar detalles del grupo',
    AppStrings.altergroupmembers: 'Modificar miembros del grupo',
    AppStrings.altergroupposts: 'Modificar publicaciones del grupo',
    AppStrings.altergrouppostscomments:
        'Modificar comentarios de publicaciones del grupo',
    AppStrings.alterpagedetails: 'Modificar detalles de la página',
    AppStrings.alterpagemembers: 'Modificar miembros de la página',
    AppStrings.alterpageposts: 'Modificar publicaciones de la página',
    AppStrings.alterpagepostscomments:
        'Modificar comentarios de publicaciones de la página',
    AppStrings.updateuser: 'Actualizar Usuario',
    AppStrings.editgroup: 'Editar Grupo',
    AppStrings.editpage: 'Editar Página',
    AppStrings.deletegroup: 'Eliminar Grupo',
    AppStrings.deletepage: 'Eliminar Página',
    AppStrings.groupmembers: 'Miembros del Grupo',
    AppStrings.pagemembers: 'Miembros de la Página',
    AppStrings.report: 'Reportar',
    AppStrings.areyousureyouwanttodeletegroup:
        '¿Está seguro que desea eliminar el grupo?',
    AppStrings.areyousureyouwanttodeletepage:
        '¿Está seguro que desea eliminar la página?',
    AppStrings.youremailisnotverified:
        'Su correo electrónico no está verificado',
    AppStrings.unauthenticated: 'No autenticado',
    AppStrings.failedtodeletepost: 'Error al eliminar la publicación',
    AppStrings.addingapost: 'agregando una publicación',
    AppStrings.golive: 'Ir en Vivo',
    AppStrings.location: 'Ubicación',
    AppStrings.timestamp: 'Marca de tiempo',
    AppStrings.votes: 'votos',
    AppStrings.short: 'corto',
    AppStrings.reply: 'responder',
    AppStrings.shortvideopost: 'publicación de video corto',
    AppStrings.shares: 'Compartidos',
    AppStrings.share: 'Compartir',
    AppStrings.comment: 'comentario',
    AppStrings.hidecomments: 'Ocultar Comentarios',
    AppStrings.viewmorecomments: 'Ver Más Comentarios',
    AppStrings.replytonamepost: 'responder a publicación de',
    AppStrings.name: 'nombre',
    AppStrings.onedayago: 'Hace 1 día',
    AppStrings.promote: 'Promocionar',
    AppStrings.increaseyourpopularity: 'Aumenta tu popularidad',
    AppStrings.allocatecoinsforpromotions: 'Asignar monedas para promociones',
    AppStrings.like: 'Me gusta',
    AppStrings.viewpost: 'Ver Publicación',
    AppStrings.replypost: 'Responder Publicación',
    AppStrings.submitanewpost: 'ENVIAR UNA NUEVA PUBLICACIÓN',
    AppStrings.submitanewpostdescription:
        'Alimenta este informe con un contenido completo. Por favor, incluya tantos detalles como pueda, en todas las formas posibles para obtener una resolución adecuada.',
    AppStrings.content: 'contenido',
    AppStrings.reportnow: 'reportar ahora',
    AppStrings.failedtoremovelock: 'Error al eliminar el bloqueo',
    AppStrings.password: 'Contraseña',
    AppStrings.unlock: 'Desbloquear',
    AppStrings.thesecredentialsdonotmatch: 'Estas credenciales no coinciden',
    AppStrings.login: 'Iniciar Sesión',
    AppStrings.signin: 'iniciar sesión',
    AppStrings.signup: 'registrarse',
    AppStrings.email: 'Correo Electrónico',
    AppStrings.rememberme: 'Recordarme',
    AppStrings.forgetpassword: 'Olvidé la Contraseña',
    AppStrings.notifications: 'Notificaciones',
    AppStrings.pages: 'Páginas',
    AppStrings.createnewpage: 'CREAR NUEVA PÁGINA',
    AppStrings.members: 'Miembros',
    AppStrings.creators: 'Creadores',
    AppStrings.page: 'Página',
    AppStrings.submitpage: 'Enviar Página',
    AppStrings.aboutthispage: 'Sobre esta Página',
    AppStrings.writemoreaboutthispage: 'Escriba más sobre esta Página',
    AppStrings.pagename: 'Nombre de la Página',
    AppStrings.private: 'privado',
    AppStrings.public: 'público',
    AppStrings.invite: 'INVITAR',
    AppStrings.about: 'SOBRE',
    AppStrings.photos: 'FOTOS',
    AppStrings.events: 'EVENTOS',
    AppStrings.pagewillbepublic: 'La página será pública',
    AppStrings.pagefollowed: 'Página Seguida',
    AppStrings.joinpage: 'Unirse a la Página',
    AppStrings.pageleavedsuccessfully: 'Página Abandonada Exitosamente',
    AppStrings.pagejoinedsuccessfully: 'Página Unida Exitosamente',
    AppStrings.userspage: 'Página del Usuario',
    AppStrings.paymentcompletedsuccessfully: '¡Pago completado con éxito!',
    AppStrings.stripepayment: 'Pago de Stripe',
    AppStrings.myphotos: 'Mis Fotos',
    AppStrings.recentphotos: 'Fotos Recientes',
    AppStrings.recentposts: 'Publicaciones Recientes',
    AppStrings.savedshorts: 'Cortos Guardados',
    AppStrings.seeall: 'Ver Todo',
    AppStrings.groups: 'Grupos',
    AppStrings.errorloadingaccountdetails:
        'Error al cargar los detalles de la cuenta',
    AppStrings.errorloadingprofile: 'Error al cargar el perfil',
    AppStrings.timeline: 'Línea de tiempo',
    AppStrings.saved: 'Guardado',
    AppStrings.restricted: 'Restringido',
    AppStrings.blocked: 'Bloqueado',
    AppStrings.register: 'Registrarse',
    AppStrings.date: 'Fecha',
    AppStrings.find: 'Encontrar',
    AppStrings.users: 'Usuarios',
    AppStrings.status: 'Estado',
    AppStrings.open: 'Abierto',
    AppStrings.closed: 'Cerrado',
    AppStrings.title: 'Título',
    AppStrings.edittickets: 'Editar tickets',
    AppStrings.postareply: 'Publicar una respuesta',
    AppStrings.createdat: 'Creado el',
    AppStrings.lastreplyby: 'Última respuesta por',
    AppStrings.repliesintotal: 'Respuestas en total',
    AppStrings.supportTickets: 'Tickets de Soporte',
    AppStrings.ticketsummary: 'Resumen del Ticket',
    AppStrings.availableactions: 'Acciones Disponibles',
    AppStrings.retypepassword: 'Reescribir Contraseña',
    AppStrings.yourname: 'Su Nombre',
    AppStrings.selectyourcountry: 'Seleccione Su País',
    AppStrings.username: 'Nombre de Usuario',
    AppStrings.searchby: 'Buscar Por',
    AppStrings.searchresults: 'Resultados de Búsqueda',
    AppStrings.searchpeoplegrouporpage: 'Buscar Personas, grupo o páginas',
    AppStrings.followaddedsuccessfully: 'Seguimiento Agregado Exitosamente',
    AppStrings.followremovedsuccessfully: 'Seguimiento Eliminado Exitosamente',
    AppStrings.pleaseverifyyuouremail:
        'Por favor, verifique su correo electrónico',
    AppStrings.verifyyouraccount: 'Verificar su cuenta',
    AppStrings.sendverificationlink: 'Enviar Enlace de Verificación',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
        'si ya ha recibido un enlace o si tiene una cuenta, inicie sesión ahora',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere:
        'si no ha recibido un enlace, haga clic aquí',
    AppStrings.videos: 'Videos',
    AppStrings.videoselected: '¡Video Seleccionado!',
    AppStrings.donate: 'Donar',
    AppStrings.recentvideos: 'Videos Recientes',
    AppStrings.firstofallselectvideo: 'Primero, seleccione un video',
    AppStrings.shortdescriprtiontags: 'Descripción Corta, #etiquetas',
    AppStrings.postshort: '↑ Publicar corto',
    AppStrings.pleaseselectavideofile: '',
    AppStrings.donations: 'Donaciones',
    AppStrings.topdonations: 'Mejores Donaciones',
    AppStrings.helptheshortcreator: 'Ayuda al creador del video corto.',
    AppStrings.sharethispostto: 'Compartir esta publicación en',
    AppStrings.copylink: 'copiar enlace',
    AppStrings.selectanuser: 'SELECCIONAR UN USUARIO',
    AppStrings.user111: 'usuario111',
    AppStrings.sharenow: 'Compartir Ahora',
    AppStrings.reopenticket: 'Reabrir ticket',
  AppStrings.closeticket: 'Cerrar ticket',
  AppStrings.supportsticket: 'Ticket de soporte',
  AppStrings.totalticket: 'TICKETS TOTALES',
  AppStrings.solvedticket: 'TICKETS RESUELTOS',
  AppStrings.openedissues: 'PROBLEMAS ABIERTOS',
  AppStrings.sendemail: 'Enviar correo electrónico',
  AppStrings.support: 'Soporte',
  AppStrings.openticket: 'Abrir ticket',
  AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
  'Si prefiere contactarnos por correo electrónico, envíe su consulta a:',
  AppStrings.ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
  'Si lee esta línea, parece que su problema es realmente grave... por favor, cuéntenos más al respecto, le ayudaremos sin duda.',
  AppStrings.createanewsupportticket: 'Crear un nuevo ticket de soporte',
  AppStrings.newintervention: 'Nueva intervención',
  AppStrings.interventiontitle: 'Título de la intervención',
  AppStrings.typeherethetitle: 'Escriba aquí el título',
  AppStrings.submitticket: 'enviar ticket',
  AppStrings.submitcomment: 'enviar comentario',
  AppStrings.contentmustnotbelessthentencharacters:
  'El contenido no debe tener menos de diez caracteres',
  AppStrings.completeinterventiontitle:
  'Complete esta intervención con un contenido exhaustivo. Por favor, incluya tantos detalles como sea posible, en todas las formas posibles para obtener una resolución adecuada.',
  AppStrings.updatecomment: 'actualizar comentario',
  AppStrings.updatethereply: 'actualizar la respuesta',
  AppStrings.commentcontent:
  'Complete esta respuesta con un contenido exhaustivo. Por favor, incluya tantos detalles como sea posible, en todas las formas posibles para obtener una resolución adecuada.',
  AppStrings.thereisopeninterventionticketcloseitfirst:
  'Hay un ticket de intervención abierto, ciérrelo primero.',
  AppStrings.addanewcomment: 'Añadir un nuevo comentario',
  AppStrings.billingarea: 'Área de facturación',
  AppStrings.billingareacap: 'ÁREA DE FACTURACIÓN',
  AppStrings.browsetransactionsandaddmorecoinstoyouraccount:
  'Explore transacciones y añada más monedas a su cuenta',
  AppStrings.topup: 'RECARGAR',
  AppStrings.gotopayment: 'Ir al pago',
  AppStrings.paymentfailed: 'Pago fallido',
  AppStrings.pleaseselectanamount: 'Por favor, seleccione un monto',
  AppStrings.showlatesttransactionscap: 'MOSTRAR ÚLTIMAS TRANSACCIONES',
  AppStrings.transactionscap: 'TRANSACCIONES',
  AppStrings.transactionnote:
  'Rastree y vea transacciones de entrada o salida y prepárese para sus próximos logros.',
  AppStrings.searchtransactionsby: 'Buscar transacciones por',
  AppStrings.searchtransactions: 'Buscar transacciones',
  AppStrings.alltransactions: 'Todas las transacciones',
  AppStrings.transactionname: 'Nombre de la transacción',
  AppStrings.transactionid: 'ID de la transacción',
  AppStrings.querytobeexecuted: 'Consulta a ejecutar',
  AppStrings.settingssaved: 'Configuración guardada',
  AppStrings.general: 'General',
  AppStrings.failedtosavesettigns: 'Error al guardar la configuración',
  AppStrings.emailpreferences: 'Preferencias de correo electrónico',
  AppStrings.emailnotificationscap: 'NOTIFICACIONES POR CORREO ELECTRÓNICO',
  AppStrings.savepreferences: 'Guardar preferencias',
  AppStrings.sendmeemailsaboutmyentireactivity:
  'Enviarme correos electrónicos sobre toda mi actividad',
  AppStrings.selectpushandemailnotificationyouliketorecieve:
  'Seleccione las notificaciones push y por correo electrónico que le gustaría recibir',
  AppStrings.onlysendmerequiredemails: 'Enviarme solo los correos electrónicos requeridos',
  AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges:
  'Nota: Siempre recibirá notificaciones de cambios individuales de cuenta.',
  AppStrings.enablefollowmecap: 'HABILITAR SEGUIRME',
  AppStrings.sendmenotificationscap: 'ENVIARME NOTIFICACIONES',
  AppStrings.enablethisifyouwantpeopletofollowyou:
  'Habilite esto si desea que las personas le sigan',
  AppStrings.sendmenotificationaboutmyfriendlike:
  'Enviarme notificación sobre el gusto de mi amigo',
  AppStrings.shareormessageme: 'Compartir o enviarme un mensaje.',
  AppStrings.hideyourprofilefromsearchengine:
  'Ocultar su perfil de los motores de búsqueda',
  AppStrings.searchprivacycap: 'PRIVACIDAD DE BÚSQUEDA',
  AppStrings.hidegendercap: 'OCULTAR GÉNERO',
  AppStrings.hideagecap: 'OCULTAR EDAD',
  AppStrings.hidelocationcap: 'OCULTAR UBICACIÓN',
  AppStrings.profilecap: 'PERFIL',
  AppStrings.editprofilecap: 'EDITAR PERFIL',
  AppStrings.changecap: 'CAMBIAR',
  AppStrings.displaynamecap: 'NOMBRE A MOSTRAR',
  AppStrings.peopleongenixwillgettoknowbybelowinfo:
  'Las personas en Genix lo conocerán por la siguiente información',
  AppStrings.showingname: 'Mostrando nombre',
  AppStrings.usernamecap: 'NOMBRE DE USUARIO',
  AppStrings.emailaddressecap: 'DIRECCIÓN DE CORREO ELECTRÓNICO',
  AppStrings.youremailaddress: 'Su dirección de correo electrónico',
  AppStrings.gendercap: 'GÉNERO',
  AppStrings.male: 'Masculino',
  AppStrings.female: 'Femenino',
  AppStrings.bio: 'Biografía',
  AppStrings.tellusmoreaboutyou: 'Cuéntenos más sobre usted',
  AppStrings.socialprofilelinks: 'Enlaces de perfil social',
  AppStrings.citycap: 'CIUDAD',
  AppStrings.countrycap: 'PAÍS',
  AppStrings.yourcity: 'Su ciudad',
  AppStrings.paypalemailaddress: 'Dirección de correo electrónico de PayPal',
  AppStrings.enteryourpaypalemailaddress: 'Ingrese su dirección de correo electrónico de PayPal',
  AppStrings.security: 'Seguridad',
  AppStrings.accountpasswordcap: 'CONTRASEÑA DE LA CUENTA',
  AppStrings.changeyourpasswordandalterothersecurityoptions:
  'Cambie su contraseña y modifique otras opciones de seguridad',
  AppStrings.currentpasswordcap: 'CONTRASEÑA ACTUAL',
  AppStrings.currentpassword: 'Contraseña actual',
  AppStrings.newpassword: 'Nueva contraseña',
  AppStrings.confirmpassword: 'Confirmar contraseña',
  AppStrings.repeatnewpassword: 'Repetir nueva contraseña',
  AppStrings.mineightcharacters: 'MÍNIMO 8 CARACTERES',
  AppStrings.twofactorauthenticationcap: 'AUTENTICACIÓN DE DOS FACTORES',
  AppStrings.twofactorauthentication: 'Autenticación de dos factores',
  AppStrings.enable: 'Habilitar',
  AppStrings.enablecap: 'HABILITAR',
  AppStrings.accountclosure: 'Cierre de cuenta',
  AppStrings.deleteyouraccountanddata: 'Eliminar su cuenta y datos',
  AppStrings.areyousureyouwanttodeleteyouraccount:
  '¿Está seguro de que desea eliminar su cuenta?',
  AppStrings.deletecap: 'ELIMINAR',
  AppStrings.settingscap: 'CONFIGURACIÓN',
  AppStrings.emails: 'Correos electrónicos',
  AppStrings.billings: 'Facturación',
  AppStrings.profile: 'Perfil',
  AppStrings.currentbalancecap: 'SALDO ACTUAL',
  AppStrings.revenuefromshortscap: 'INGRESOS POR CORTOS',
  AppStrings.withdrawcap: 'RETIRAR',
  AppStrings.coins: 'Monedas',
  AppStrings.customamount: 'Monto personalizado',
    AppStrings.selectlanguage: "Seleccionar idioma",
    AppStrings.languagecap: "IDIOMA",
    AppStrings.changinglanguage: "Cambiando idioma...",
  };
}
