import 'all_app_strings.dart';

mixin AppLocaleFrench {
  static const Map<String, dynamic> french ={
    AppStrings.somethingwentwrong: 'Quelque chose a mal tourné',
    AppStrings.nothingtodisplay: 'Rien à afficher...',
    AppStrings.chat: 'Chat',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Vidéo',
    AppStrings.active: 'Actif',
    AppStrings.inactive: 'Inactif',
    AppStrings.edit: 'Éditer',
    AppStrings.yes: 'Oui',
    AppStrings.no: 'Non',
    AppStrings.settings: 'Paramètres',
    AppStrings.getcoins: 'Obtenir des pièces',
    AppStrings.promotions: 'Promotions',
    AppStrings.errorloadingvideo: "Erreur de chargement de la vidéo",
    AppStrings.errorloadingpage: "Erreur de chargement de la page",
    AppStrings.comments: 'Commentaires',
    AppStrings.replyto: 'Répondre à',
    AppStrings.replytonamecomment: 'Répondre au commentaire de Nom',
    AppStrings.replies: 'Réponses',
    AppStrings.post: 'Publier',
    AppStrings.nocommentsyet: 'Aucun commentaire pour le moment',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Tapez un message',
    AppStrings.nomessagesfound: "Aucun message trouvé",
    AppStrings.failedtoloadthechatrroms: "Échec du chargement des salles de chat",
    AppStrings.typeheretheusername: 'Tapez ici le nom d\'utilisateur',
    AppStrings.lockscreen: 'Écran de verrouillage',
    AppStrings.logout: 'Se déconnecter',
    AppStrings.darkmode: 'Mode sombre',
    AppStrings.followers: 'Abonnés',
    AppStrings.followings: 'Abonnements',
    AppStrings.recentfollowings: 'Abonnements récents',
    AppStrings.recentfollowers: 'Abonnés récents',
    AppStrings.groupnmae: 'Nom du groupe',
    AppStrings.required: ' requis',
    AppStrings.website: 'Site Web',
    AppStrings.category: 'Catégorie',
    AppStrings.validwebsiteurl: 'URL de site Web valide',
    AppStrings.aboutthisgroup: 'À propos de ce groupe',
    AppStrings.areyousureyouwanttologout: 'Êtes-vous sûr de vouloir vous déconnecter ?',
    AppStrings.writemoreaboutthisgroup: 'Écrivez plus sur ce groupe',
    AppStrings.sociallinks: 'Liens sociaux',
    AppStrings.facebookprofilelink: 'Lien du profil Facebook',
    AppStrings.xprofilelink: 'Lien du profil X',
    AppStrings.instagramprofilelink: 'Lien du profil Instagram',
    AppStrings.tiktokprofilelink: 'Lien du profil TikTok',
    AppStrings.pinterestprofilelink: 'Lien du profil Pinterest',
    AppStrings.steamprofilelink: 'Lien du profil Steam',
    AppStrings.linkedInprofilelink: 'Lien du profil LinkedIn',
    AppStrings.selectprivacy: 'Sélectionner la confidentialité',
    AppStrings.groupwillbepublic: 'Le groupe sera public',
    AppStrings.submitgroup: 'Soumettre le groupe',
    AppStrings.allrequiredfieldsshouldbefilled: 'Tous les champs obligatoires doivent être remplis',
    AppStrings.errorloadinggroupdata: 'Erreur de chargement des données du groupe',
    AppStrings.artAndCulture: 'Art et Culture',
    AppStrings.scienceAndTechnology: 'Science et Technologie',
    AppStrings.sport: 'Sport',
    AppStrings.music: 'Musique',
    AppStrings.gastronomy: 'Gastronomie',
    AppStrings.fashionAndStyle: 'Mode et Style',
    AppStrings.travelAndPlaces: 'Voyages et Lieux',
    AppStrings.education: 'Éducation',
    AppStrings.career: 'Carrière',
    AppStrings.businessAndFinance: 'Affaires et Finance',
    AppStrings.entertainment: 'Divertissement',
    AppStrings.environmentAndEcology: 'Environnement et Écologie',
    AppStrings.agricultureAndHorticulture: 'Agriculture et Horticulture',
    AppStrings.languagesAndCommunication: 'Langues et Communication',
    AppStrings.technologyAndDigital: 'Technologie et Numérique',
    AppStrings.architectureAndDesign: 'Architecture et Design',
    AppStrings.mediaAndJournalism: 'Médias et Journalisme',
    AppStrings.buyAndSell: 'Acheter et Vendre',
    AppStrings.selectacategory: 'Sélectionner une catégorie',
    AppStrings.groupprofilepicture: 'Photo de profil du groupe',
    AppStrings.selectaimage: 'Sélectionner une image',
    AppStrings.groupcoverpicture: 'Photo de couverture du groupe',
    AppStrings.createpost: 'Créer une publication',
    AppStrings.writesomething: 'Écrire quelque chose...',
    AppStrings.createapoll: 'Créer un sondage',
    AppStrings.pollquestion: 'Question du sondage',
    AppStrings.polloption: 'Option du sondage',
    AppStrings.addoption: '+ Ajouter une option',
    AppStrings.checkin: 'Check-in',
    AppStrings.current: 'Actuel',
    AppStrings.customLocation: 'Emplacement personnalisé',
    AppStrings.onlyforclosefriend: 'Uniquement pour les amis proches ?',
    AppStrings.newsfeed: 'Fil d\'actualités',
    AppStrings.story: 'Histoire',
    AppStrings.contentmustbefilled: 'Le contenu doit être rempli',
    AppStrings.polloptions: 'Options du sondage :',
    AppStrings.pollmusthaveaquestionandatleasttwooptions: 'Le sondage doit avoir une question et au moins deux options',
    AppStrings.firstofallselectanimage: 'Tout d\'abord, sélectionnez une image',
    AppStrings.browseondevice: 'Parcourir sur l\'appareil',
    AppStrings.joinedgroup: 'Groupe rejoint',
    AppStrings.leavegroupsuccessfully: 'Quitter le groupe avec succès',
    AppStrings.joingroup: 'Rejoindre le groupe',
    AppStrings.groupjoinedsuccessfully: 'Groupe rejoint avec succès',
    AppStrings.postdeletedsuccessfully: 'Publication supprimée avec succès',
    AppStrings.deleteallusersposts: 'Supprimer toutes les publications de l\'utilisateur',
    AppStrings.deletealluserscomments: 'Supprimer tous les commentaires de l\'utilisateur',
    AppStrings.deleteposts: 'Supprimer les publications',
    AppStrings.deletecomments: 'Supprimer les commentaires',
    AppStrings.removethisuser: 'Supprimer cet utilisateur',
    AppStrings.delete: 'Supprimer',
    AppStrings.editmemberdetails: 'MODIFIER LES DÉTAILS DU MEMBRE',
    AppStrings.availableroles: 'Rôles disponibles',
    AppStrings.groupmanger: 'Gestionnaire de groupe',
    AppStrings.pagemanger: 'Gestionnaire de page',
    AppStrings.pagemangerdescription: 'modifier les détails de la page, modifier les membres de la page, modifier les publications de la page, modifier les commentaires des publications de la page',
    AppStrings.groupmangerdescription: 'modifier les détails du groupe, modifier les membres du groupe, modifier les publications du groupe, modifier les commentaires des publications du groupe',
    AppStrings.groupmoderatord: 'Modérateur de groupe',
    AppStrings.pagemoderatord: 'Modérateur de page',
    AppStrings.pagemoderatorddescription: 'modifier les publications de la page, modifier les commentaires des publications de la page',
    AppStrings.groupmoderatorddescription: 'modifier les publications du groupe, modifier les commentaires des publications du groupe',
    AppStrings.none: 'Aucun',
    AppStrings.availablepermission: 'Permission disponible',
    AppStrings.altergroupdetails: 'Modifier les détails du groupe',
    AppStrings.altergroupmembers: 'Modifier les membres du groupe',
    AppStrings.altergroupposts: 'Modifier les publications du groupe',
    AppStrings.altergrouppostscomments: 'Modifier les commentaires des publications du groupe',
    AppStrings.alterpagedetails: 'Modifier les détails de la page',
    AppStrings.alterpagemembers: 'Modifier les membres de la page',
    AppStrings.alterpageposts: 'Modifier les publications de la page',
    AppStrings.alterpagepostscomments: 'Modifier les commentaires des publications de la page',
    AppStrings.updateuser: 'Mettre à jour l\'utilisateur',
    AppStrings.editgroup: 'Modifier le groupe',
    AppStrings.editpage: 'Modifier la page',
    AppStrings.deletegroup: 'Supprimer le groupe',
    AppStrings.deletepage: 'Supprimer la page',
    AppStrings.groupmembers: 'Membres du groupe',
    AppStrings.pagemembers: 'Membres de la page',
    AppStrings.report: 'Signaler',
    AppStrings.areyousureyouwanttodeletegroup: 'Êtes-vous sûr de vouloir supprimer le groupe ?',
    AppStrings.areyousureyouwanttodeletepage: 'Êtes-vous sûr de vouloir supprimer la page ?',
    AppStrings.youremailisnotverified: 'Votre email n\'est pas vérifié',
    AppStrings.unauthenticated: 'Non authentifié',
    AppStrings.failedtodeletepost: 'Échec de la suppression de la publication',
    AppStrings.addingapost: 'ajout d\'une publication',
    AppStrings.golive: 'Passer en direct',
    AppStrings.location: 'Emplacement',
    AppStrings.timestamp: 'Horodatage',
    AppStrings.votes: 'votes',
    AppStrings.short: 'court',
    AppStrings.reply: 'répondre',
    AppStrings.shortvideopost: 'publication de vidéo courte',
    AppStrings.shares: 'Partages',
    AppStrings.share: 'Partager',
    AppStrings.comment: 'commentaire',
    AppStrings.hidecomments: 'Masquer les commentaires',
    AppStrings.viewmorecomments: 'Voir plus de commentaires',
    AppStrings.replytonamepost: 'répondre à la publication de nom',
    AppStrings.name: 'nom',
    AppStrings.onedayago: 'Il y a 1 jour',
    AppStrings.promote: 'Promouvoir',
    AppStrings.increaseyourpopularity: 'Augmentez votre popularité',
    AppStrings.allocatecoinsforpromotions: 'Attribuer des pièces pour les promotions',
    AppStrings.like: 'J\'aime',
    AppStrings.viewpost: 'Voir la publication',
    AppStrings.replypost: 'Répondre à la publication',
    AppStrings.submitanewpost: 'SOUMETTRE UNE NOUVELLE PUBLICATION',
    AppStrings.submitanewpostdescription:
    'Alimentez ce rapport avec un contenu complet. Veuillez inclure autant de détails que possible, sous toutes les formes possibles pour obtenir une résolution appropriée.',
    AppStrings.content: 'contenu',
    AppStrings.reportnow: 'signaler maintenant',
    AppStrings.failedtoremovelock: 'Échec de la suppression du verrou',
    AppStrings.password: 'Mot de passe',
    AppStrings.unlock: 'Déverrouiller',
    AppStrings.thesecredentialsdonotmatch: 'Ces identifiants ne correspondent pas',
    AppStrings.login: 'Se connecter',
    AppStrings.signin: 'Se connecter',
    AppStrings.signup: 'S\'inscrire',
    AppStrings.email: 'E-mail',
    AppStrings.rememberme: 'Se souvenir de moi',
    AppStrings.forgetpassword: 'Mot de passe oublié',
    AppStrings.notifications: 'Notifications',
    AppStrings.pages: 'Pages',
    AppStrings.createnewpage: 'CRÉER UNE NOUVELLE PAGE',
    AppStrings.members: 'Membres',
    AppStrings.creators: 'Créateurs',
    AppStrings.page: 'Page',
    AppStrings.submitpage: 'Soumettre la page',
    AppStrings.aboutthispage: 'À propos de cette page',
    AppStrings.writemoreaboutthispage: 'Écrire plus sur cette page',
    AppStrings.pagename: 'Nom de la page',
    AppStrings.private: 'privé',
    AppStrings.public: 'public',
    AppStrings.invite: 'INVITER',
    AppStrings.about: 'À PROPOS',
    AppStrings.photos: 'PHOTOS',
    AppStrings.events: 'ÉVÉNEMENTS',
    AppStrings.pagewillbepublic: 'La page sera publique',
    AppStrings.pagefollowed: 'Page suivie',

  AppStrings.joinpage: 'Rejoindre la page',
  AppStrings.pageleavedsuccessfully: 'Page quittée avec succès',
  AppStrings.pagejoinedsuccessfully: 'Page rejointe avec succès',
  AppStrings.userspage: 'Page de l\'utilisateur',
  AppStrings.paymentcompletedsuccessfully: 'Paiement effectué avec succès !',
  AppStrings.stripepayment: 'Paiement Stripe',
  AppStrings.myphotos: 'Mes photos',
  AppStrings.recentphotos: 'Photos récentes',
  AppStrings.recentposts: 'Publications récentes',
  AppStrings.savedshorts: 'Shorts enregistrés',
  AppStrings.seeall: 'Voir tout',
  AppStrings.groups: 'Groupes',
  AppStrings.errorloadingaccountdetails: 'Erreur lors du chargement des détails du compte',
  AppStrings.errorloadingprofile: 'Erreur lors du chargement du profil',
  AppStrings.timeline: 'Chronologie',
  AppStrings.saved: 'Enregistré',
  AppStrings.restricted: 'Restreint',
  AppStrings.blocked: 'Bloqué',
  AppStrings.register: 'S\'inscrire',
  AppStrings.date: 'Date',
  AppStrings.find: 'Trouver',
  AppStrings.users: 'Utilisateurs',
  AppStrings.status: 'Statut',
  AppStrings.open: 'Ouvert',
  AppStrings.closed: 'Fermé',
  AppStrings.title: 'Titre',
  AppStrings.edittickets: 'Modifier les tickets',
  AppStrings.postareply: 'Publier une réponse',
  AppStrings.createdat: 'Créé le',
  AppStrings.lastreplyby: 'Dernière réponse de',
  AppStrings.repliesintotal: 'Réponses au total',
  AppStrings.supportTickets: 'Tickets de support',
  AppStrings.ticketsummary: 'Résumé du ticket',
  AppStrings.availableactions: 'Actions disponibles',
  AppStrings.retypepassword: 'Retaper le mot de passe',
  AppStrings.yourname: 'Votre nom',
  AppStrings.selectyourcountry: 'Sélectionnez votre pays',
  AppStrings.username: 'Nom d\'utilisateur',
  AppStrings.searchby: 'Rechercher par',
  AppStrings.searchresults: 'Résultats de recherche',
  AppStrings.searchpeoplegrouporpage: 'Rechercher des personnes, des groupes ou des pages',
  AppStrings.followaddedsuccessfully: 'Suivi ajouté avec succès',
  AppStrings.followremovedsuccessfully: 'Suivi supprimé avec succès',
  AppStrings.pleaseverifyyuouremail: 'Veuillez vérifier votre e-mail',
  AppStrings.verifyyouraccount: 'Vérifiez votre compte',
  AppStrings.sendverificationlink: 'Envoyer le lien de vérification',
  AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
  'Si vous avez déjà reçu un lien ou si vous avez un compte, connectez-vous maintenant',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere:
    'Si vous n\'avez pas reçu de lien, veuillez cliquer ici',
    AppStrings.videos: 'Vidéos',
    AppStrings.videoselected: 'Vidéo sélectionnée !',
    AppStrings.donate: 'Faire un don',
    AppStrings.recentvideos: 'Vidéos récentes',
    AppStrings.firstofallselectvideo: 'Tout d\'abord, sélectionnez une vidéo',
    AppStrings.shortdescriprtiontags: 'Description courte,  #tags',
    AppStrings.postshort: '↑ Publier le short',
    AppStrings.pleaseselectavideofile: 'Veuillez sélectionner un fichier vidéo',
    AppStrings.donations: 'Dons',
    AppStrings.topdonations: 'Dons principaux',
    AppStrings.helptheshortcreator: 'Aidez le créateur de short.',
    AppStrings.sharethispostto: 'Partager ce post à',
    AppStrings.copylink: 'Copier le lien',
    AppStrings.selectanuser: 'SÉLECTIONNER UN UTILISATEUR',
    AppStrings.user111: 'utilisateur111',
    AppStrings.sharenow: 'Partager maintenant',
    AppStrings.reopenticket: 'Rouvrir le ticket',
    AppStrings.closeticket: 'Fermer le ticket',
    AppStrings.supportsticket: 'Tickets de support',
    AppStrings.totalticket: 'TICKETS AU TOTAL',
    AppStrings.solvedticket: 'TICKETS RÉSOLUS',
    AppStrings.openedissues: 'PROBLÈMES OUVERTS',
    AppStrings.sendemail: 'Envoyer un e-mail',
    AppStrings.support: 'Support',
    AppStrings.openticket: 'Ouvrir un ticket',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
    'Si vous préférez nous contacter par e-mail, veuillez envoyer votre demande à :',
    AppStrings.ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
    'Si vous lisez cette ligne, il semble que votre problème soit vraiment sérieux... veuillez nous en dire plus, nous vous aiderons sûrement.',
    AppStrings.createanewsupportticket: 'Créer un nouveau ticket de support',
    AppStrings.newintervention: 'Nouvelle intervention',
    AppStrings.interventiontitle: 'Titre de l\'intervention',
    AppStrings.typeherethetitle: 'Tapez ici le titre',
    AppStrings.submitticket: 'Soumettre le ticket',
    AppStrings.submitcomment: 'Soumettre le commentaire',
    AppStrings.contentmustnotbelessthentencharacters:
    'Le contenu ne doit pas être inférieur à dix caractères',
    AppStrings.completeinterventiontitle:
    'Alimentez cette intervention avec un contenu détaillé. Veuillez inclure autant de détails que possible, sous toutes les formes possibles pour obtenir une résolution correcte.',
    AppStrings.updatecomment: 'Mettre à jour le commentaire',
    AppStrings.updatethereply: 'Mettre à jour la réponse',
    AppStrings.commentcontent:
    'Alimentez cette réponse avec un contenu détaillé. Veuillez inclure autant de détails que possible, sous toutes les formes possibles pour obtenir une résolution correcte.',
    AppStrings.thereisopeninterventionticketcloseitfirst:
    'Il y a un ticket d\'intervention ouvert, veuillez le fermer d\'abord.',
    AppStrings.addanewcomment: 'Ajouter un nouveau commentaire',
    AppStrings.billingarea: 'Zone de facturation',
    AppStrings.billingareacap: 'ZONE DE FACTURATION',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount:
    'Parcourez les transactions et ajoutez plus de pièces à votre compte',
    AppStrings.topup: 'RECHARGER',
    AppStrings.gotopayment: 'Aller au paiement',
    AppStrings.paymentfailed: 'Échec du paiement',
    AppStrings.pleaseselectanamount: 'Veuillez sélectionner un montant',
    AppStrings.showlatesttransactionscap: 'AFFICHER LES DERNIÈRES TRANSACTIONS',
    AppStrings.transactionscap: 'TRANSACTIONS',
    AppStrings.transactionnote:
    'Suivez et consultez les transactions entrantes ou sortantes et préparez-vous pour vos prochaines réussites.',
    AppStrings.searchtransactionsby: 'Rechercher des transactions par',
    AppStrings.searchtransactions: 'Rechercher des transactions',
    AppStrings.alltransactions: 'Toutes les transactions',
    AppStrings.transactionname: 'Nom de la transaction',
    AppStrings.transactionid: 'ID de la transaction',
    AppStrings.querytobeexecuted: 'Requête à exécuter',
    AppStrings.settingssaved: 'Paramètres enregistrés',
    AppStrings.general: 'Général',
    AppStrings.failedtosavesettigns: 'Échec de l\'enregistrement des paramètres',
    AppStrings.emailpreferences: 'Préférences de messagerie',
    AppStrings.emailnotificationscap: 'NOTIFICATIONS PAR E-MAIL',
    AppStrings.savepreferences: 'Enregistrer les préférences',
    AppStrings.sendmeemailsaboutmyentireactivity:
    'Envoyez-moi des e-mails sur toute mon activité',
    AppStrings.selectpushandemailnotificationyouliketorecieve:
    'Sélectionnez les notifications push et par e-mail que vous souhaitez recevoir',
    AppStrings.onlysendmerequiredemails: 'Envoyez-moi uniquement les e-mails nécessaires',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges:
    'Remarque : Vous recevrez toujours des notifications pour les modifications individuelles de votre compte.',
    AppStrings.enablefollowmecap: 'ACTIVER LE SUIVI',
    AppStrings.sendmenotificationscap: 'ENVOYER DES NOTIFICATIONS',
    AppStrings.enablethisifyouwantpeopletofollowyou:
    'Activez cela si vous voulez que les gens vous suivent',
    AppStrings.sendmenotificationaboutmyfriendlike: 'Envoyez-moi une notification à propos du like de mon ami',
    AppStrings.shareormessageme: 'Partager ou m\'envoyer un message.',
    AppStrings.hideyourprofilefromsearchengine:
    'Masquer votre profil des moteurs de recherche',
    AppStrings.searchprivacycap: 'CONFIDENTIALITÉ DE LA RECHERCHE',
    AppStrings.hidegendercap: 'MASQUER LE SEXE',
    AppStrings.hideagecap: 'MASQUER L\'ÂGE',
    AppStrings.hidelocationcap: 'MASQUER L\'EMPLACEMENT',
    AppStrings.profilecap: 'PROFIL',
    AppStrings.editprofilecap: 'MODIFIER LE PROFIL',
    AppStrings.changecap: 'MODIFIER',
    AppStrings.displaynamecap: 'NOM D\'AFFICHAGE',
    AppStrings.peopleongenixwillgettoknowbybelowinfo:
    'Les gens sur Genix apprendront par les informations ci-dessous',
    AppStrings.showingname: 'Nom affiché',
    AppStrings.usernamecap: 'NOM D\'UTILISATEUR',
    AppStrings.emailaddressecap: 'ADRESSE E-MAIL',
    AppStrings.youremailaddress: 'Votre adresse e-mail',
    AppStrings.gendercap: 'SEXE',
    AppStrings.male: 'Homme',
    AppStrings.female: 'Femme',
    AppStrings.bio: 'Bio',
    AppStrings.tellusmoreaboutyou: 'Dites-nous en plus sur vous',
    AppStrings.socialprofilelinks: 'Liens de profil social',
    AppStrings.citycap: 'VILLE',
    AppStrings.countrycap: 'PAYS',
    AppStrings.yourcity: 'Votre ville',
    AppStrings.paypalemailaddress: 'Adresse e-mail PAY-PAL',
    AppStrings.enteryourpaypalemailaddress: 'Entrez votre adresse e-mail PAY-PAL',
    AppStrings.security: 'Sécurité',
    AppStrings.accountpasswordcap: 'MOT DE PASSE DU COMPTE',
    AppStrings.changeyourpasswordandalterothersecurityoptions:
    'Changez votre mot de passe et modifiez d\'autres options de sécurité',
    AppStrings.currentpasswordcap: 'MOT DE PASSE ACTUEL',
    AppStrings.currentpassword: 'Mot de passe actuel',
    AppStrings.newpassword: 'Nouveau mot de passe',
    AppStrings.confirmpassword: 'Confirmer le mot de passe',
    AppStrings.repeatnewpassword: 'Répétez le nouveau mot de passe',
    AppStrings.mineightcharacters: 'MIN 8 CARACTÈRES',
    AppStrings.twofactorauthenticationcap: 'AUTHENTIFICATION À DEUX FACTEURS',
    AppStrings.twofactorauthentication: 'Authentification à deux facteurs',
    AppStrings.enable: 'Activer',
    AppStrings.enablecap: 'ACTIVER',
    AppStrings.accountclosure: 'Fermeture de compte',
    AppStrings.deleteyouraccountanddata: 'Supprimer votre compte et vos données',
    AppStrings.areyousureyouwanttodeleteyouraccount:
    'Êtes-vous sûr de vouloir supprimer votre compte ?',
    AppStrings.deletecap: 'SUPPRIMER',
    AppStrings.settingscap: 'PARAMÈTRES',
    AppStrings.emails: 'E-mails',
    AppStrings.billings: 'Facturation',
    AppStrings.profile: 'Profil',
    AppStrings.selectlanguage: "Sélectionner une langue",
    AppStrings.languagecap: "LANGUE",
    AppStrings.changinglanguage: "Changement de langue...",
    AppStrings.currentbalancecap: 'SOLDE ACTUEL',
    AppStrings.revenuefromshortscap: 'REVENUS DES SHORTS',
    AppStrings.withdrawcap: 'RETRAIT',
    AppStrings.coins: 'Pièces',
    AppStrings.customamount: 'Montant personnalisé',

  };}