import 'all_app_strings.dart';

mixin AppLocaleGerman {
  static const Map<String, dynamic> german = {
    AppStrings.somethingwentwrong: 'Etwas ist schiefgelaufen',
    AppStrings.nothingtodisplay: "Nichts anzuzeigen...",
    AppStrings.chat: 'Chat',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Video',
    AppStrings.active: 'Aktiv',
    AppStrings.inactive: 'Inaktiv',
    AppStrings.selectlanguage: "Sprache auswählen",
    AppStrings.languagecap: "SPRACHE",
    AppStrings.changinglanguage: "Sprache ändern...",
    AppStrings.edit: 'Bearbeiten',
    AppStrings.yes: 'Ja',
    AppStrings.no: 'Nein',
    AppStrings.settings: 'Einstellungen',
    AppStrings.getcoins: 'Münzen erhalten',
    AppStrings.promotions: 'Aktionen',
    AppStrings.errorloadingvideo: "Fehler beim Laden des Videos",
    AppStrings.errorloadingpage: "Fehler beim Laden der Seite",
    AppStrings.comments: 'Kommentare',
    AppStrings.replyto: 'Antworten an',
    AppStrings.replytonamecomment: 'Antworten auf den Kommentar von Name',
    AppStrings.replies: 'Antworten',
    AppStrings.post: 'Beitrag',
    AppStrings.nocommentsyet: 'Noch keine Kommentare',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Nachricht eingeben',
    AppStrings.nomessagesfound: "Keine Nachrichten gefunden",
    AppStrings.failedtoloadthechatrroms: "Fehler beim Laden der Chaträume",
    AppStrings.typeheretheusername: 'Geben Sie hier den Benutzernamen ein',
    AppStrings.lockscreen: 'Sperrbildschirm',
    AppStrings.logout: 'Abmelden',
    AppStrings.darkmode: 'Dunkelmodus',
    AppStrings.followers: 'Follower',
    AppStrings.followings: 'Abonnements',
    AppStrings.recentfollowings: 'Letzte Abonnements',
    AppStrings.recentfollowers: 'Letzte Follower',
    AppStrings.groupnmae: 'Gruppenname',
    AppStrings.required: 'Erforderlich',
    AppStrings.website: 'Webseite',
    AppStrings.category: 'Kategorie',
    AppStrings.validwebsiteurl: 'Gültige Website-URL',
    AppStrings.aboutthisgroup: 'Über diese Gruppe',
    AppStrings.areyousureyouwanttologout:
        'Sind Sie sicher, dass Sie sich abmelden möchten?',
    AppStrings.writemoreaboutthisgroup: 'Schreiben Sie mehr über diese Gruppe',
    AppStrings.sociallinks: 'Soziale Links',
    AppStrings.facebookprofilelink: 'Facebook-Profillink',
    AppStrings.xprofilelink: 'X-Profillink',
    AppStrings.instagramprofilelink: 'Instagram-Profillink',
    AppStrings.tiktokprofilelink: 'TikTok-Profillink',
    AppStrings.pinterestprofilelink: 'Pinterest-Profillink',
    AppStrings.steamprofilelink: 'Steam-Profillink',
    AppStrings.linkedInprofilelink: 'LinkedIn-Profillink',
    AppStrings.selectprivacy: 'Datenschutz auswählen',
    AppStrings.groupwillbepublic: 'Gruppe wird öffentlich sein',
    AppStrings.submitgroup: 'Gruppe einreichen',
    AppStrings.allrequiredfieldsshouldbefilled:
        'Alle erforderlichen Felder müssen ausgefüllt werden',
    AppStrings.errorloadinggroupdata: 'Fehler beim Laden der Gruppendaten',
    AppStrings.artAndCulture: 'Kunst und Kultur',
    AppStrings.scienceAndTechnology: 'Wissenschaft und Technologie',
    AppStrings.sport: 'Sport',
    AppStrings.music: 'Musik',
    AppStrings.gastronomy: 'Gastronomie',
    AppStrings.fashionAndStyle: 'Mode und Stil',
    AppStrings.travelAndPlaces: 'Reisen und Orte',
    AppStrings.education: 'Bildung',
    AppStrings.career: 'Karriere',
    AppStrings.businessAndFinance: 'Geschäft und Finanzen',
    AppStrings.entertainment: 'Unterhaltung',
    AppStrings.environmentAndEcology: 'Umwelt und Ökologie',
    AppStrings.agricultureAndHorticulture: 'Landwirtschaft und Gartenbau',
    AppStrings.languagesAndCommunication: 'Sprachen und Kommunikation',
    AppStrings.technologyAndDigital: 'Technologie und Digital',
    AppStrings.architectureAndDesign: 'Architektur und Design',
    AppStrings.mediaAndJournalism: 'Medien und Journalismus',
    AppStrings.buyAndSell: 'Kaufen & Verkaufen',
    AppStrings.selectacategory: 'Wählen Sie eine Kategorie aus',
    AppStrings.groupprofilepicture: 'Gruppenprofilbild',
    AppStrings.selectaimage: 'Wählen Sie ein Bild aus',
    AppStrings.groupcoverpicture: 'Gruppen-Coverbild',
    AppStrings.createpost: 'Beitrag erstellen',
    AppStrings.writesomething: 'Schreiben Sie etwas...',
    AppStrings.createapoll: 'Umfrage erstellen',
    AppStrings.pollquestion: 'Umfragefrage',
    AppStrings.polloption: 'Umfrageoption',
    AppStrings.addoption: '+ Option hinzufügen',
    AppStrings.checkin: 'Einchecken',
    AppStrings.current: 'Aktuell',
    AppStrings.customLocation: 'Benutzerdefinierter Standort',
    AppStrings.onlyforclosefriend: 'Nur für enge Freunde?',
    AppStrings.newsfeed: 'Neuigkeiten',
    AppStrings.story: 'Story',
    AppStrings.contentmustbefilled: 'Inhalt muss ausgefüllt sein',
    AppStrings.polloptions: 'Umfrageoptionen:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions:
        'Eine Umfrage muss eine Frage und mindestens zwei Optionen haben',
    AppStrings.firstofallselectanimage: 'Wählen Sie zuerst ein Bild aus',
    AppStrings.browseondevice: 'Auf Gerät durchsuchen',
    AppStrings.joinedgroup: 'Gruppe beigetreten',
    AppStrings.leavegroupsuccessfully: 'Gruppe erfolgreich verlassen',
    AppStrings.joingroup: 'Gruppe beitreten',
    AppStrings.groupjoinedsuccessfully: 'Gruppe erfolgreich beigetreten',
    AppStrings.postdeletedsuccessfully: 'Beitrag erfolgreich gelöscht',
    AppStrings.deleteallusersposts: 'Alle Beiträge des Benutzers löschen',
    AppStrings.deletealluserscomments: 'Alle Kommentare des Benutzers löschen',
    AppStrings.deleteposts: 'Beiträge löschen',
    AppStrings.deletecomments: 'Kommentare löschen',
    AppStrings.removethisuser: 'Diesen Benutzer entfernen',
    AppStrings.delete: 'Löschen',
    AppStrings.editmemberdetails: 'MITGLIEDERDETAILS BEARBEITEN',
    AppStrings.availableroles: 'Verfügbare Rollen',
    AppStrings.groupmanger: 'Gruppenmanager',
    AppStrings.pagemanger: 'Seitenmanager',
    AppStrings.pagemangerdescription:
        'Seiteninformationen ändern, Seitenmitglieder ändern, Seitenbeiträge ändern, Kommentare zu Seitenbeiträgen ändern',
    AppStrings.groupmangerdescription:
        'Gruppendetails ändern, Gruppenmitglieder ändern, Gruppenbeiträge ändern, Kommentare zu Gruppenbeiträgen ändern',
    AppStrings.groupmoderatord: 'Gruppenmoderator',
    AppStrings.pagemoderatord: 'Seitenmoderator',
    AppStrings.pagemoderatorddescription:
        'Seitenbeiträge ändern, Kommentare zu Seitenbeiträgen ändern',
    AppStrings.groupmoderatorddescription:
        'Gruppenbeiträge ändern, Kommentare zu Gruppenbeiträgen ändern',
    AppStrings.none: 'Keine',
    AppStrings.availablepermission: 'Verfügbare Berechtigungen',
    AppStrings.altergroupdetails: 'Gruppendetails ändern',
    AppStrings.altergroupmembers: 'Gruppenmitglieder ändern',
    AppStrings.altergroupposts: 'Gruppenbeiträge ändern',
    AppStrings.altergrouppostscomments: 'Kommentare zu Gruppenbeiträgen ändern',
    AppStrings.alterpagedetails: 'Seiteninformationen ändern',
    AppStrings.alterpagemembers: 'Seitenmitglieder ändern',
    AppStrings.alterpageposts: 'Seitenbeiträge ändern',
    AppStrings.alterpagepostscomments: 'Kommentare zu Seitenbeiträgen ändern',
    AppStrings.updateuser: 'Benutzer aktualisieren',
    AppStrings.editgroup: 'Gruppe bearbeiten',
    AppStrings.editpage: 'Seite bearbeiten',
    AppStrings.deletegroup: 'Gruppe löschen',
    AppStrings.deletepage: 'Seite löschen',
    AppStrings.groupmembers: 'Gruppenmitglieder',
    AppStrings.pagemembers: 'Seitenmitglieder',
    AppStrings.report: 'Melden',
    AppStrings.areyousureyouwanttodeletegroup:
        'Sind Sie sicher, dass Sie die Gruppe löschen möchten?',
    AppStrings.areyousureyouwanttodeletepage:
        'Sind Sie sicher, dass Sie die Seite löschen möchten?',
    AppStrings.youremailisnotverified: 'Ihre E-Mail ist nicht verifiziert',
    AppStrings.unauthenticated: 'Nicht authentifiziert',
    AppStrings.failedtodeletepost: 'Beitrag konnte nicht gelöscht werden',
    AppStrings.addingapost: 'Einen Beitrag hinzufügen',
    AppStrings.golive: 'Live gehen',
    AppStrings.location: 'Standort',
    AppStrings.timestamp: 'Zeitstempel',
    AppStrings.votes: 'Stimmen',
    AppStrings.short: 'Kurz',
    AppStrings.reply: 'Antworten',
    AppStrings.shortvideopost: 'Kurzvideobeitrag',
    AppStrings.shares: 'Teilen',
    AppStrings.share: 'Teilen',
    AppStrings.comment: 'Kommentar',
    AppStrings.hidecomments: 'Kommentare ausblenden',
    AppStrings.viewmorecomments: 'Mehr Kommentare anzeigen',
    AppStrings.replytonamepost: 'Antwort auf den Beitrag von {name}',
    AppStrings.name: 'Name',
    AppStrings.onedayago: 'Vor 1 Tag',
    AppStrings.promote: 'Bewerben',
    AppStrings.increaseyourpopularity: 'Steigern Sie Ihre Beliebtheit',
    AppStrings.allocatecoinsforpromotions: 'Münzen für Werbung zuweisen',
    AppStrings.like: 'Gefällt mir',
    AppStrings.viewpost: 'Beitrag ansehen',
    AppStrings.replypost: 'Beitrag beantworten',
    AppStrings.submitanewpost: 'NEUEN BEITRAG EINREICHEN',
    AppStrings.submitanewpostdescription:
        'Füllen Sie diesen Bericht mit umfassendem Inhalt aus. Bitte geben Sie so viele Details wie möglich an, in allen möglichen Formen, um eine ordnungsgemäße Lösung zu erhalten.',
    AppStrings.content: 'Inhalt',
    AppStrings.reportnow: 'Jetzt melden',
    AppStrings.failedtoremovelock: 'Schloss konnte nicht entfernt werden',
    AppStrings.password: 'Passwort',
    AppStrings.unlock: 'Entsperren',
    AppStrings.thesecredentialsdonotmatch:
        'Diese Anmeldeinformationen stimmen nicht überein',
    AppStrings.login: 'Anmelden',
    AppStrings.signin: 'Einloggen',
    AppStrings.signup: 'Registrieren',
    AppStrings.email: 'E-Mail',
    AppStrings.rememberme: 'Angemeldet bleiben',
    AppStrings.forgetpassword: 'Passwort vergessen',
    AppStrings.notifications: 'Benachrichtigungen',
    AppStrings.pages: 'Seiten',
    AppStrings.createnewpage: 'NEUE SEITE ERSTELLEN',
    AppStrings.members: 'Mitglieder',
    AppStrings.creators: 'Ersteller',
    AppStrings.page: 'Seite',
    AppStrings.submitpage: 'Seite einreichen',
    AppStrings.aboutthispage: 'Über diese Seite',
    AppStrings.writemoreaboutthispage: 'Mehr über diese Seite schreiben',
    AppStrings.pagename: 'Seitenname',
    AppStrings.private: 'Privat',
    AppStrings.public: 'Öffentlich',
    AppStrings.invite: 'EINLADEN',
    AppStrings.about: 'ÜBER',
    AppStrings.photos: 'FOTOS',
    AppStrings.events: 'EREIGNISSE',
    AppStrings.pagewillbepublic: 'Seite wird öffentlich sein',
    AppStrings.pagefollowed: 'Seite abonniert',
    AppStrings.joinpage: 'Seite beitreten',
    AppStrings.pageleavedsuccessfully: 'Seite erfolgreich verlassen',
    AppStrings.pagejoinedsuccessfully: 'Seite erfolgreich beigetreten',
    AppStrings.userspage: 'Benutzerseite',
    AppStrings.paymentcompletedsuccessfully:
        'Zahlung erfolgreich abgeschlossen!',
    AppStrings.stripepayment: 'Stripe-Zahlung',
    AppStrings.myphotos: 'Meine Fotos',
    AppStrings.recentphotos: 'Neueste Fotos',
    AppStrings.recentposts: 'Neueste Beiträge',
    AppStrings.savedshorts: 'Gespeicherte Shorts',
    AppStrings.seeall: 'Alle anzeigen',
    AppStrings.groups: 'Gruppen',
    AppStrings.errorloadingaccountdetails: 'Fehler beim Laden der Kontodaten',
    AppStrings.errorloadingprofile: 'Fehler beim Laden des Profils',
    AppStrings.timeline: 'Zeitachse',
    AppStrings.saved: 'Gespeichert',
    AppStrings.restricted: 'Eingeschränkt',
    AppStrings.blocked: 'Blockiert',
    AppStrings.register: 'Registrieren',
    AppStrings.date: 'Datum',
    AppStrings.find: 'Finden',
    AppStrings.users: 'Benutzer',
    AppStrings.status: 'Status',
    AppStrings.open: 'Offen',
    AppStrings.closed: 'Geschlossen',
    AppStrings.title: 'Titel',
    AppStrings.edittickets: 'Tickets bearbeiten',
    AppStrings.postareply: 'Eine Antwort posten',
    AppStrings.createdat: 'Erstellt am',
    AppStrings.lastreplyby: 'Letzte Antwort von',
    AppStrings.repliesintotal: 'Gesamtanzahl der Antworten',
    AppStrings.supportTickets: 'Support-Tickets',
    AppStrings.ticketsummary: 'Ticket-Zusammenfassung',
    AppStrings.availableactions: 'Verfügbare Aktionen',
    AppStrings.retypepassword: 'Passwort erneut eingeben',
    AppStrings.yourname: 'Ihr Name',
    AppStrings.selectyourcountry: 'Wählen Sie Ihr Land',
    AppStrings.username: 'Benutzername',
    AppStrings.searchby: 'Suchen nach',
    AppStrings.searchresults: 'Suchergebnisse',
    AppStrings.searchpeoplegrouporpage: 'Personen, Gruppen oder Seiten suchen',
    AppStrings.followaddedsuccessfully: 'Erfolgreich hinzugefügt',
    AppStrings.followremovedsuccessfully: 'Erfolgreich entfernt',
    AppStrings.pleaseverifyyuouremail: 'Bitte überprüfen Sie Ihre E-Mail',
    AppStrings.verifyyouraccount: 'Konto verifizieren',
    AppStrings.sendverificationlink: 'Verifizierungslink senden',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
        'Wenn Sie bereits einen Link erhalten haben oder ein Konto besitzen, melden Sie sich jetzt an',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere:
        'Wenn Sie keinen Link erhalten haben, klicken Sie bitte hier',
    AppStrings.videos: 'Videos',
    AppStrings.videoselected: 'Video ausgewählt!',
    AppStrings.donate: 'Spenden',
    AppStrings.recentvideos: 'Neueste Videos',
    AppStrings.firstofallselectvideo: 'Wählen Sie zuerst ein Video aus',
    AppStrings.shortdescriprtiontags: 'Kurze Beschreibung, #Tags',
    AppStrings.postshort: '↑ Kurzes Video posten',
    AppStrings.pleaseselectavideofile: 'Bitte wählen Sie eine Videodatei aus',
    AppStrings.donations: 'Spenden',
    AppStrings.topdonations: 'Top-Spenden',
    AppStrings.helptheshortcreator:
        'Helfen Sie dem Ersteller des kurzen Videos.',
    AppStrings.sharethispostto: 'Teilen Sie diesen Beitrag mit',
    AppStrings.copylink: 'Link kopieren',
    AppStrings.selectanuser: 'BENUTZER AUSWÄHLEN',
    AppStrings.user111: 'Benutzer111',
    AppStrings.sharenow: 'Jetzt teilen',
    AppStrings.reopenticket: 'Ticket wieder öffnen',
    AppStrings.closeticket: 'Ticket schließen',
    AppStrings.supportsticket: 'Support-Ticket',
    AppStrings.totalticket: 'GESAMTE TICKETS',
    AppStrings.solvedticket: 'GELÖSTE TICKETS',
    AppStrings.openedissues: 'OFFENE PROBLEME',
    AppStrings.sendemail: 'E-Mail senden',
    AppStrings.support: 'Support',
    AppStrings.openticket: 'Ticket öffnen',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
        'Wenn Sie uns lieber per E-Mail kontaktieren möchten, senden Sie uns Ihre Anfrage an:',
    AppStrings
            .ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
        'Wenn Sie diese Zeile lesen, scheint Ihr Problem wirklich ernst zu sein. Bitte lassen Sie uns mehr darüber wissen, wir helfen Ihnen auf jeden Fall.',
    AppStrings.createanewsupportticket:
        'Erstellen Sie ein neues Support-Ticket',
    AppStrings.newintervention: 'Neue Intervention',
    AppStrings.interventiontitle: 'Interventionstitel',
    AppStrings.typeherethetitle: 'Geben Sie hier den Titel ein',
    AppStrings.submitticket: 'Ticket absenden',
    AppStrings.submitcomment: 'Kommentar absenden',
    AppStrings.contentmustnotbelessthentencharacters:
        'Der Inhalt darf nicht weniger als 10 Zeichen enthalten',
    AppStrings.completeinterventiontitle:
        'Fügen Sie dieser Intervention umfassende Inhalte hinzu. Bitte geben Sie so viele Details wie möglich in allen möglichen Formen an, um eine ordnungsgemäße Lösung zu erhalten.',
    AppStrings.updatecomment: 'Kommentar aktualisieren',
    AppStrings.updatethereply: 'Antwort aktualisieren',
    AppStrings.commentcontent:
        'Fügen Sie dieser Antwort umfassende Inhalte hinzu. Bitte geben Sie so viele Details wie möglich in allen möglichen Formen an, um eine ordnungsgemäße Lösung zu erhalten.',
    AppStrings.thereisopeninterventionticketcloseitfirst:
        'Es gibt ein offenes Interventions-Ticket, bitte schließen Sie es zuerst.',
    AppStrings.addanewcomment: 'Einen neuen Kommentar hinzufügen',
    AppStrings.billingarea: 'Abrechnungsbereich',
    AppStrings.billingareacap: 'ABRECHNUNGSBEREICH',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount:
        'Durchsuchen Sie Transaktionen und fügen Sie Ihrem Konto weitere Coins hinzu',
    AppStrings.topup: 'AUFLADEN',
    AppStrings.gotopayment: 'Zur Zahlung gehen',
    AppStrings.paymentfailed: 'Zahlung fehlgeschlagen',
    AppStrings.pleaseselectanamount: 'Bitte wählen Sie einen Betrag aus',
    AppStrings.showlatesttransactionscap: 'NEUESTE TRANSAKTIONEN ANZEIGEN',
    AppStrings.transactionscap: 'TRANSAKTIONEN',
    AppStrings.transactionnote:
        'Verfolgen und sehen Sie eingehende oder ausgehende Transaktionen und bereiten Sie sich auf Ihre nächsten Erfolge vor.',
    AppStrings.searchtransactionsby: 'Transaktionen suchen nach',
    AppStrings.searchtransactions: 'Transaktionen suchen',
    AppStrings.alltransactions: 'Alle Transaktionen',
    AppStrings.transactionname: 'Transaktionsname',
    AppStrings.transactionid: 'Transaktions-ID',
    AppStrings.querytobeexecuted: 'Abfrage ausführen',
    AppStrings.settingssaved: 'Einstellungen gespeichert',
    AppStrings.general: 'Allgemein',
    AppStrings.failedtosavesettigns:
        'Einstellungen konnten nicht gespeichert werden',
    AppStrings.emailpreferences: 'E-Mail-Einstellungen',
    AppStrings.emailnotificationscap: 'E-MAIL-BENACHRICHTIGUNGEN',
    AppStrings.savepreferences: 'Einstellungen speichern',
    AppStrings.sendmeemailsaboutmyentireactivity:
        'Senden Sie mir E-Mails über meine gesamte Aktivität',
    AppStrings.selectpushandemailnotificationyouliketorecieve:
        'Wählen Sie Push- und E-Mail-Benachrichtigungen aus, die Sie erhalten möchten',
    AppStrings.onlysendmerequiredemails:
        'Senden Sie mir nur erforderliche E-Mails',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges:
        'Hinweis: Sie erhalten immer Benachrichtigungen über Änderungen an Ihrem Konto.',
    AppStrings.enablefollowmecap: 'FOLGEN ERLAUBEN',
    AppStrings.sendmenotificationscap: 'BENACHRICHTIGUNGEN SENDEN',
    AppStrings.enablethisifyouwantpeopletofollowyou:
        'Aktivieren Sie dies, wenn Sie möchten, dass Personen Ihnen folgen',
    AppStrings.sendmenotificationaboutmyfriendlike:
        'Senden Sie mir Benachrichtigungen über die Likes meiner Freunde',
    AppStrings.shareormessageme: 'Teilen oder mir schreiben.',
    AppStrings.hideyourprofilefromsearchengine:
        'Verbergen Sie Ihr Profil vor Suchmaschinen',
    AppStrings.searchprivacycap: 'SUCHPRIVATSPHÄRE',
    AppStrings.hidegendercap: 'GESCHLECHT VERBERGEN',
    AppStrings.hideagecap: 'ALTER VERBERGEN',
    AppStrings.hidelocationcap: 'STANDORT VERBERGEN',
    AppStrings.profilecap: 'PROFIL',
    AppStrings.editprofilecap: 'PROFIL BEARBEITEN',
    AppStrings.changecap: 'ÄNDERN',
    AppStrings.displaynamecap: 'ANZEIGENAME',
    AppStrings.peopleongenixwillgettoknowbybelowinfo:
        'Personen auf Genix werden Sie durch die unten stehenden Informationen kennenlernen',
    AppStrings.showingname: 'Angezeigter Name',
    AppStrings.usernamecap: 'BENUTZERNAME',
    AppStrings.emailaddressecap: 'E-MAIL-ADRESSE',
    AppStrings.youremailaddress: 'Ihre E-Mail-Adresse',
    AppStrings.gendercap: 'GESCHLECHT',
    AppStrings.male: 'Männlich',
    AppStrings.female: 'Weiblich',
    AppStrings.bio: 'Biografie',
    AppStrings.tellusmoreaboutyou: 'Erzählen Sie uns mehr über sich',
    AppStrings.socialprofilelinks: 'Links zu sozialen Profilen',
    AppStrings.citycap: 'STADT',
    AppStrings.countrycap: 'LAND',
    AppStrings.yourcity: 'Ihre Stadt',
    AppStrings.paypalemailaddress: 'PayPal-E-Mail-Adresse',
    AppStrings.enteryourpaypalemailaddress:
        'Geben Sie Ihre PayPal-E-Mail-Adresse ein',
    AppStrings.security: 'Sicherheit',
    AppStrings.accountpasswordcap: 'KONTOPASSWORT',
    AppStrings.changeyourpasswordandalterothersecurityoptions:
        'Ändern Sie Ihr Passwort und passen Sie andere Sicherheitsoptionen an',
    AppStrings.currentpasswordcap: 'AKTUELLES PASSWORT',
    AppStrings.currentpassword: 'Aktuelles Passwort',
    AppStrings.newpassword: 'Neues Passwort',
    AppStrings.confirmpassword: 'Passwort bestätigen',
    AppStrings.repeatnewpassword: 'Neues Passwort wiederholen',
    AppStrings.mineightcharacters: 'MINDESTENS 8 ZEICHEN',
    AppStrings.twofactorauthenticationcap: 'ZWEI-FAKTOR-AUTHENTIFIZIERUNG',
    AppStrings.twofactorauthentication: 'Zwei-Faktor-Authentifizierung',
    AppStrings.enable: 'Aktivieren',
    AppStrings.enablecap: 'AKTIVIEREN',
    AppStrings.accountclosure: 'Kontoschließung',
    AppStrings.deleteyouraccountanddata: 'Löschen Sie Ihr Konto und Ihre Daten',
    AppStrings.areyousureyouwanttodeleteyouraccount:
        'Sind Sie sicher, dass Sie Ihr Konto löschen möchten?',
    AppStrings.deletecap: 'LÖSCHEN',
    AppStrings.settingscap: 'EINSTELLUNGEN',
    AppStrings.emails: 'E-Mails',
    AppStrings.billings: 'Abrechnungen',
    AppStrings.profile: 'Profil',
    AppStrings.currentbalancecap: 'AKTUELLES GUTHABEN',
    AppStrings.revenuefromshortscap: 'EINKOMMEN AUS SHORTS',
    AppStrings.withdrawcap: 'AUSZAHLEN',
    AppStrings.coins: 'Münzen',
    AppStrings.customamount: 'Benutzerdefinierter Betrag',
  };
}
