import 'all_app_strings.dart';

mixin AppLocaleItalian {
  static const Map<String, dynamic> italian ={
    AppStrings.somethingwentwrong: "Qualcosa è andato storto",
    AppStrings.nothingtodisplay: "Niente da visualizzare...",
    AppStrings.chat: "Chat",
    AppStrings.spam: "Spam",
    AppStrings.video: "Video",
    AppStrings.active: "Attivo",
    AppStrings.inactive: "Inattivo",
    AppStrings.edit: "Modifica",
    AppStrings.yes: "Sì",
    AppStrings.no: "No",
    AppStrings.settings: "Impostazioni",
    AppStrings.getcoins: "Ottieni monete",
    AppStrings.promotions: "Promozioni",
    AppStrings.errorloadingvideo: "Errore nel caricare il video",
    AppStrings.errorloadingpage: "Errore nel caricare la pagina",
    AppStrings.comments: "Commenti",
    AppStrings.replyto: "Rispondi a",
    AppStrings.replytonamecomment: "Rispondi al commento di Nome",
    AppStrings.replies: "Risposte",
    AppStrings.post: "Posta",
    AppStrings.nocommentsyet: "Ancora nessun commento",
    AppStrings.hommeeeeee: "hommeeeeee",
    AppStrings.typeamessage: "Scrivi un messaggio",
    AppStrings.nomessagesfound: "Nessun messaggio trovato",
    AppStrings.failedtoloadthechatrroms: "Impossibile caricare le stanze di chat",
    AppStrings.typeheretheusername: "Scrivi qui il nome utente",
    AppStrings.lockscreen: "Schermata di blocco",
    AppStrings.logout: "Disconnettersi",
    AppStrings.darkmode: "Modalità scura",
    AppStrings.followers: "Follower",
    AppStrings.followings: "Persone seguite",
    AppStrings.recentfollowings: "Persone seguite recentemente",
    AppStrings.recentfollowers: "Follower recenti",
    AppStrings.groupnmae: "Nome del gruppo",
    AppStrings.required: " richiesto",
    AppStrings.website: "Sito web",
    AppStrings.category: "Categoria",
    AppStrings.validwebsiteurl: "URL del sito web valido",
    AppStrings.aboutthisgroup: "Informazioni su questo gruppo",
    AppStrings.areyousureyouwanttologout: "Sei sicuro di voler uscire?",
    AppStrings.writemoreaboutthisgroup: "Scrivi di più su questo gruppo",
    AppStrings.sociallinks: "Link ai social",
    AppStrings.facebookprofilelink: "Link profilo Facebook",
    AppStrings.xprofilelink: "Link profilo X",
    AppStrings.instagramprofilelink: "Link profilo Instagram",
    AppStrings.tiktokprofilelink: "Link profilo TikTok",
    AppStrings.pinterestprofilelink: "Link profilo Pinterest",
    AppStrings.steamprofilelink: "Link profilo Steam",
    AppStrings.linkedInprofilelink: "Link profilo LinkedIn",
    AppStrings.selectprivacy: "Seleziona la privacy",
    AppStrings.groupwillbepublic: "Il gruppo sarà pubblico",
    AppStrings.submitgroup: "Invia gruppo",
    AppStrings.allrequiredfieldsshouldbefilled: "Tutti i campi obbligatori devono essere compilati",
    AppStrings.errorloadinggroupdata: "Errore nel caricare i dati del gruppo",
    AppStrings.artAndCulture: "Arte e cultura",
    AppStrings.scienceAndTechnology: "Scienza e tecnologia",
    AppStrings.sport: "Sport",
    AppStrings.music: "Musica",
    AppStrings.gastronomy: "Gastronomia",
    AppStrings.fashionAndStyle: "Moda e stile",
    AppStrings.travelAndPlaces: "Viaggi e luoghi",
    AppStrings.education: "Educazione",
    AppStrings.career: "Carriera",
    AppStrings.businessAndFinance: "Affari e finanza",
    AppStrings.entertainment: "Intrattenimento",
    AppStrings.environmentAndEcology: "Ambiente ed ecologia",
    AppStrings.agricultureAndHorticulture: "Agricoltura e orticoltura",
    AppStrings.languagesAndCommunication: "Lingue e comunicazione",
    AppStrings.technologyAndDigital: "Tecnologia e digitale",
    AppStrings.architectureAndDesign: "Architettura e design",
    AppStrings.mediaAndJournalism: "Media e giornalismo",
    AppStrings.buyAndSell: "Compra & Vendi",
    AppStrings.selectacategory: "Seleziona una categoria",
    AppStrings.groupprofilepicture: "Immagine del profilo del gruppo",
    AppStrings.selectaimage: "Seleziona un'immagine",
    AppStrings.groupcoverpicture: "Immagine di copertura del gruppo",
    AppStrings.createpost: "Crea post",
    AppStrings.writesomething: "Scrivi qualcosa...",
    AppStrings.createapoll: "Crea un sondaggio",
    AppStrings.pollquestion: "Domanda del sondaggio",
    AppStrings.polloption: "Opzione del sondaggio",
    AppStrings.addoption: "+ Aggiungi opzione",
    AppStrings.checkin: "Registrati",
    AppStrings.current: "Attuale",
    AppStrings.customLocation: "Posizione personalizzata",
    AppStrings.onlyforclosefriend: "Solo per amici stretti?",
    AppStrings.newsfeed: "Notizie",
    AppStrings.story: "Storia",
    AppStrings.contentmustbefilled: "Il contenuto deve essere compilato",
    AppStrings.polloptions: "Opzioni del sondaggio:",
    AppStrings.pollmusthaveaquestionandatleasttwooptions: "Il sondaggio deve avere una domanda e almeno due opzioni",
    AppStrings.firstofallselectanimage: "Prima di tutto, seleziona un'immagine",
    AppStrings.browseondevice: "Sfoglia sul dispositivo",
    AppStrings.joinedgroup: "Gruppo unito",
    AppStrings.leavegroupsuccessfully: "Gruppo lasciato con successo",
    AppStrings.joingroup: "Unisciti al gruppo",
    AppStrings.groupjoinedsuccessfully: "Gruppo unito con successo",
    AppStrings.postdeletedsuccessfully: "Post eliminato con successo",
    AppStrings.deleteallusersposts: "Elimina tutti i post dell'utente",
    AppStrings.deletealluserscomments: "Elimina tutti i commenti dell'utente",
    AppStrings.deleteposts: "Elimina i post",
    AppStrings.deletecomments: "Elimina i commenti",
    AppStrings.removethisuser: "Rimuovi questo utente",
    AppStrings.delete: "Elimina",
    AppStrings.editmemberdetails: "MODIFICA DETTAGLI MEMBRO",
    AppStrings.availableroles: "Ruoli disponibili",
    AppStrings.groupmanger: "Gestore del gruppo",
    AppStrings.pagemanger: "Gestore della pagina",
    AppStrings.pagemangerdescription: "modifica i dettagli della pagina, modifica i membri della pagina, modifica i post della pagina, modifica i commenti dei post della pagina",
    AppStrings.groupmangerdescription: "modifica i dettagli del gruppo, modifica i membri del gruppo, modifica i post del gruppo, modifica i commenti dei post del gruppo",
    AppStrings.groupmoderatord: "Moderatore del gruppo",
    AppStrings.pagemoderatord: "Moderatore della pagina",
    AppStrings.pagemoderatorddescription: "modifica i post della pagina, modifica i commenti dei post della pagina",
    AppStrings.groupmoderatorddescription: "modifica i post del gruppo, modifica i commenti dei post del gruppo",
    AppStrings.none: "Nessuno",
    AppStrings.availablepermission: "Autorizzazioni disponibili",
    AppStrings.altergroupdetails: "Modifica i dettagli del gruppo",
    AppStrings.altergroupmembers: "Modifica i membri del gruppo",
    AppStrings.altergroupposts: "Modifica i post del gruppo",
    AppStrings.altergrouppostscomments: "Modifica i commenti dei post del gruppo",
    AppStrings.alterpagedetails: "Modifica i dettagli della pagina",
    AppStrings.alterpagemembers: "Modifica i membri della pagina",
    AppStrings.alterpageposts: "Modifica i post della pagina",
    AppStrings.alterpagepostscomments: "Modifica i commenti dei post della pagina",
    AppStrings.updateuser: "Aggiorna utente",
    AppStrings.editgroup: "Modifica gruppo",
    AppStrings.editpage: "Modifica pagina",
    AppStrings.deletegroup: "Elimina gruppo",
    AppStrings.deletepage: "Elimina pagina",
    AppStrings.groupmembers: "Membri del gruppo",
    AppStrings.pagemembers: "Membri della pagina",
    AppStrings.report: "Segnala",
    AppStrings.areyousureyouwanttodeletegroup: "Sei sicuro di voler eliminare il gruppo?",
    AppStrings.areyousureyouwanttodeletepage: "Sei sicuro di voler eliminare la pagina?",
    AppStrings.youremailisnotverified: "La tua email non è verificata",
    AppStrings.unauthenticated: "Non autenticato",
    AppStrings.failedtodeletepost: "Impossibile eliminare il post",
    AppStrings.addingapost: "aggiungendo un post",
    AppStrings.golive: "Vai in diretta",
    AppStrings.location: "Posizione",
    AppStrings.timestamp: "Timestamp",
    AppStrings.votes: "voti",
    AppStrings.short: 'Breve',
    AppStrings.reply: 'Rispondi',
    AppStrings.shortvideopost: 'Post video breve',
    AppStrings.shares: 'Condivisioni',
    AppStrings.share: 'Condividi',
    AppStrings.comment: 'Commento',
    AppStrings.hidecomments: 'Nascondi commenti',
    AppStrings.viewmorecomments: 'Vedi altri commenti',
    AppStrings.replytonamepost: 'Rispondi al post di nome',
    AppStrings.name: 'Nome',
    AppStrings.onedayago: '1 giorno fa',
    AppStrings.promote: 'Promuovi',
    AppStrings.increaseyourpopularity: 'Aumenta la tua popolarità',
    AppStrings.allocatecoinsforpromotions: 'Assegna monete per promozioni',
    AppStrings.like: 'Mi piace',
    AppStrings.viewpost: 'Vedi post',
    AppStrings.replypost: 'Rispondi al post',
    AppStrings.submitanewpost: 'INVIATE UN NUOVO POST',
    AppStrings.submitanewpostdescription: 'Fornisci un contenuto completo per questo report. Includi quanti più dettagli possibili in tutte le forme possibili per ottenere una risoluzione adeguata.',
    AppStrings.content: 'Contenuto',
    AppStrings.reportnow: 'Segnala ora',
    AppStrings.failedtoremovelock: 'Impossibile rimuovere il blocco',
    AppStrings.password: 'Password',
    AppStrings.unlock: 'Sblocca',
    AppStrings.thesecredentialsdonotmatch: 'Queste credenziali non corrispondono',
    AppStrings.login: 'Accedi',
    AppStrings.signin: 'Accedi',
    AppStrings.signup: 'Iscriviti',
    AppStrings.email: 'E-Mail',
    AppStrings.rememberme: 'Ricordami',
    AppStrings.forgetpassword: 'Hai dimenticato la password?',
    AppStrings.notifications: 'Notifiche',
    AppStrings.pages: 'Pagine',
    AppStrings.createnewpage: 'CREA UNA NUOVA PAGINA',
    AppStrings.members: 'Membri',
    AppStrings.creators: 'Creatori',
    AppStrings.page: 'Pagina',
    AppStrings.submitpage: 'Invia pagina',
    AppStrings.aboutthispage: 'Informazioni su questa pagina',
    AppStrings.writemoreaboutthispage: 'Scrivi di più su questa pagina',
    AppStrings.pagename: 'Nome della pagina',
    AppStrings.private: 'Privato',
    AppStrings.public: 'Pubblico',
    AppStrings.invite: 'INVITA',
    AppStrings.about: 'CHI SIAMO',
    AppStrings.photos: 'FOTO',
    AppStrings.events: 'EVENTI',
    AppStrings.pagewillbepublic: 'La pagina sarà pubblica',
    AppStrings.pagefollowed: 'Pagina seguita',
    AppStrings.joinpage: 'Unisciti alla pagina',
    AppStrings.pageleavedsuccessfully: 'Pagina abbandonata con successo',
    AppStrings.pagejoinedsuccessfully: 'Pagina unita con successo',
    AppStrings.userspage: 'Pagina dell\'utente',
    AppStrings.paymentcompletedsuccessfully: 'Pagamento completato con successo!',
    AppStrings.stripepayment: 'Pagamento con Stripe',
    AppStrings.myphotos: 'Le mie foto',
    AppStrings.recentphotos: 'Foto recenti',
    AppStrings.recentposts: 'Post recenti',
    AppStrings.savedshorts: 'Shorts salvati',
    AppStrings.seeall: 'Vedi tutto',
    AppStrings.groups: 'Gruppi',
    AppStrings.errorloadingaccountdetails: 'Errore nel caricare i dettagli dell\'account',
    AppStrings.errorloadingprofile: 'Errore nel caricare il profilo',
    AppStrings.timeline: 'Cronologia',
    AppStrings.saved: 'Salvato',
    AppStrings.restricted: 'Limitato',
    AppStrings.blocked: 'Bloccato',
    AppStrings.register: 'Registrati',
    AppStrings.date: 'Data',
    AppStrings.find: 'Trova',
    AppStrings.users: 'Utenti',
    AppStrings.status: 'Stato',
    AppStrings.open: 'Aperto',
    AppStrings.closed: 'Chiuso',
    AppStrings.title: 'Titolo',
    AppStrings.edittickets: 'Modifica biglietti',
    AppStrings.postareply: 'Posta una risposta',
    AppStrings.createdat: 'Creato il',
    AppStrings.lastreplyby: 'Ultima risposta da',
    AppStrings.repliesintotal: 'Risposte in totale',
    AppStrings.supportTickets: 'Biglietti di supporto',
    AppStrings.ticketsummary: 'Riepilogo del biglietto',
    AppStrings.availableactions: 'Azioni disponibili',
    AppStrings.retypepassword: 'Ridigita la password',
    AppStrings.yourname: 'Il tuo nome',
    AppStrings.selectyourcountry: 'Seleziona il tuo paese',
    AppStrings.username: 'Nome utente',
    AppStrings.searchby: 'Cerca per',
    AppStrings.searchresults: 'Risultati di ricerca',
    AppStrings.searchpeoplegrouporpage: 'Cerca persone, gruppi o pagine',
    AppStrings.followaddedsuccessfully: 'Segui aggiunto con successo',
    AppStrings.followremovedsuccessfully: 'Segui rimosso con successo',
    AppStrings.pleaseverifyyuouremail: 'Per favore verifica la tua email',
    AppStrings.verifyyouraccount: 'Verifica il tuo account',
    AppStrings.sendverificationlink: 'Invia link di verifica',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
    'Se hai già ricevuto un link o se hai un account, accedi ora',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere: 'Se non hai ricevuto un link, fai clic qui',
    AppStrings.videos: 'Video',
    AppStrings.videoselected: 'Video selezionato!',
    AppStrings.donate: 'Dona',
    AppStrings.recentvideos: 'Video recenti',
    AppStrings.firstofallselectvideo: 'Prima di tutto, seleziona un video',
    AppStrings.shortdescriprtiontags: 'Breve descrizione,  #tags',
    AppStrings.postshort: '↑ Pubblica breve',
    AppStrings.pleaseselectavideofile: 'Per favore seleziona un file video',
    AppStrings.donations: 'Donazioni',
    AppStrings.topdonations: 'Le migliori donazioni',
    AppStrings.helptheshortcreator: 'Aiuta il creatore del breve video.',
    AppStrings.sharethispostto: 'Condividi questo post su',
    AppStrings.copylink: 'Copia link',
    AppStrings.selectanuser: 'SELEZIONA UN UTENTE',
    AppStrings.user111: 'utente111',
    AppStrings.sharenow: 'Condividi ora',
    AppStrings.reopenticket: 'Riapri il ticket',
    AppStrings.closeticket: 'Chiudi ticket',
    AppStrings.supportsticket: 'Supporto ticket',
    AppStrings.totalticket: 'TICKET TOTALE',
    AppStrings.solvedticket: 'TICKET RISOLTI',
    AppStrings.openedissues: 'ISSUE APERTI',
    AppStrings.sendemail: 'Invia email',
    AppStrings.support: 'Supporto',
    AppStrings.openticket: 'Apri ticket',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
    'Se preferisci contattarci via email, invia la tua richiesta a:',
    AppStrings.ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
    'Se hai letto questa linea, sembra che il tuo problema sia davvero serio... facci sapere di più e ti aiuteremo sicuramente.',
    AppStrings.createanewsupportticket: 'Crea un nuovo ticket di supporto',
    AppStrings.newintervention: 'Nuova intervento',
    AppStrings.interventiontitle: 'Titolo intervento',
    AppStrings.typeherethetitle: 'Scrivi qui il titolo',
    AppStrings.submitticket: 'Invia ticket',
    AppStrings.submitcomment: 'Invia commento',
    AppStrings.contentmustnotbelessthentencharacters: 'Il contenuto non deve essere inferiore a 10 caratteri',
    AppStrings.completeinterventiontitle:
    'Fornisci questo intervento con un contenuto completo. Per favore includi il maggior numero di dettagli possibile, in tutte le forme possibili per ottenere una risoluzione adeguata.',
    AppStrings.updatecomment: 'Aggiorna commento',
    AppStrings.updatethereply: 'Aggiorna la risposta',
    AppStrings.commentcontent:
    'Fornisci questa risposta con un contenuto completo. Per favore includi il maggior numero di dettagli possibile, in tutte le forme possibili per ottenere una risoluzione adeguata.',
    AppStrings.thereisopeninterventionticketcloseitfirst: 'C\'è un ticket di intervento aperto, chiudilo prima.',
    AppStrings.addanewcomment: 'Aggiungi un nuovo commento',
    AppStrings.billingarea: 'Area di fatturazione',
    AppStrings.billingareacap: 'AREA DI FATTURAZIONE',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount:
    'Esplora le transazioni e aggiungi più monete al tuo account',
    AppStrings.topup: 'RICARICA',
    AppStrings.gotopayment: 'Vai al pagamento',
    AppStrings.paymentfailed: 'Pagamento fallito',
    AppStrings.pleaseselectanamount: 'Seleziona un importo',
    AppStrings.showlatesttransactionscap: 'MOSTRA TRANSAZIONI RECENTI',
    AppStrings.transactionscap: 'TRANSAZIONI',
    AppStrings.transactionnote:
    'Traccia e visualizza le transazioni in entrata o in uscita e preparati per i tuoi prossimi traguardi.',
    AppStrings.searchtransactionsby: 'Cerca transazioni per',
    AppStrings.searchtransactions: 'Cerca transazioni',
    AppStrings.alltransactions: 'Tutte le transazioni',
    AppStrings.transactionname: 'Nome transazione',
    AppStrings.transactionid: 'ID transazione',
    AppStrings.querytobeexecuted: 'Query da eseguire',
    AppStrings.settingssaved: 'Impostazioni salvate',
    AppStrings.general: 'Generale',
    AppStrings.failedtosavesettigns: 'Impossibile salvare le impostazioni',
    AppStrings.emailpreferences: 'Preferenze email',
    AppStrings.emailnotificationscap: 'NOTIFICHE EMAIL',
    AppStrings.savepreferences: 'Salva preferenze',
    AppStrings.sendmeemailsaboutmyentireactivity:
    'Mandami email su tutta la mia attività',
    AppStrings.selectpushandemailnotificationyouliketorecieve:
    'Seleziona le notifiche push e email che desideri ricevere',
    AppStrings.onlysendmerequiredemails: 'Mandami solo email necessarie',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges:
    'Nota: Riceverai sempre notifiche per le modifiche individuali dell\'account.',
    AppStrings.enablefollowmecap: 'ABILITA SEGUIMI',
    AppStrings.sendmenotificationscap: 'INVIA NOTIFICHE',
    AppStrings.enablethisifyouwantpeopletofollowyou:
    'Abilita questa opzione se vuoi che le persone ti seguano',
    AppStrings.sendmenotificationaboutmyfriendlike:
    'Mandami una notifica quando il mio amico mette mi piace',
    AppStrings.shareormessageme: 'Condividi o messaggiami',
    AppStrings.hideyourprofilefromsearchengine: 'Nascondi il tuo profilo dai motori di ricerca',
    AppStrings.searchprivacycap: 'PRIVACY DI RICERCA',
    AppStrings.hidegendercap: 'NASCONDI IL GENERE',
    AppStrings.hideagecap: 'NASCONDI L\'ETÀ',
    AppStrings.hidelocationcap: 'NASCONDI LA LOCALITÀ',
    AppStrings.profilecap: 'PROFILO',
    AppStrings.editprofilecap: 'MODIFICA PROFILO',
    AppStrings.changecap: 'CAMBIA',
    AppStrings.displaynamecap: 'NOME VISIBILE',
    AppStrings.peopleongenixwillgettoknowbybelowinfo:
    'Le persone su Genix conosceranno le informazioni qui sotto',
    AppStrings.showingname: 'Mostrando nome',
    AppStrings.usernamecap: 'NOME UTENTE',
    AppStrings.emailaddressecap: 'INDIRIZZO EMAIL',
    AppStrings.youremailaddress: 'Il tuo indirizzo email',
    AppStrings.gendercap: 'GENERE',
    AppStrings.male: 'Maschio',
    AppStrings.female: 'Femmina',
    AppStrings.bio: 'Bio',
    AppStrings.tellusmoreaboutyou: 'Raccontaci di più su di te',
    AppStrings.socialprofilelinks: 'Link ai profili social',
    AppStrings.citycap: 'CITTÀ',
    AppStrings.countrycap: 'PAESE',
    AppStrings.yourcity: 'La tua città',
    AppStrings.paypalemailaddress: 'Indirizzo email PAY-PAL',
    AppStrings.enteryourpaypalemailaddress: 'Inserisci il tuo indirizzo email PAY-PAL',
    AppStrings.security: 'Sicurezza',
    AppStrings.accountpasswordcap: 'PASSWORD ACCOUNT',
    AppStrings.changeyourpasswordandalterothersecurityoptions:
    'Cambia la tua password e modifica altre opzioni di sicurezza',
    AppStrings.currentpasswordcap: 'PASSWORD ATTUALE',
    AppStrings.currentpassword: 'Password attuale',
    AppStrings.newpassword: 'Nuova password',
    AppStrings.confirmpassword: 'Conferma password',
    AppStrings.repeatnewpassword: 'Ripeti la nuova password',
    AppStrings.mineightcharacters: 'MINIMO 8 CARATTERI',
    AppStrings.twofactorauthenticationcap: 'AUTENTICAZIONE A DUE FATTORI',
    AppStrings.twofactorauthentication: 'Autenticazione a due fattori',
    AppStrings.enable: 'Abilita',
    AppStrings.enablecap: 'ABILITA',
    AppStrings.accountclosure: 'Chiusura account',
    AppStrings.deleteyouraccountanddata: 'Elimina il tuo account e i dati',
    AppStrings.areyousureyouwanttodeleteyouraccount:
    'Sei sicuro di voler eliminare il tuo account?',
    AppStrings.deletecap: 'ELIMINA',
    AppStrings.settingscap: 'IMPOSTAZIONI',
    AppStrings.emails: 'Email',
    AppStrings.billings: 'Fatturazioni',
    AppStrings.profile: 'Profilo',
    AppStrings.selectlanguage: "Seleziona la lingua",
    AppStrings.languagecap: "LINGUA",
    AppStrings.changinglanguage: "Cambio della lingua...",
    AppStrings.currentbalancecap: 'SALDO ATTUALE',
    AppStrings.revenuefromshortscap: 'ENTRATE DA SHORTS',
    AppStrings.withdrawcap: 'RITIRO',
    AppStrings.coins: 'Monete',
    AppStrings.customamount: 'Importo personalizzato',

  };}