import 'all_app_strings.dart';

mixin AppLocaleMagyur {
  static const Map<String, dynamic> magyur = {
    AppStrings.somethingwentwrong: 'Valami hiba történt',
    AppStrings.nothingtodisplay: "Nincs megjeleníthető tartalom...",
    AppStrings.chat: 'Csevegés',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Videó',
    AppStrings.active: 'Aktív',
    AppStrings.inactive: 'Inaktív',
    AppStrings.edit: 'Szerkesztés',
    AppStrings.yes: 'Igen',
    AppStrings.no: 'Nem',
    AppStrings.settings: 'Beállítások',
    AppStrings.getcoins: 'Szerezzen érméket',
    AppStrings.promotions: 'Promóciók',
    AppStrings.errorloadingvideo: "Hiba történt a videó betöltésekor",
    AppStrings.errorloadingpage: "Hiba történt az oldal betöltésekor",
    AppStrings.comments: 'Hozzászólások',
    AppStrings.replyto: 'Válaszolni erre',
    AppStrings.replytonamecomment: 'Válasz erre a névre vonatkozó hozzászólásra',
    AppStrings.replies: 'Válaszok',
    AppStrings.post: 'Bejegyzés',
    AppStrings.nocommentsyet: 'Még nincsenek hozzászólások',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Írj egy üzenetet',
    AppStrings.nomessagesfound: "Nincs üzenet",
    AppStrings.failedtoloadthechatrroms: "Hiba történt a csevegőszobák betöltésekor",
    AppStrings.typeheretheusername: 'Írja ide a felhasználónevet',
    AppStrings.lockscreen: 'Képernyő lezárása',
    AppStrings.logout: 'Kijelentkezés',
    AppStrings.darkmode: 'Sötét mód',
    AppStrings.followers: 'Követők',
    AppStrings.followings: 'Követettek',
    AppStrings.recentfollowings: 'Legutóbbi követettek',
    AppStrings.recentfollowers: 'Legutóbbi követők',
    AppStrings.groupnmae: 'Csoport neve',
    AppStrings.required: '  szükséges',
    AppStrings.website: 'Weboldal',
    AppStrings.category: 'Kategória',
    AppStrings.validwebsiteurl: 'Érvényes weboldal URL',
    AppStrings.aboutthisgroup: 'A csoport bemutatása',
    AppStrings.areyousureyouwanttologout: 'Biztos, hogy ki akarsz jelentkezni?',
    AppStrings.writemoreaboutthisgroup: 'Írj többet erről a csoportról',
    AppStrings.sociallinks: 'Közösségi linkek',
    AppStrings.facebookprofilelink: 'Facebook profil link',
    AppStrings.xprofilelink: 'X profil link',
    AppStrings.instagramprofilelink: 'Instagram profil link',
    AppStrings.tiktokprofilelink: 'TikTok profil link',
    AppStrings.pinterestprofilelink: 'Pinterest profil link',
    AppStrings.steamprofilelink: 'Steam profil link',
    AppStrings.linkedInprofilelink: 'LinkedIn profil link',
    AppStrings.selectprivacy: 'Válassz adatvédelmet',
    AppStrings.groupwillbepublic: 'A csoport nyilvános lesz',
    AppStrings.submitgroup: 'Csoport beküldése',
    AppStrings.allrequiredfieldsshouldbefilled: 'Minden kötelező mezőt ki kell tölteni',
    AppStrings.errorloadinggroupdata: 'Hiba történt a csoport adatainak betöltésekor',
    AppStrings.artAndCulture: 'Művészet és kultúra',
    AppStrings.scienceAndTechnology: 'Tudomány és technológia',
    AppStrings.sport: 'Sport',
    AppStrings.music: 'Zene',
    AppStrings.gastronomy: 'Gasztronómia',
    AppStrings.fashionAndStyle: 'Divat és stílus',
    AppStrings.travelAndPlaces: 'Utazás és helyek',
    AppStrings.education: 'Oktatás',
    AppStrings.career: 'Karrier',
    AppStrings.businessAndFinance: 'Üzlet és pénzügyek',
    AppStrings.entertainment: 'Szórakozás',
    AppStrings.environmentAndEcology: 'Környezet és ökológia',
    AppStrings.agricultureAndHorticulture: 'Mezőgazdaság és kertészet',
    AppStrings.languagesAndCommunication: 'Nyelvek és kommunikáció',
    AppStrings.technologyAndDigital: 'Technológia és digitális',
    AppStrings.architectureAndDesign: 'Építészet és design',
    AppStrings.mediaAndJournalism: 'Média és újságírás',
    AppStrings.buyAndSell: 'Vásárlás és eladás',
    AppStrings.selectacategory: 'Válassz egy kategóriát',
    AppStrings.groupprofilepicture: 'Csoport profilkép',
    AppStrings.selectaimage: 'Válassz egy képet',
    AppStrings.groupcoverpicture: 'Csoport borítókép',
    AppStrings.createpost: 'Bejegyzés létrehozása',
    AppStrings.writesomething: 'Írj valamit...',
    AppStrings.createapoll: 'Kérdőív létrehozása',
    AppStrings.pollquestion: 'Kérdőív kérdése',
    AppStrings.polloption: 'Kérdőív válaszlehetőség',
    AppStrings.addoption: '+ Hozzáadás válaszlehetőség',
    AppStrings.checkin: 'Bejelentkezés',
    AppStrings.current: 'Aktuális',
    AppStrings.customLocation: 'Egyedi helyszín',
    AppStrings.onlyforclosefriend: 'Csak közeli barátoknak?',
    AppStrings.newsfeed: 'Hírcsatorna',
    AppStrings.story: 'Történet',
    AppStrings.contentmustbefilled: 'A tartalom kitöltése kötelező',
    AppStrings.polloptions: 'Kérdőív válaszlehetőségek:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions: 'A kérdőívnek tartalmaznia kell kérdést és legalább két válaszlehetőséget',
    AppStrings.firstofallselectanimage: 'Először válassz egy képet',
    AppStrings.browseondevice: 'Böngésszen az eszközön',
    AppStrings.joinedgroup: 'Csatlakozott csoport',
    AppStrings.leavegroupsuccessfully: 'Sikeresen elhagyta a csoportot',
    AppStrings.joingroup: 'Csatlakozz a csoporthoz',
    AppStrings.groupjoinedsuccessfully: 'Csoporthoz való csatlakozás sikeres',
    AppStrings.postdeletedsuccessfully: 'A bejegyzés sikeresen törölve',
    AppStrings.deleteallusersposts: 'Törölje az összes felhasználói bejegyzést',
    AppStrings.deletealluserscomments: 'Törölje az összes felhasználói kommentet',
    AppStrings.deleteposts: 'Bejegyzések törlése',
    AppStrings.deletecomments: 'Kommentek törlése',
    AppStrings.removethisuser: 'Távolítsa el ezt a felhasználót',
    AppStrings.delete: 'Törlés',
    AppStrings.editmemberdetails: 'TAG ADATAINAK MÓDOSÍTÁSA',
    AppStrings.availableroles: 'Elérhető szerepek',
    AppStrings.groupmanger: 'Csoport adminisztrátor',
    AppStrings.pagemanger: 'Oldal adminisztrátor',
    AppStrings.pagemangerdescription: 'Oldaladatok módosítása, oldaltagok módosítása, oldali bejegyzések módosítása, oldali bejegyzések kommentjeinek módosítása',
    AppStrings.groupmangerdescription: 'Csoportadatok módosítása, csoporttagok módosítása, csoportbejegyzések módosítása, csoportbejegyzések kommentjeinek módosítása',
    AppStrings.groupmoderatord: 'Csoport moderátor',
    AppStrings.pagemoderatord: 'Oldal moderátor',
    AppStrings.pagemoderatorddescription: 'Oldali bejegyzések módosítása, oldali bejegyzések kommentjeinek módosítása',
    AppStrings.groupmoderatorddescription: 'Csoportbejegyzések módosítása, csoportbejegyzések kommentjeinek módosítása',
    AppStrings.none: 'Nincs',
    AppStrings.availablepermission: 'Elérhető engedélyek',
    AppStrings.altergroupdetails: 'Csoportadatok módosítása',
    AppStrings.altergroupmembers: 'Csoporttagok módosítása',
    AppStrings.altergroupposts: 'Csoportbejegyzések módosítása',
    AppStrings.altergrouppostscomments: 'Csoportbejegyzések kommentjeinek módosítása',
    AppStrings.alterpagedetails: 'Oldaladatok módosítása',
    AppStrings.alterpagemembers: 'Oldaltagok módosítása',
    AppStrings.alterpageposts: 'Oldali bejegyzések módosítása',
    AppStrings.alterpagepostscomments: 'Oldali bejegyzések kommentjeinek módosítása',
    AppStrings.updateuser: 'Felhasználó frissítése',
    AppStrings.editgroup: 'Csoport szerkesztése',
    AppStrings.editpage: 'Oldal szerkesztése',
    AppStrings.deletegroup: 'Csoport törlése',
    AppStrings.deletepage: 'Oldal törlése',
    AppStrings.groupmembers: 'Csoporttagok',
    AppStrings.pagemembers: 'Oldaltagok',
    AppStrings.report: 'Jelentés',
    AppStrings.areyousureyouwanttodeletegroup: 'Biztosan törölni szeretnéd a csoportot?',
    AppStrings.areyousureyouwanttodeletepage: 'Biztosan törölni szeretnéd az oldalt?',
    AppStrings.youremailisnotverified: 'Az email címed nincs megerősítve',
    AppStrings.unauthenticated: 'Nem hitelesített',
    AppStrings.failedtodeletepost: 'A bejegyzés törlése nem sikerült',
    AppStrings.addingapost: 'Bejegyzés hozzáadása',
    AppStrings.golive: 'Indítsd el élőben',
    AppStrings.location: 'Helyszín',
    AppStrings.timestamp: 'Időbélyeg',
    AppStrings.votes: 'Szavazatok',
    AppStrings.short: 'rövid',
    AppStrings.reply: 'válasz',
    AppStrings.shortvideopost: 'rövid videó bejegyzés',
    AppStrings.shares: 'Megosztások',
    AppStrings.share: 'Megosztás',
    AppStrings.comment: 'hozzászólás',
    AppStrings.hidecomments: 'Hozzászólások elrejtése',
    AppStrings.viewmorecomments: 'További hozzászólások megtekintése',
    AppStrings.replytonamepost: 'válasz a név bejegyzésére',
    AppStrings.name: 'név',
    AppStrings.onedayago: '1 nappal ezelőtt',
    AppStrings.promote: 'Népszerűsítés',
    AppStrings.increaseyourpopularity: 'Növeld a népszerűséged',
    AppStrings.allocatecoinsforpromotions: 'Érmék allokálása a népszerűsítéshez',
    AppStrings.like: 'Tetszik',
    AppStrings.viewpost: 'Bejegyzés megtekintése',
    AppStrings.replypost: 'Bejegyzés válaszolása',
    AppStrings.submitanewpost: 'ÚJ BEJEGYZÉS BENYÚJTÁSA',
    AppStrings.submitanewpostdescription: 'Tápláld ezt a jelentést átfogó tartalommal. Kérjük, minél több részletet adj meg, minden lehetséges formában a megfelelő megoldás érdekében.',
    AppStrings.content: 'tartalom',
    AppStrings.reportnow: 'jelentés most',
    AppStrings.failedtoremovelock: 'Nem sikerült eltávolítani a zárolást',
    AppStrings.password: 'Jelszó',
    AppStrings.unlock: 'Feloldás',
    AppStrings.thesecredentialsdonotmatch: 'Ezek az adatok nem egyeznek',
    AppStrings.login: 'Bejelentkezés',
    AppStrings.signin: 'bejelentkezés',
    AppStrings.signup: 'regisztráció',
    AppStrings.email: 'E-mail',
    AppStrings.rememberme: 'Emlékezz rám',
    AppStrings.forgetpassword: 'Elfelejtett jelszó',
    AppStrings.notifications: 'Értesítések',
    AppStrings.pages: 'oldalak',
    AppStrings.createnewpage: 'ÚJ OLDAL LÉTREHOZÁSA',
    AppStrings.members: 'Tagok',
    AppStrings.creators: 'Alkotók',
    AppStrings.page: 'Oldal',
    AppStrings.submitpage: 'Oldal benyújtása',
    AppStrings.aboutthispage: 'Az oldalról',
    AppStrings.writemoreaboutthispage: 'Írj többet erről az oldalról',
    AppStrings.pagename: 'Oldal neve',
    AppStrings.private: 'privát',
    AppStrings.public: 'nyilvános',
    AppStrings.invite: 'MEGHÍVÓ',
    AppStrings.about: 'RÓLUNK',
    AppStrings.photos: 'FOTÓK',
    AppStrings.events: 'ESEMÉNYEK',
    AppStrings.pagewillbepublic: 'Az oldal nyilvános lesz',
    AppStrings.pagefollowed: 'Oldal követve',
    AppStrings.joinpage: 'Csatlakozás az oldalhoz',
    AppStrings.pageleavedsuccessfully: 'Oldal elhagyása sikeresen',
    AppStrings.pagejoinedsuccessfully: 'Oldal csatlakozás sikeresen',
    AppStrings.userspage: 'Felhasználó oldala',
    AppStrings.paymentcompletedsuccessfully: 'Fizetés sikeresen befejezve!',
    AppStrings.stripepayment: 'Stripe Fizetés',
    AppStrings.myphotos: 'Saját fényképek',
    AppStrings.recentphotos: 'Legutóbbi fényképek',
    AppStrings.recentposts: 'Legutóbbi bejegyzések',
    AppStrings.savedshorts: 'Mentett rövid videók',
    AppStrings.seeall: 'Mindet megtekinteni',
    AppStrings.groups: 'Csoportok',
    AppStrings.errorloadingaccountdetails: 'Hiba a fiók adatai betöltésekor',
    AppStrings.errorloadingprofile: 'Hiba a profil betöltésekor',
    AppStrings.timeline: 'Idővonal',
    AppStrings.saved: 'Mentett',
    AppStrings.restricted: 'Korlátozott',
    AppStrings.blocked: 'Blokkolt',
    AppStrings.register: 'Regisztrálj',
    AppStrings.date: 'Dátum',
    AppStrings.find: 'Keresés',
    AppStrings.users: 'Felhasználók',
    AppStrings.status: 'Státusz',
    AppStrings.open: 'Nyitott',
    AppStrings.closed: 'Zárt',
    AppStrings.title: 'Cím',
    AppStrings.edittickets: 'Jegyek szerkesztése',
    AppStrings.postareply: 'Válasz küldése',
    AppStrings.createdat: 'Létrehozva',
    AppStrings.lastreplyby: 'Utolsó válaszadó',
    AppStrings.repliesintotal: 'Összes válasz',
    AppStrings.supportTickets: 'Támogatási jegyek',
    AppStrings.ticketsummary: 'Jegy összefoglaló',
    AppStrings.availableactions: 'Elérhető műveletek',
    AppStrings.retypepassword: 'Jelszó újra',
    AppStrings.yourname: 'A te neved',
    AppStrings.selectyourcountry: 'Válaszd ki az országod',
    AppStrings.username: 'Felhasználónév',
    AppStrings.searchby: 'Keresés alapján',
    AppStrings.searchresults: 'Keresési eredmények',
    AppStrings.searchpeoplegrouporpage: 'Keresés emberek, csoportok vagy oldalak között',
    AppStrings.followaddedsuccessfully: 'Követés sikeresen hozzáadva',
    AppStrings.followremovedsuccessfully: 'Követés sikeresen eltávolítva',
    AppStrings.pleaseverifyyuouremail: 'Kérjük, ellenőrizd az e-mailed',
    AppStrings.verifyyouraccount: 'Ellenőrizd a fiókodat',
    AppStrings.sendverificationlink: 'Ellenőrző link küldése',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow: 'Ha már megkaptad a linket, vagy ha van fiókod, jelentkezz be most',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere: 'Ha nem kaptál linket, kérlek kattints ide',
    AppStrings.videos: 'Videók',
    AppStrings.videoselected: 'Videó kiválasztva!',
    AppStrings.donate: 'Adományozni',
    AppStrings.recentvideos: 'Legutóbbi videók',
    AppStrings.firstofallselectvideo: 'Először is, válassz egy videót',
    AppStrings.shortdescriprtiontags: 'Rövid leírás,  #címkék',
    AppStrings.postshort: '↑ Postolj rövidet',
    AppStrings.pleaseselectavideofile: 'Kérlek válassz egy videófájlt',
    AppStrings.donations: 'Adományok',
    AppStrings.topdonations: 'Legnagyobb adományok',
    AppStrings.helptheshortcreator: 'Segíts a rövid videó készítőjének.',
    AppStrings.sharethispostto: 'Oszd meg ezt a posztot itt: ',
    AppStrings.copylink: 'Link másolása',
    AppStrings.selectanuser: 'Válassz egy felhasználót',
    AppStrings.user111: 'felhasználó111',
    AppStrings.sharenow: 'Oszd meg most',
    AppStrings.reopenticket: 'Ticket újranyitása',
    AppStrings.closeticket: 'Ticket bezárása',
    AppStrings.supportsticket: 'Támogatási jegy',
    AppStrings.totalticket: 'ÖSSZES JEGY',
    AppStrings.solvedticket: 'MEGOLDOTT JEGYEK',
    AppStrings.openedissues: 'NYITOTT PROBLÉMÁK',
    AppStrings.sendemail: 'E-mail küldése',
    AppStrings.support: 'Támogatás',
    AppStrings.openticket: 'Új ticket nyitása',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto: 'Ha inkább e-mailben szeretnél kapcsolatba lépni, kérjük küldd el érdeklődésedet ide:',
    AppStrings.ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure: 'Ha ezt a sort olvasod, úgy tűnik, hogy a problémád tényleg komoly... kérlek tudass minket többet róla, biztosan segítünk.',
    AppStrings.createanewsupportticket: 'Új támogatási jegy létrehozása',
    AppStrings.newintervention: 'Új beavatkozás',
    AppStrings.interventiontitle: 'Beavatkozás címe',
    AppStrings.typeherethetitle: 'Írd ide a címet',
    AppStrings.submitticket: 'Jegy benyújtása',
    AppStrings.submitcomment: 'Hozzászólás benyújtása',
    AppStrings.contentmustnotbelessthentencharacters: 'A tartalom nem lehet kevesebb, mint 10 karakter',
    AppStrings.completeinterventiontitle: 'Töltsd ki ezt a beavatkozást részletes tartalommal. Kérjük, adj meg minél több információt, hogy megfelelő megoldást találhassunk.',
    AppStrings.updatecomment: 'Hozzászólás frissítése',
    AppStrings.updatethereply: 'Válasz frissítése',
    AppStrings.commentcontent: 'Töltsd ki ezt a választ részletes tartalommal. Kérjük, adj meg minél több információt a megfelelő megoldás érdekében.',
    AppStrings.thereisopeninterventionticketcloseitfirst: 'Van egy nyitott beavatkozási jegy, először azt kell bezárnod.',
    AppStrings.addanewcomment: 'Új hozzászólás hozzáadása',
    AppStrings.billingarea: 'Számlázási terület',
    AppStrings.billingareacap: 'SZÁMLÁZÁSI TERÜLET',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount: 'Böngéssz tranzakciók között, és adj hozzá több érmét a fiókhoz',
    AppStrings.topup: 'FELTÖLTÉS',
    AppStrings.gotopayment: 'Menj a fizetéshez',
    AppStrings.paymentfailed: 'Fizetés sikertelen',
    AppStrings.pleaseselectanamount: 'Kérlek válassz egy összeget',
    AppStrings.showlatesttransactionscap: 'LEGÚJABB TRANZAKCIÓK MEGJELENTETÉSE',
    AppStrings.transactionscap: 'TRANZAKCIÓK',
    AppStrings.transactionnote: 'Kövesd és tekintsd meg a bejövő vagy kimenő tranzakciókat, és készülj fel a következő eredményeidre.',
    AppStrings.searchtransactionsby: 'Tranzakciók keresése szerint',
    AppStrings.searchtransactions: 'Tranzakciók keresése',
    AppStrings.alltransactions: 'Minden tranzakció',
    AppStrings.transactionname: 'Tranzakció neve',
    AppStrings.transactionid: 'Tranzakció azonosító',
    AppStrings.querytobeexecuted: 'Végrehajtandó lekérdezés',
    AppStrings.settingssaved: 'Beállítások elmentve',
    AppStrings.general: 'Általános',
    AppStrings.failedtosavesettigns: 'A beállítások mentése nem sikerült',
    AppStrings.emailpreferences: 'E-mail beállítások',
    AppStrings.emailnotificationscap: 'E-MAIL ÉRTESÍTÉSEK',
    AppStrings.savepreferences: 'Beállítások mentése',
    AppStrings.sendmeemailsaboutmyentireactivity: 'Küldj nekem e-maileket az összes tevékenységemről',
    AppStrings.selectpushandemailnotificationyouliketorecieve: 'Válaszd ki a push és e-mail értesítéseket, amiket szeretnél kapni',
    AppStrings.onlysendmerequiredemails: 'Csak a szükséges e-maileket küldd el nekem',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges: 'Megjegyzés: Mindig kapsz értesítést az egyéni fiók változásokról.',
    AppStrings.enablefollowmecap: 'KÖVESS ENGEM ENGEDÉLYEZÉSE',
    AppStrings.sendmenotificationscap: 'KÜLDJ ÉRTESÍTÉSEKET',
    AppStrings.enablethisifyouwantpeopletofollowyou: 'Engedélyezd ezt, ha szeretnéd, hogy kövessenek téged',
    AppStrings.sendmenotificationaboutmyfriendlike: 'Küldj értesítést a barátom tetszéseiről',
    AppStrings.shareormessageme: 'Oszd meg vagy üzenj nekem.',
    AppStrings.hideyourprofilefromsearchengine: 'Rejtsd el a profilodat a keresőmotorok elől',
    AppStrings.searchprivacycap: 'KERESÉSI ADATVÉDELEM',
    AppStrings.hidegendercap: 'REJTSD EL A NEMET',
    AppStrings.hideagecap: 'REJTSD EL A KOROT',
    AppStrings.hidelocationcap: 'REJTSD EL A HELYET',
    AppStrings.profilecap: 'PROFIL',
    AppStrings.editprofilecap: 'PROFIL SZERKESZTÉSE',
    AppStrings.changecap: 'MÓDOSÍTÁS',
    AppStrings.displaynamecap: 'MEGJELENÍTETT NÉV',
    AppStrings.peopleongenixwillgettoknowbybelowinfo: 'A Genix-en lévők az alábbi információk alapján fognak megismerni',
    AppStrings.showingname: 'Megjelenített név',
    AppStrings.usernamecap: 'FELHASZNÁLÓI NÉV',
    AppStrings.emailaddressecap: 'E-MAIL CÍM',
    AppStrings.youremailaddress: 'A te e-mail címed',
    AppStrings.gendercap: 'NEM',
    AppStrings.male: 'Férfi',
    AppStrings.female: 'Nő',
    AppStrings.bio: 'Bio',
    AppStrings.tellusmoreaboutyou: 'Mondj többet rólad',
    AppStrings.socialprofilelinks: 'Közösségi profil linkek',
    AppStrings.citycap: 'VÁROS',
    AppStrings.countrycap: 'ORSZÁG',
    AppStrings.yourcity: 'A te városod',
    AppStrings.paypalemailaddress: 'PAY-PAL E-mail cím',
    AppStrings.enteryourpaypalemailaddress: 'Add meg a PAY-PAL e-mail címed',
    AppStrings.security: 'Biztonság',
    AppStrings.accountpasswordcap: 'FÓRUM JELSZÓ',
    AppStrings.changeyourpasswordandalterothersecurityoptions: 'Módosítsd a jelszavadat és állíts be egyéb biztonsági lehetőségeket',
    AppStrings.currentpasswordcap: 'JELENLEGI JELSZÓ',
    AppStrings.currentpassword: 'Jelenlegi jelszó',
    AppStrings.newpassword: 'Új jelszó',
    AppStrings.confirmpassword: 'Jelszó megerősítése',
    AppStrings.repeatnewpassword: 'Új jelszó ismétlés',
    AppStrings.mineightcharacters: 'MIN 8 KARAKTER',
    AppStrings.twofactorauthenticationcap: 'KÉTFAKTOROS HITelesítés',
    AppStrings.twofactorauthentication: 'Kétfaktoros hitelesítés',
    AppStrings.enable: 'Engedélyezés',
    AppStrings.enablecap: 'ENGEDÉLYEZÉS',
    AppStrings.accountclosure: 'Fiók törlése',
    AppStrings.deleteyouraccountanddata: 'Töröld a fiókodat és az adatokat',
    AppStrings.areyousureyouwanttodeleteyouraccount: 'Biztosan törölni szeretnéd a fiókodat?',
    AppStrings.deletecap: 'TÖRÖLÉS',
    AppStrings.settingscap: 'BEÁLLÍTÁSOK',
    AppStrings.emails: 'E-mailek',
    AppStrings.billings: 'Számlázás',
    AppStrings.profile: 'Profil',
    AppStrings.selectlanguage: "Nyelv kiválasztása",
    AppStrings.languagecap: "NYELV",
    AppStrings.changinglanguage: "Nyelv módosítása...",
    AppStrings.currentbalancecap: 'JELENLEGI EGYESEK',
    AppStrings.revenuefromshortscap: 'BEVÉTEL A KISFILMEK RÉVÉN',
    AppStrings.withdrawcap: 'KIVONÁS',
    AppStrings.coins: 'Érmék',
    AppStrings.customamount: 'Egyedi összeg',

  };}