import 'all_app_strings.dart';

mixin AppLocalePolski {
  static const Map<String, dynamic> polski = {
    AppStrings.somethingwentwrong: 'Coś poszło nie tak',
    AppStrings.nothingtodisplay: "Nic do wyświetlenia...",
    AppStrings.chat: 'Czat',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Wideo',
    AppStrings.active: 'Aktywny',
    AppStrings.inactive: 'Nieaktywny',
    AppStrings.edit: 'Edytuj',
    AppStrings.yes: 'Tak',
    AppStrings.no: 'Nie',
    AppStrings.settings: 'Ustawienia',
    AppStrings.getcoins: 'Zdobądź monety',
    AppStrings.promotions: 'Promocje',
    AppStrings.errorloadingvideo: "Błąd ładowania wideo",
    AppStrings.errorloadingpage: "Błąd ładowania strony",
    AppStrings.comments: 'Komentarze',
    AppStrings.replyto: 'Odpowiedz na',
    AppStrings.replytonamecomment: 'Odpowiedz na komentarz nazwy',
    AppStrings.replies: 'Odpowiedzi',
    AppStrings.post: 'Post',
    AppStrings.nocommentsyet: 'Brak komentarzy',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Wpisz wiadomość',
    AppStrings.nomessagesfound: "Brak wiadomości",
    AppStrings.failedtoloadthechatrroms: "Nie udało się załadować pokoi czatu",
    AppStrings.typeheretheusername: 'Wpisz nazwę użytkownika',
    AppStrings.lockscreen: 'Zablokuj ekran',
    AppStrings.logout: 'Wyloguj się',
    AppStrings.darkmode: 'Tryb ciemny',
    AppStrings.followers: 'Obserwujący',
    AppStrings.followings: 'Obserwowane',
    AppStrings.recentfollowings: 'Ostatnio obserwowane',
    AppStrings.recentfollowers: 'Ostatni obserwujący',
    AppStrings.groupnmae: 'Nazwa grupy',
    AppStrings.required: 'wymagane',
    AppStrings.website: 'Strona internetowa',
    AppStrings.category: 'Kategoria',
    AppStrings.validwebsiteurl: 'Prawidłowy adres URL strony',
    AppStrings.aboutthisgroup: 'O tej grupie',
    AppStrings.areyousureyouwanttologout: 'Czy na pewno chcesz się wylogować?',
    AppStrings.writemoreaboutthisgroup: 'Napisz więcej o tej grupie',
    AppStrings.sociallinks: 'Linki do mediów społecznościowych',
    AppStrings.facebookprofilelink: 'Link do profilu na Facebooku',
    AppStrings.xprofilelink: 'Link do profilu na X',
    AppStrings.instagramprofilelink: 'Link do profilu na Instagramie',
    AppStrings.tiktokprofilelink: 'Link do profilu na TikToku',
    AppStrings.pinterestprofilelink: 'Link do profilu na Pintereście',
    AppStrings.steamprofilelink: 'Link do profilu na Steamie',
    AppStrings.linkedInprofilelink: 'Link do profilu na LinkedIn',
    AppStrings.selectprivacy: 'Wybierz prywatność',
    AppStrings.groupwillbepublic: 'Grupa będzie publiczna',
    AppStrings.submitgroup: 'Prześlij grupę',
    AppStrings.allrequiredfieldsshouldbefilled: 'Wszystkie wymagane pola powinny być wypełnione',
    AppStrings.errorloadinggroupdata: 'Błąd ładowania danych grupy',
    AppStrings.artAndCulture: 'Sztuka i kultura',
    AppStrings.scienceAndTechnology: 'Nauka i technologia',
    AppStrings.sport: 'Sport',
    AppStrings.music: 'Muzyka',
    AppStrings.gastronomy: 'Gastronomia',
    AppStrings.fashionAndStyle: 'Moda i styl',
    AppStrings.travelAndPlaces: 'Podróże i miejsca',
    AppStrings.education: 'Edukacja',
    AppStrings.career: 'Kariera',
    AppStrings.businessAndFinance: 'Biznes i finanse',
    AppStrings.entertainment: 'Rozrywka',
    AppStrings.environmentAndEcology: 'Środowisko i ekologia',
    AppStrings.agricultureAndHorticulture: 'Rolnictwo i ogrodnictwo',
    AppStrings.languagesAndCommunication: 'Języki i komunikacja',
    AppStrings.technologyAndDigital: 'Technologia i cyfryzacja',
    AppStrings.architectureAndDesign: 'Architektura i design',
    AppStrings.mediaAndJournalism: 'Media i dziennikarstwo',
    AppStrings.buyAndSell: 'Kupno i sprzedaż',
    AppStrings.selectacategory: 'Wybierz kategorię',
    AppStrings.groupprofilepicture: 'Zdjęcie profilowe grupy',
    AppStrings.selectaimage: 'Wybierz obraz',
    AppStrings.groupcoverpicture: 'Zdjęcie okładki grupy',
    AppStrings.createpost: 'Stwórz post',
    AppStrings.writesomething: 'Napisz coś...',
    AppStrings.createapoll: 'Stwórz ankietę',
    AppStrings.pollquestion: 'Pytanie ankiety',
    AppStrings.polloption: 'Opcja ankiety',
    AppStrings.addoption: '+ Dodaj opcję',
    AppStrings.checkin: 'Zameldowanie',
    AppStrings.current: 'Bieżący',
    AppStrings.customLocation: 'Własna lokalizacja',
    AppStrings.onlyforclosefriend: 'Tylko dla bliskich przyjaciół?',
    AppStrings.newsfeed: 'Aktualności',
    AppStrings.story: 'Historia',
    AppStrings.contentmustbefilled: 'Treść musi być wypełniona',
    AppStrings.polloptions: 'Opcje ankiety:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions: 'Ankieta musi mieć pytanie i przynajmniej dwie opcje',
    AppStrings.firstofallselectanimage: 'Najpierw wybierz obraz',
    AppStrings.browseondevice: 'Przeglądaj w urządzeniu',
    AppStrings.joinedgroup: 'Dołączona grupa',
    AppStrings.leavegroupsuccessfully: 'Pomyślnie opuściłeś grupę',
    AppStrings.joingroup: 'Dołącz do grupy',
    AppStrings.groupjoinedsuccessfully: 'Pomyślnie dołączono do grupy',
    AppStrings.postdeletedsuccessfully: 'Post usunięty pomyślnie',
    AppStrings.deleteallusersposts: 'Usuń wszystkie posty użytkownika',
    AppStrings.deletealluserscomments: 'Usuń wszystkie komentarze użytkownika',
    AppStrings.deleteposts: 'Usuń posty',
    AppStrings.deletecomments: 'Usuń komentarze',
    AppStrings.removethisuser: 'Usuń tego użytkownika',
    AppStrings.delete: 'Usuń',
    AppStrings.editmemberdetails: 'EDYTUJ SZCZEGÓŁY CZŁONKA',
    AppStrings.availableroles: 'Dostępne role',
    AppStrings.groupmanger: 'Menadżer grupy',
    AppStrings.pagemanger: 'Menadżer strony',
    AppStrings.pagemangerdescription:
    'zmień szczegóły strony, zmień członków strony, zmień posty na stronie, zmień komentarze do postów na stronie',
    AppStrings.groupmangerdescription:
    'zmień szczegóły grupy, zmień członków grupy, zmień posty w grupie, zmień komentarze do postów w grupie',
    AppStrings.groupmoderatord: 'Moderator grupy',
    AppStrings.pagemoderatord: 'Moderator strony',
    AppStrings.pagemoderatorddescription:
    'zmień posty na stronie, zmień komentarze do postów na stronie',
    AppStrings.groupmoderatorddescription:
    'zmień posty w grupie, zmień komentarze do postów w grupie',
    AppStrings.none: 'Brak',
    AppStrings.availablepermission: 'Dostępne uprawnienia',
    AppStrings.altergroupdetails: 'Zmień szczegóły grupy',
    AppStrings.altergroupmembers: 'Zmień członków grupy',
    AppStrings.altergroupposts: 'Zmień posty w grupie',
    AppStrings.altergrouppostscomments: 'Zmień komentarze do postów w grupie',
    AppStrings.alterpagedetails: 'Zmień szczegóły strony',
    AppStrings.alterpagemembers: 'Zmień członków strony',
    AppStrings.alterpageposts: 'Zmień posty na stronie',
    AppStrings.alterpagepostscomments: 'Zmień komentarze do postów na stronie',
    AppStrings.updateuser: 'Aktualizuj użytkownika',
    AppStrings.editgroup: 'Edytuj grupę',
    AppStrings.editpage: 'Edytuj stronę',
    AppStrings.deletegroup: 'Usuń grupę',
    AppStrings.deletepage: 'Usuń stronę',
    AppStrings.groupmembers: 'Członkowie grupy',
    AppStrings.pagemembers: 'Członkowie strony',
    AppStrings.report: 'Zgłoś',
    AppStrings.areyousureyouwanttodeletegroup:
    'Czy na pewno chcesz usunąć grupę?',
    AppStrings.areyousureyouwanttodeletepage:
    'Czy na pewno chcesz usunąć stronę?',
    AppStrings.youremailisnotverified: 'Twój email nie został zweryfikowany',
    AppStrings.unauthenticated: 'Nieautoryzowany',
    AppStrings.failedtodeletepost: 'Nie udało się usunąć posta',
    AppStrings.addingapost: 'dodawanie posta',
    AppStrings.golive: 'Rozpocznij transmisję',
    AppStrings.location: 'Lokalizacja',
    AppStrings.timestamp: 'Znacznik czasu',
    AppStrings.votes: 'głosy',
    AppStrings.short: 'krótkie',
    AppStrings.reply: 'odpowiedź',
    AppStrings.shortvideopost: 'krótki post wideo',
    AppStrings.shares: 'Udostępnienia',
    AppStrings.share: 'Udostępnij',
    AppStrings.comment: 'komentarz',
    AppStrings.hidecomments: 'Ukryj komentarze',
    AppStrings.viewmorecomments: 'Zobacz więcej komentarzy',
    AppStrings.replytonamepost: 'odpowiedź na post nazwy',
    AppStrings.name: 'nazwa',
    AppStrings.onedayago: '1 dzień temu',
    AppStrings.promote: 'Promuj',
    AppStrings.increaseyourpopularity: 'Zwiększ swoją popularność',
    AppStrings.allocatecoinsforpromotions: 'Przydziel monety na promocje',
    AppStrings.like: 'Lubię to',
    AppStrings.viewpost: 'Zobacz post',
    AppStrings.replypost: 'Odpowiedz na post',
    AppStrings.submitanewpost: 'ZŁOŻYĆ NOWY POST',
    AppStrings.submitanewpostdescription:
    'Wypełnij ten raport szczegółową treścią. Proszę dołączyć jak najwięcej szczegółów w możliwych formach, aby uzyskać odpowiednią odpowiedź.',
    AppStrings.content: 'treść',
    AppStrings.reportnow: 'zgłoś teraz',
    AppStrings.failedtoremovelock: 'Nie udało się usunąć blokady',
    AppStrings.password: 'Hasło',
    AppStrings.unlock: 'Odblokuj',
    AppStrings.thesecredentialsdonotmatch: 'Te dane logowania się nie zgadzają',
    AppStrings.login: 'Zaloguj się',
    AppStrings.signin: 'zaloguj się',
    AppStrings.signup: 'zarejestruj się',
    AppStrings.email: 'E-mail',
    AppStrings.rememberme: 'Zapamiętaj mnie',
    AppStrings.forgetpassword: 'Zapomniałeś hasła',
    AppStrings.notifications: 'Powiadomienia',
    AppStrings.pages: 'strony',
    AppStrings.createnewpage: 'STWÓRZ NOWĄ STRONĘ',
    AppStrings.members: 'Członkowie',
    AppStrings.creators: 'Twórcy',
    AppStrings.page: 'Strona',
    AppStrings.submitpage: 'Prześlij stronę',
    AppStrings.aboutthispage: 'O tej stronie',
    AppStrings.writemoreaboutthispage: 'Napisz więcej o tej stronie',
    AppStrings.pagename: 'Nazwa strony',
    AppStrings.private: 'prywatne',
    AppStrings.public: 'publiczne',
    AppStrings.invite: 'ZAPROŚ',
    AppStrings.about: 'O',
    AppStrings.photos: 'ZDJĘCIA',
    AppStrings.events: 'WYDARZENIA',
    AppStrings.pagewillbepublic: 'Strona będzie publiczna',
    AppStrings.pagefollowed: 'Strona obserwowana',
    AppStrings.joinpage: 'Join Page',
    AppStrings.pageleavedsuccessfully: 'Page Leaved Successfully',
    AppStrings.pagejoinedsuccessfully: 'Page Joined Successfully',
    AppStrings.userspage: 'User\'s page',
    AppStrings.paymentcompletedsuccessfully: 'Payment completed successfully!',
    AppStrings.stripepayment: 'Stripe Payment',
    AppStrings.myphotos: 'My Photos',
    AppStrings.recentphotos: 'Recent Photos',
    AppStrings.recentposts: 'Recent Posts',
    AppStrings.savedshorts: 'Saved Shorts',
    AppStrings.seeall: 'See All',
    AppStrings.groups: 'Groups',
    AppStrings.errorloadingaccountdetails: 'Error Loading Account Details',
    AppStrings.errorloadingprofile: 'Error Loading Profile',
    AppStrings.timeline: 'Timeline',
    AppStrings.saved: 'Saved',
    AppStrings.restricted: 'Restricted',
    AppStrings.blocked: 'Blocked',
    AppStrings.register: 'Register',
    AppStrings.date: 'Date',
    AppStrings.find: 'Find',
    AppStrings.users: 'Users',
    AppStrings.status: 'Status',
    AppStrings.open: 'Open',
    AppStrings.closed: 'Closed',
    AppStrings.title: 'Title',
    AppStrings.edittickets: 'Edit tickets',
    AppStrings.postareply: 'Post a reply',
    AppStrings.createdat: 'Created At',
    AppStrings.lastreplyby: 'Last reply By',
    AppStrings.repliesintotal: 'Replies in total',
    AppStrings.supportTickets: 'Support Tickets',
    AppStrings.ticketsummary: 'Ticket Summary',
    AppStrings.availableactions: 'Available Actions',
    AppStrings.retypepassword: 'Retype Password',
    AppStrings.yourname: 'Your Name',
    AppStrings.selectyourcountry: 'Select Your Country',
    AppStrings.username: 'User Name',
    AppStrings.searchby: 'Search By',
    AppStrings.searchresults: 'Search Results',
    AppStrings.searchpeoplegrouporpage: 'Search People, group or pages',
    AppStrings.followaddedsuccessfully: 'Follow Added Successfully',
    AppStrings.followremovedsuccessfully: 'Follow Removed Successfully',
    AppStrings.pleaseverifyyuouremail: 'Please Verify Your email',
    AppStrings.verifyyouraccount: 'verify your account',
    AppStrings.sendverificationlink: 'Send Verification Link',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
    'if you have already received a link or if you have an account , log in now',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere:
    'if you have\'t received a link please click here',
    AppStrings.videos: 'Videos',
    AppStrings.videoselected: 'Video Selected!',
    AppStrings.donate: 'Donate',
    AppStrings.recentvideos: 'Recent Videos',
    AppStrings.firstofallselectvideo: 'First of all, select a video',
    AppStrings.shortdescriprtiontags: 'Short Description,  #tags',
    AppStrings.postshort: '↑ Post short',
    AppStrings.pleaseselectavideofile: 'Please select a video file',
    AppStrings.donations: 'Donations',
    AppStrings.topdonations: 'Top Donations',
    AppStrings.helptheshortcreator: 'Help the short creator.',
    AppStrings.sharethispostto: 'Share this post to',
    AppStrings.copylink: 'Copy Link',
    AppStrings.selectanuser: 'Select an User',
    AppStrings.user111: 'user111',
    AppStrings.sharenow: 'Share Now',
    AppStrings.reopenticket: 'Reopen ticket',
    AppStrings.closeticket: 'Close ticket',
    AppStrings.supportsticket: 'Supports ticket',
    AppStrings.totalticket: 'TOTAL TICKETS',
    AppStrings.solvedticket: 'SOLVED TICKETS',
    AppStrings.openedissues: 'OPENED ISSUES',
    AppStrings.sendemail: 'Send email',
    AppStrings.support: 'Support',
    AppStrings.openticket: 'Open ticket',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
    'If you would prefer to contact us by email, please send us your inquiry to:',
    AppStrings.ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
    'If you read this line it looks like your issue is really serious.. please let us know more about this, we will help you for sure.',
    AppStrings.createanewsupportticket: 'Create a new support ticket',
    AppStrings.newintervention: 'New Intervention',
    AppStrings.interventiontitle: 'Intervention title',
    AppStrings.typeherethetitle: 'Type here the title',
    AppStrings.submitticket: 'Submit ticket',
    AppStrings.submitcomment: 'Submit comment',
    AppStrings.contentmustnotbelessthentencharacters: 'Content must not be less than ten characters',
    AppStrings.completeinterventiontitle:
    'Feed this intervention with comprehensive content. Please include as many details as you can, in all possible forms to get a proper resolution.',
    AppStrings.updatecomment: 'Update comment',
    AppStrings.updatethereply: 'Update the reply',
    AppStrings.commentcontent:
    'Feed this reply with comprehensive content. Please include as many details as you can, in all possible forms to get a proper resolution.',
    AppStrings.thereisopeninterventionticketcloseitfirst:
    'There is an open intervention ticket, please close it first.',
    AppStrings.addanewcomment: 'Add a new comment',
    AppStrings.billingarea: 'Billing area',
    AppStrings.billingareacap: 'BILLING AREA',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount:
    'Browse transactions, and add more coins into your account',
    AppStrings.topup: 'TOP UP',
    AppStrings.gotopayment: 'Przejdź do płatności',
    AppStrings.paymentfailed: 'Płatność nie powiodła się',
    AppStrings.pleaseselectanamount: 'Proszę wybrać kwotę',
    AppStrings.showlatesttransactionscap: 'POKAŻ NAJNOWSZE TRANSAKCJE',
    AppStrings.transactionscap: 'TRANSAKCJE',
    AppStrings.transactionnote: 'Śledź i przeglądaj przychodzące lub wychodzące transakcje i przygotuj się na kolejne osiągnięcia.',
    AppStrings.searchtransactionsby: 'Szukaj transakcji po',
    AppStrings.searchtransactions: 'Szukaj transakcji',
    AppStrings.alltransactions: 'Wszystkie transakcje',
    AppStrings.transactionname: 'Nazwa transakcji',
    AppStrings.transactionid: 'ID transakcji',
    AppStrings.querytobeexecuted: 'Zapytanie do wykonania',
    AppStrings.settingssaved: 'Ustawienia zapisane',
    AppStrings.general: 'Ogólne',
    AppStrings.failedtosavesettigns: 'Nie udało się zapisać ustawień',
    AppStrings.emailpreferences: 'Preferencje e-mail',
    AppStrings.emailnotificationscap: 'POWIADOMIENIA E-MAIL',
    AppStrings.savepreferences: 'Zapisz preferencje',
    AppStrings.sendmeemailsaboutmyentireactivity: 'Wyślij mi e-maile o mojej całej aktywności',
    AppStrings.selectpushandemailnotificationyouliketorecieve: 'Wybierz powiadomienia push i e-mail, które chcesz otrzymywać',
    AppStrings.onlysendmerequiredemails: 'Wyślij mi tylko wymagane e-maile',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges: 'Uwaga: Zawsze będziesz otrzymywać powiadomienia o zmianach w koncie.',
    AppStrings.enablefollowmecap: 'WŁĄCZ ŚLEDZENIE MNIE',
    AppStrings.sendmenotificationscap: 'WYŚLIJ MI POWIADOMIENIA',
    AppStrings.enablethisifyouwantpeopletofollowyou: 'Włącz to, jeśli chcesz, aby ludzie cię śledzili',
    AppStrings.sendmenotificationaboutmyfriendlike: 'Wyślij mi powiadomienie o polubieniu mojego przyjaciela',
    AppStrings.shareormessageme: 'Udostępnij lub wyślij mi wiadomość.',
    AppStrings.hideyourprofilefromsearchengine: 'Ukryj swój profil przed wyszukiwarkami',
    AppStrings.searchprivacycap: 'PRYWATNOŚĆ WYSZUKIWANIA',
    AppStrings.hidegendercap: 'UKRYJ PŁEĆ',
    AppStrings.hideagecap: 'UKRYJ WIEK',
    AppStrings.hidelocationcap: 'UKRYJ LOKACJĘ',
    AppStrings.profilecap: 'PROFIL',
    AppStrings.editprofilecap: 'EDYTUJ PROFIL',
    AppStrings.changecap: 'ZMIANA',
    AppStrings.displaynamecap: 'NAZWA WYŚWIETLANA',
    AppStrings.peopleongenixwillgettoknowbybelowinfo: 'Ludzie na Genix poznają cię po poniższych informacjach',
    AppStrings.showingname: 'Pokazywana nazwa',
    AppStrings.usernamecap: 'NAZWA UŻYTKOWNIKA',
    AppStrings.emailaddressecap: 'ADRES E-MAIL',
    AppStrings.youremailaddress: 'Twój adres e-mail',
    AppStrings.gendercap: 'PŁEĆ',
    AppStrings.male: 'Mężczyzna',
    AppStrings.female: 'Kobieta',
    AppStrings.bio: 'Bio',
    AppStrings.tellusmoreaboutyou: 'Powiedz nam więcej o sobie',
    AppStrings.socialprofilelinks: 'Linki do profili społecznościowych',
    AppStrings.citycap: 'MIASTO',
    AppStrings.countrycap: 'KRAJ',
    AppStrings.yourcity: 'Twoje miasto',
    AppStrings.paypalemailaddress: 'Adres e-mail PAY-PAL',
    AppStrings.enteryourpaypalemailaddress: 'Wprowadź swój adres e-mail PAY-PAL',
    AppStrings.security: 'Bezpieczeństwo',
    AppStrings.accountpasswordcap: 'HASŁO KONTA',
    AppStrings.changeyourpasswordandalterothersecurityoptions: 'Zmień swoje hasło i inne opcje zabezpieczeń',
    AppStrings.currentpasswordcap: 'BIEŻĄCE HASŁO',
    AppStrings.currentpassword: 'Bieżące hasło',
    AppStrings.newpassword: 'Nowe hasło',
    AppStrings.confirmpassword: 'Potwierdź hasło',
    AppStrings.repeatnewpassword: 'Powtórz nowe hasło',
    AppStrings.mineightcharacters: 'MIN 8 ZNAKÓW',
    AppStrings.twofactorauthenticationcap: 'AUTORYZACJA DWUCZYNNIKOWA',
    AppStrings.twofactorauthentication: 'Autoryzacja dwuczynnikowa',
    AppStrings.enable: 'Włącz',
    AppStrings.enablecap: 'WŁĄCZ',
    AppStrings.accountclosure: 'ZAMKNIĘCIE KONTA',
    AppStrings.deleteyouraccountanddata: 'Usuń swoje konto i dane',
    AppStrings.areyousureyouwanttodeleteyouraccount: 'Czy na pewno chcesz usunąć swoje konto?',
    AppStrings.deletecap: 'USUŃ',
    AppStrings.settingscap: 'USTAWIENIA',
    AppStrings.emails: 'E-maile',
    AppStrings.billings: 'Fakturowanie',
    AppStrings.profile: 'Profil',
    AppStrings.currentbalancecap: 'BIEŻĄCE SALDO',
    AppStrings.revenuefromshortscap: 'PRZYCHÓD Z FILMÓW KRÓTKICH',
    AppStrings.withdrawcap: 'WYPŁATA',
    AppStrings.coins: 'Monety',
    AppStrings.customamount: 'Własna kwota',
    AppStrings.selectlanguage: "Wybierz język",
    AppStrings.languagecap: "JĘZYK",
    AppStrings.changinglanguage: "Zmienianie języka...",
  };}