import 'all_app_strings.dart';

mixin AppLocalePortugues {
  static const Map<String, dynamic> portugues = {
    AppStrings.somethingwentwrong: 'Algo deu errado',
    AppStrings.nothingtodisplay: 'Nada para exibir...',
    AppStrings.chat: 'Chat',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Vídeo',
    AppStrings.active: 'Ativo',
    AppStrings.inactive: 'Inativo',
    AppStrings.edit: 'Editar',
    AppStrings.yes: 'Sim',
    AppStrings.no: 'Não',
    AppStrings.settings: 'Configurações',
    AppStrings.getcoins: 'Obter Moedas',
    AppStrings.promotions: 'Promoções',
    AppStrings.errorloadingvideo: 'Erro ao carregar o vídeo',
    AppStrings.errorloadingpage: 'Erro ao carregar a página',
    AppStrings.comments: 'Comentários',
    AppStrings.replyto: 'Responder para',
    AppStrings.replytonamecomment: 'Responder ao comentário de Nome',
    AppStrings.replies: 'Respostas',
    AppStrings.post: 'Postar',
    AppStrings.nocommentsyet: 'Nenhum comentário ainda',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Digite uma mensagem',
    AppStrings.nomessagesfound: 'Nenhuma mensagem encontrada',
    AppStrings.failedtoloadthechatrroms: 'Falha ao carregar as salas de bate-papo',
    AppStrings.typeheretheusername: 'Digite aqui o nome de usuário',
    AppStrings.lockscreen: 'Tela de bloqueio',
    AppStrings.logout: 'Sair',
    AppStrings.darkmode: 'Modo escuro',
    AppStrings.followers: 'Seguidores',
    AppStrings.followings: 'Seguindo',
    AppStrings.recentfollowings: 'Seguindo recentemente',
    AppStrings.recentfollowers: 'Seguidores recentes',
    AppStrings.groupnmae: 'Nome do grupo',
    AppStrings.required: '  obrigatório',
    AppStrings.website: 'Website',
    AppStrings.category: 'Categoria',
    AppStrings.validwebsiteurl: 'URL de Website Válida',
    AppStrings.aboutthisgroup: 'Sobre este grupo',
    AppStrings.areyousureyouwanttologout: 'Tem certeza de que deseja sair?',
    AppStrings.writemoreaboutthisgroup: 'Escreva mais sobre este grupo',
    AppStrings.sociallinks: 'Links sociais',
    AppStrings.facebookprofilelink: 'Link do perfil do Facebook',
    AppStrings.xprofilelink: 'Link do perfil do X',
    AppStrings.instagramprofilelink: 'Link do perfil do Instagram',
    AppStrings.tiktokprofilelink: 'Link do perfil do TikTok',
    AppStrings.pinterestprofilelink: 'Link do perfil do Pinterest',
    AppStrings.steamprofilelink: 'Link do perfil do Steam',
    AppStrings.linkedInprofilelink: 'Link do perfil do LinkedIn',
    AppStrings.selectprivacy: 'Selecionar privacidade',
    AppStrings.groupwillbepublic: 'O grupo será público',
    AppStrings.submitgroup: 'Enviar grupo',
    AppStrings.allrequiredfieldsshouldbefilled:
    'Todos os campos obrigatórios devem ser preenchidos',
    AppStrings.errorloadinggroupdata: 'Erro ao carregar os dados do grupo',
    AppStrings.artAndCulture: 'Arte e Cultura',
    AppStrings.scienceAndTechnology: 'Ciência e Tecnologia',
    AppStrings.sport: 'Esporte',
    AppStrings.music: 'Música',
    AppStrings.gastronomy: 'Gastronomia',
    AppStrings.fashionAndStyle: 'Moda e Estilo',
    AppStrings.travelAndPlaces: 'Viagens e Lugares',
    AppStrings.education: 'Educação',
    AppStrings.career: 'Carreira',
    AppStrings.businessAndFinance: 'Negócios e Finanças',
    AppStrings.entertainment: 'Entretenimento',
    AppStrings.environmentAndEcology: 'Meio Ambiente e Ecologia',
    AppStrings.agricultureAndHorticulture: 'Agricultura e Horticultura',
    AppStrings.languagesAndCommunication: 'Línguas e Comunicação',
    AppStrings.technologyAndDigital: 'Tecnologia e Digital',
    AppStrings.architectureAndDesign: 'Arquitetura e Design',
    AppStrings.mediaAndJournalism: 'Mídia e Jornalismo',
    AppStrings.buyAndSell: 'Comprar e Vender',
    AppStrings.selectacategory: 'Selecione uma categoria',
    AppStrings.groupprofilepicture: 'Foto de perfil do grupo',
    AppStrings.selectaimage: 'Selecione uma imagem',
    AppStrings.groupcoverpicture: 'Foto de capa do grupo',
    AppStrings.createpost: 'Criar Postagem',
    AppStrings.writesomething: 'Escreva algo...',
    AppStrings.createapoll: 'Criar uma Enquete',
    AppStrings.pollquestion: 'Pergunta da Enquete',
    AppStrings.polloption: 'Opção da Enquete',
    AppStrings.addoption: '+ Adicionar Opção',
    AppStrings.checkin: 'Check-In',
    AppStrings.current: 'Atual',
    AppStrings.customLocation: 'Localização personalizada',
    AppStrings.onlyforclosefriend: 'Somente para amigos próximos?',
    AppStrings.newsfeed: 'Feed de Notícias',
    AppStrings.story: 'História',
    AppStrings.contentmustbefilled: 'O conteúdo deve ser preenchido',
    AppStrings.polloptions: 'Opções da Enquete:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions:
    'A enquete deve ter uma pergunta e pelo menos duas opções',
    AppStrings.firstofallselectanimage: 'Primeiro, selecione uma imagem',
    AppStrings.browseondevice: 'Procurar no dispositivo',
    AppStrings.joinedgroup: 'Grupo Participado',
    AppStrings.leavegroupsuccessfully: 'Saída do grupo com sucesso',
    AppStrings.joingroup: 'Participar do Grupo',
    AppStrings.groupjoinedsuccessfully: 'Grupo Participado com Sucesso',
    AppStrings.postdeletedsuccessfully: 'Postagem excluída com sucesso',
    AppStrings.deleteallusersposts: 'Excluir todas as postagens do usuário',
    AppStrings.deletealluserscomments: 'Excluir todos os comentários do usuário',
    AppStrings.deleteposts: 'Excluir postagens',
    AppStrings.deletecomments: 'Excluir comentários',
    AppStrings.removethisuser: 'Remover este usuário',
    AppStrings.delete: 'Excluir',
    AppStrings.editmemberdetails: 'EDITAR DETALHES DO MEMBRO',
    AppStrings.availableroles: 'Funções Disponíveis',
    AppStrings.groupmanger: 'Gerente de Grupo',
    AppStrings.pagemanger: 'Gerente de Página',
    AppStrings.pagemangerdescription:
    'alterar detalhes da página, alterar membros da página, alterar postagens da página, alterar comentários das postagens da página',
    AppStrings.groupmangerdescription:
    'alterar detalhes do grupo, alterar membros do grupo, alterar postagens do grupo, alterar comentários das postagens do grupo',
    AppStrings.groupmoderatord: 'Moderador do Grupo',
    AppStrings.pagemoderatord: 'Moderador da Página',
    AppStrings.pagemoderatorddescription:
    'alterar postagens da página, alterar comentários das postagens da página',
    AppStrings.groupmoderatorddescription:
    'alterar postagens do grupo, alterar comentários das postagens do grupo',
    AppStrings.none: 'Nenhum',
    AppStrings.availablepermission: 'Permissões Disponíveis',
    AppStrings.altergroupdetails: 'Alterar detalhes do grupo',
    AppStrings.altergroupmembers: 'Alterar membros do grupo',
    AppStrings.altergroupposts: 'Alterar postagens do grupo',
    AppStrings.altergrouppostscomments: 'Alterar comentários das postagens do grupo',
    AppStrings.alterpagedetails: 'Alterar detalhes da página',
    AppStrings.alterpagemembers: 'Alterar membros da página',
    AppStrings.alterpageposts: 'Alterar postagens da página',
    AppStrings.alterpagepostscomments: 'Alterar comentários das postagens da página',
    AppStrings.updateuser: 'Atualizar Usuário',
    AppStrings.editgroup: 'Editar Grupo',
    AppStrings.editpage: 'Editar Página',
    AppStrings.deletegroup: 'Excluir Grupo',
    AppStrings.deletepage: 'Excluir Página',
    AppStrings.groupmembers: 'Membros do Grupo',
    AppStrings.pagemembers: 'Membros da Página',
    AppStrings.report: 'Relatar',
    AppStrings.areyousureyouwanttodeletegroup:
    'Você tem certeza de que deseja excluir o grupo?',
    AppStrings.areyousureyouwanttodeletepage:
    'Você tem certeza de que deseja excluir a página?',
    AppStrings.youremailisnotverified: 'Seu e-mail não está verificado',
    AppStrings.unauthenticated: 'Não autenticado',
    AppStrings.failedtodeletepost: 'Falha ao excluir postagem',
    AppStrings.addingapost: 'Adicionando uma postagem',
    AppStrings.golive: 'Transmitir ao Vivo',
    AppStrings.location: 'Localização',
    AppStrings.timestamp: 'Data e Hora',
    AppStrings.votes: 'Votos',
    AppStrings.short: 'Curto',
    AppStrings.reply: 'Responder',
    AppStrings.shortvideopost: 'Postagem de vídeo curto',
    AppStrings.shares: 'Compartilhamentos',
    AppStrings.share: 'Compartilhar',
    AppStrings.comment: 'Comentar',
    AppStrings.hidecomments: 'Ocultar Comentários',
    AppStrings.viewmorecomments: 'Ver Mais Comentários',
    AppStrings.replytonamepost: 'Responder à postagem de nome',
    AppStrings.name: 'Nome',
    AppStrings.onedayago: '1 dia atrás',
    AppStrings.promote: 'Promover',
    AppStrings.increaseyourpopularity: 'Aumente sua popularidade',
    AppStrings.allocatecoinsforpromotions: 'Alocar moedas para promoções',
    AppStrings.like: 'Curtir',
    AppStrings.viewpost: 'Visualizar Postagem',
    AppStrings.replypost: 'Responder à Postagem',
    AppStrings.submitanewpost: 'ENVIAR UMA NOVA POSTAGEM',
    AppStrings.submitanewpostdescription:
    'Preencha este relatório com um conteúdo abrangente. Inclua o máximo de detalhes possível, em todas as formas possíveis, para obter uma resolução adequada.',
    AppStrings.content: 'Conteúdo',
    AppStrings.reportnow: 'Relatar Agora',
    AppStrings.failedtoremovelock: 'Falha ao remover bloqueio',
    AppStrings.password: 'Senha',
    AppStrings.unlock: 'Desbloquear',
    AppStrings.thesecredentialsdonotmatch: 'Estas credenciais não correspondem',
    AppStrings.login: 'Entrar',
    AppStrings.signin: 'Entrar',
    AppStrings.signup: 'Cadastrar-se',
    AppStrings.email: 'E-Mail',
    AppStrings.rememberme: 'Lembrar-me',
    AppStrings.forgetpassword: 'Esquecer Senha',
    AppStrings.notifications: 'Notificações',
    AppStrings.pages: 'Páginas',
    AppStrings.createnewpage: 'CRIAR NOVA PÁGINA',
    AppStrings.members: 'Membros',
    AppStrings.creators: 'Criadores',
    AppStrings.page: 'Página',
    AppStrings.submitpage: 'Enviar Página',
    AppStrings.aboutthispage: 'Sobre esta Página',
    AppStrings.writemoreaboutthispage: 'Escreva Mais Sobre esta Página',
    AppStrings.pagename: 'Nome da Página',
    AppStrings.private: 'Privado',
    AppStrings.public: 'Público',
    AppStrings.invite: 'CONVIDAR',
    AppStrings.about: 'SOBRE',
    AppStrings.photos: 'FOTOS',
    AppStrings.events: 'EVENTOS',
    AppStrings.pagewillbepublic: 'A página será pública',
    AppStrings.pagefollowed: 'Página Seguindo',
    AppStrings.joinpage: 'Participar da Página',
    AppStrings.pageleavedsuccessfully: 'Página deixada com sucesso',
    AppStrings.pagejoinedsuccessfully: 'Página unida com sucesso',
    AppStrings.userspage: 'Página do usuário',
    AppStrings.paymentcompletedsuccessfully: 'Pagamento concluído com sucesso!',
    AppStrings.stripepayment: 'Pagamento Stripe',
    AppStrings.myphotos: 'Minhas Fotos',
    AppStrings.recentphotos: 'Fotos Recentes',
    AppStrings.recentposts: 'Publicações Recentes',
    AppStrings.savedshorts: 'Shorts Salvos',
    AppStrings.seeall: 'Ver Tudo',
    AppStrings.groups: 'Grupos',
    AppStrings.errorloadingaccountdetails: 'Erro ao carregar detalhes da conta',
    AppStrings.errorloadingprofile: 'Erro ao carregar perfil',
    AppStrings.timeline: 'Linha do Tempo',
    AppStrings.saved: 'Salvo',
    AppStrings.restricted: 'Restrito',
    AppStrings.blocked: 'Bloqueado',
    AppStrings.register: 'Registrar',
    AppStrings.date: 'Data',
    AppStrings.find: 'Encontrar',
    AppStrings.users: 'Usuários',
    AppStrings.status: 'Status',
    AppStrings.open: 'Aberto',
    AppStrings.closed: 'Fechado',
    AppStrings.title: 'Título',
    AppStrings.edittickets: 'Editar tickets',
    AppStrings.postareply: 'Postar uma resposta',
    AppStrings.createdat: 'Criado em',
    AppStrings.lastreplyby: 'Última resposta por',
    AppStrings.repliesintotal: 'Respostas no total',
    AppStrings.supportTickets: 'Tickets de Suporte',
    AppStrings.ticketsummary: 'Resumo do Ticket',
    AppStrings.availableactions: 'Ações Disponíveis',
    AppStrings.retypepassword: 'Redigitar Senha',
    AppStrings.yourname: 'Seu Nome',
    AppStrings.selectyourcountry: 'Selecione Seu País',
    AppStrings.username: 'Nome de Usuário',
    AppStrings.searchby: 'Buscar Por',
    AppStrings.searchresults: 'Resultados da Busca',
    AppStrings.searchpeoplegrouporpage: 'Buscar Pessoas, Grupos ou Páginas',
    AppStrings.followaddedsuccessfully: 'Seguido com sucesso',
    AppStrings.followremovedsuccessfully: 'Seguir removido com sucesso',
    AppStrings.pleaseverifyyuouremail: 'Por favor, verifique seu e-mail',
    AppStrings.verifyyouraccount: 'Verifique sua conta',
    AppStrings.sendverificationlink: 'Enviar Link de Verificação',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
    'Se você já recebeu um link ou se tem uma conta, faça login agora',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere:
    'Se você não recebeu um link, clique aqui',
    AppStrings.videos: 'Vídeos',
    AppStrings.videoselected: 'Vídeo Selecionado!',
    AppStrings.donate: 'Doar',
    AppStrings.recentvideos: 'Vídeos Recentes',
    AppStrings.firstofallselectvideo: 'Primeiro, selecione um vídeo',
    AppStrings.shortdescriprtiontags: 'Descrição Curta, #tags',
    AppStrings.postshort: '↑ Postar short',
    AppStrings.pleaseselectavideofile: 'Por favor, selecione um arquivo de vídeo',
    AppStrings.donations: 'Doações',
    AppStrings.topdonations: 'Principais Doações',
    AppStrings.helptheshortcreator: 'Ajude o criador do short.',
    AppStrings.sharethispostto: 'Compartilhar esta postagem em',
    AppStrings.copylink: 'Copiar Link',
    AppStrings.selectanuser: 'SELECIONE UM USUÁRIO',
    AppStrings.user111: 'usuário111',
    AppStrings.sharenow: 'Compartilhar Agora',
    AppStrings.reopenticket: 'Reabrir ticket',
    AppStrings.closeticket: 'Fechar ticket',
    AppStrings.supportsticket: 'Tickets de suporte',
    AppStrings.totalticket: 'TOTAL DE TICKETS',
    AppStrings.solvedticket: 'TICKETS RESOLVIDOS',
    AppStrings.openedissues: 'PROBLEMAS ABERTOS',
    AppStrings.sendemail: 'Enviar e-mail',
    AppStrings.support: 'Suporte',
    AppStrings.openticket: 'Abrir ticket',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
    'Se você prefere entrar em contato por e-mail, envie sua dúvida para:',
    AppStrings
        .ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
    'Se você leu esta linha, parece que seu problema é realmente sério. Por favor, nos informe mais sobre isso, ajudaremos com certeza.',
    AppStrings.createanewsupportticket: 'Criar um novo ticket de suporte',
    AppStrings.newintervention: 'Nova Intervenção',
    AppStrings.interventiontitle: 'Título da Intervenção',
    AppStrings.typeherethetitle: 'Digite aqui o título',
    AppStrings.submitticket: 'Enviar ticket',
    AppStrings.submitcomment: 'Enviar comentário',
    AppStrings.contentmustnotbelessthentencharacters:
    'O conteúdo deve ter pelo menos 10 caracteres',
    AppStrings.completeinterventiontitle:
    'Descreva esta intervenção com conteúdo abrangente. Inclua o máximo de detalhes possível para obter uma resolução adequada.',
    AppStrings.updatecomment: 'Atualizar comentário',
    AppStrings.updatethereply: 'Atualizar a resposta',
    AppStrings.commentcontent:
    'Descreva esta resposta com conteúdo abrangente. Inclua o máximo de detalhes possível para obter uma resolução adequada.',
    AppStrings.thereisopeninterventionticketcloseitfirst:
    'Há um ticket de intervenção aberto, feche-o primeiro.',
    AppStrings.addanewcomment: 'Adicionar um novo comentário',
    AppStrings.billingarea: 'Área de Cobrança',
    AppStrings.billingareacap: 'ÁREA DE COBRANÇA',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount:
    'Veja transações e adicione mais moedas à sua conta',
    AppStrings.topup: 'RECARREGAR',
    AppStrings.gotopayment: 'Ir para o pagamento',
    AppStrings.paymentfailed: 'Pagamento falhou',
    AppStrings.pleaseselectanamount: 'Por favor, selecione um valor',
    AppStrings.showlatesttransactionscap: 'MOSTRAR TRANSAÇÕES RECENTES',
    AppStrings.transactionscap: 'TRANSAÇÕES',
    AppStrings.transactionnote:
    'Acompanhe e visualize transações de entrada ou saída e prepare-se para suas próximas conquistas.',
    AppStrings.searchtransactionsby: 'Buscar Transações por',
    AppStrings.searchtransactions: 'Buscar Transações',
    AppStrings.alltransactions: 'Todas as transações',
    AppStrings.transactionname: 'Nome da transação',
    AppStrings.transactionid: 'ID da transação',
    AppStrings.querytobeexecuted: 'Consulta a ser executada',
    AppStrings.settingssaved: 'Configurações Salvas',
    AppStrings.general: 'Geral',
    AppStrings.failedtosavesettigns: 'Falha ao salvar as configurações',
    AppStrings.emailpreferences: 'Preferências de Email',
    AppStrings.emailnotificationscap: 'NOTIFICAÇÕES POR EMAIL',
    AppStrings.savepreferences: 'Salvar Preferências',
    AppStrings.sendmeemailsaboutmyentireactivity:
    'Envie-me e-mails sobre toda a minha atividade',
    AppStrings.selectpushandemailnotificationyouliketorecieve:
    'Selecione notificações por push e e-mail que você gostaria de receber',
    AppStrings.onlysendmerequiredemails: 'Envie apenas e-mails necessários',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges:
    'Nota: Você sempre receberá notificações sobre alterações individuais na conta.',
    AppStrings.enablefollowmecap: 'ATIVAR SEGUIR-ME',
    AppStrings.sendmenotificationscap: 'ENVIAR-ME NOTIFICAÇÕES',
    AppStrings.enablethisifyouwantpeopletofollowyou:
    'Ative isso se quiser que as pessoas te sigam',
    AppStrings.sendmenotificationaboutmyfriendlike:
    'Envie-me notificações sobre o que meus amigos curtiram',
    AppStrings.shareormessageme: 'Compartilhar ou me enviar mensagens.',
    AppStrings.hideyourprofilefromsearchengine:
    'Ocultar seu perfil dos mecanismos de busca',
    AppStrings.searchprivacycap: 'PRIVACIDADE DE BUSCA',
    AppStrings.hidegendercap: 'OCULTAR GÊNERO',
    AppStrings.hideagecap: 'OCULTAR IDADE',
    AppStrings.hidelocationcap: 'OCULTAR LOCALIZAÇÃO',
    AppStrings.profilecap: 'PERFIL',
    AppStrings.editprofilecap: 'EDITAR PERFIL',
    AppStrings.changecap: 'ALTERAR',
    AppStrings.displaynamecap: 'NOME EXIBIDO',
    AppStrings.peopleongenixwillgettoknowbybelowinfo:
    'As pessoas no Genix conhecerão você pelas informações abaixo',
    AppStrings.showingname: 'Exibindo nome',
    AppStrings.usernamecap: 'NOME DE USUÁRIO',
    AppStrings.emailaddressecap: 'ENDEREÇO DE EMAIL',
    AppStrings.youremailaddress: 'Seu endereço de email',
    AppStrings.gendercap: 'GÊNERO',
    AppStrings.male: 'Masculino',
    AppStrings.female: 'Feminino',
    AppStrings.bio: 'Bio',
    AppStrings.tellusmoreaboutyou: 'Conte-nos mais sobre você',
    AppStrings.socialprofilelinks: 'Links de Perfil Social',
    AppStrings.citycap: 'CIDADE',
    AppStrings.countrycap: 'PAÍS',
    AppStrings.yourcity: 'Sua cidade',
    AppStrings.paypalemailaddress: 'Endereço de Email do PAY-PAL',
    AppStrings.enteryourpaypalemailaddress: 'Insira seu endereço de email do PAY-PAL',
    AppStrings.security: 'Segurança',
    AppStrings.accountpasswordcap: 'SENHA DA CONTA',
    AppStrings.changeyourpasswordandalterothersecurityoptions:
    'Altere sua senha e modifique outras opções de segurança',
    AppStrings.currentpasswordcap: 'SENHA ATUAL',
    AppStrings.currentpassword: 'Senha Atual',
    AppStrings.newpassword: 'Nova Senha',
    AppStrings.confirmpassword: 'Confirmar Senha',
    AppStrings.repeatnewpassword: 'Repetir Nova Senha',
    AppStrings.mineightcharacters: 'MÍNIMO 8 CARACTERES',
    AppStrings.twofactorauthenticationcap: 'AUTENTICAÇÃO DE DOIS FATORES',
    AppStrings.twofactorauthentication: 'Autenticação de dois fatores',
    AppStrings.enable: 'Ativar',
    AppStrings.enablecap: 'ATIVAR',
    AppStrings.accountclosure: 'Encerramento de Conta',
    AppStrings.deleteyouraccountanddata: 'Excluir Sua Conta e Dados',
    AppStrings.areyousureyouwanttodeleteyouraccount:
    'Tem certeza de que deseja excluir sua conta?',
    AppStrings.deletecap: 'EXCLUIR',
    AppStrings.settingscap: 'CONFIGURAÇÕES',
    AppStrings.emails: 'Emails',
    AppStrings.billings: 'Cobranças',
    AppStrings.profile: 'Perfil',
    AppStrings.currentbalancecap: 'SALDO ATUAL',
    AppStrings.revenuefromshortscap: 'RECEITA DE SHORTS',
    AppStrings.withdrawcap: 'SACAR',
    AppStrings.coins: 'Moedas',
    AppStrings.customamount: 'Valor personalizado',
    AppStrings.selectlanguage: "Selecionar idioma",
    AppStrings.languagecap: "IDIOMA",
    AppStrings.changinglanguage: "Alterando idioma...",
  };}