import 'all_app_strings.dart';

mixin AppLocaleRomanina {
  static const Map<String, dynamic> romanian = {
    AppStrings.somethingwentwrong: 'Ceva nu a mers bine',
    AppStrings.nothingtodisplay: "Nimic de afișat...",
    AppStrings.chat: 'Chat',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Video',
    AppStrings.active: 'Activ',
    AppStrings.inactive: 'Inactiv',
    AppStrings.edit: 'Editează',
    AppStrings.yes: 'Da',
    AppStrings.no: 'Nu',
    AppStrings.settings: 'Setări',
    AppStrings.getcoins: 'Obține monede',
    AppStrings.promotions: 'Promoții',
    AppStrings.errorloadingvideo: "Eroare la încărcarea videoclipului",
    AppStrings.errorloadingpage: "Eroare la încărcarea paginii",
    AppStrings.comments: 'Comentarii',
    AppStrings.replyto: 'Răspunde la',
    AppStrings.replytonamecomment: 'Răspunde la Comentariul lui Nume',
    AppStrings.replies: 'Răspunsuri',
    AppStrings.post: 'Postează',
    AppStrings.nocommentsyet: 'Niciun comentariu încă',
    AppStrings.hommeeeeee: 'Acasă',
    AppStrings.typeamessage: 'Tastează un mesaj',
    AppStrings.nomessagesfound: "Niciun mesaj găsit",
    AppStrings.failedtoloadthechatrroms: "Nu s-au putut încărca camerele de chat",
    AppStrings.typeheretheusername: 'Tastează aici numele utilizatorului',
    AppStrings.lockscreen: 'Blocare ecran',
    AppStrings.logout: 'Deconectare',
    AppStrings.darkmode: 'Mod întunecat',
    AppStrings.followers: 'Urmăritori',
    AppStrings.followings: 'Persoane urmărite',
    AppStrings.recentfollowings: 'Persoane urmărite recent',
    AppStrings.recentfollowers: 'Urmăritori recenți',
    AppStrings.groupnmae: 'Nume Grup',
    AppStrings.required: '  obligatoriu',
    AppStrings.website: 'Site web',
    AppStrings.category: 'Categorie',
    AppStrings.validwebsiteurl: 'URL valid pentru site',
    AppStrings.aboutthisgroup: 'Despre acest grup',
    AppStrings.areyousureyouwanttologout: 'Ești sigur că vrei să te deconectezi?',
    AppStrings.writemoreaboutthisgroup: 'Scrie mai multe despre acest grup',
    AppStrings.sociallinks: 'Linkuri sociale',
    AppStrings.facebookprofilelink: 'Link profil Facebook',
    AppStrings.xprofilelink: 'Link profil X',
    AppStrings.instagramprofilelink: 'Link profil Instagram',
    AppStrings.tiktokprofilelink: 'Link profil TikTok',
    AppStrings.pinterestprofilelink: 'Link profil Pinterest',
    AppStrings.steamprofilelink: 'Link profil Steam',
    AppStrings.linkedInprofilelink: 'Link profil LinkedIn',
    AppStrings.selectprivacy: 'Selectează confidențialitate',
    AppStrings.groupwillbepublic: 'Grupul va fi public',
    AppStrings.submitgroup: 'Trimite grupul',
    AppStrings.allrequiredfieldsshouldbefilled: 'Toate câmpurile obligatorii trebuie completate',
    AppStrings.errorloadinggroupdata: 'Eroare la încărcarea datelor grupului',
    AppStrings.artAndCulture: 'Artă și Cultură',
    AppStrings.scienceAndTechnology: 'Știință și Tehnologie',
    AppStrings.sport: 'Sport',
    AppStrings.music: 'Muzică',
    AppStrings.gastronomy: 'Gastronomie',
    AppStrings.fashionAndStyle: 'Modă și Stil',
    AppStrings.travelAndPlaces: 'Călătorii și Locuri',
    AppStrings.education: 'Educație',
    AppStrings.career: 'Carieră',
    AppStrings.businessAndFinance: 'Afaceri și Finanțe',
    AppStrings.entertainment: 'Divertisment',
    AppStrings.environmentAndEcology: 'Mediu și Ecologie',
    AppStrings.agricultureAndHorticulture: 'Agricultură și Horticultură',
    AppStrings.languagesAndCommunication: 'Limbi și Comunicare',
    AppStrings.technologyAndDigital: 'Tehnologie și Digital',
    AppStrings.architectureAndDesign: 'Arhitectură și Design',
    AppStrings.mediaAndJournalism: 'Media și Jurnalism',
    AppStrings.buyAndSell: 'Cumpărături și Vânzări',
    AppStrings.selectacategory: 'Selectează o categorie',
    AppStrings.groupprofilepicture: 'Poză de profil a grupului',
    AppStrings.selectaimage: 'Selectează o imagine',
    AppStrings.groupcoverpicture: 'Poză de copertă a grupului',
    AppStrings.createpost: 'Creează Postare',
    AppStrings.writesomething: 'Scrie ceva...',
    AppStrings.createapoll: 'Creează un Sondaj',
    AppStrings.pollquestion: 'Întrebarea sondajului',
    AppStrings.polloption: 'Opțiune sondaj',
    AppStrings.addoption: '+ Adaugă opțiune',
    AppStrings.checkin: 'Check-in',
    AppStrings.current: 'Curent',
    AppStrings.customLocation: 'Locație personalizată',
    AppStrings.onlyforclosefriend: 'Doar pentru prieteni apropiați?',
    AppStrings.newsfeed: 'Flux de știri',
    AppStrings.story: 'Poveste',
    AppStrings.contentmustbefilled: 'Conținutul trebuie completat',
    AppStrings.polloptions: 'Opțiuni sondaj:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions: 'Sondajul trebuie să aibă o întrebare și cel puțin două opțiuni',
    AppStrings.firstofallselectanimage: 'Mai întâi, selectați o imagine',
    AppStrings.browseondevice: 'Răsfoiește pe dispozitiv',
    AppStrings.joinedgroup: 'Te-ai alăturat grupului',
    AppStrings.leavegroupsuccessfully: 'Ai părăsit grupul cu succes',
    AppStrings.joingroup: 'Alătură-te grupului',
    AppStrings.groupjoinedsuccessfully: 'Te-ai alăturat grupului cu succes',
    AppStrings.postdeletedsuccessfully: 'Postarea a fost ștearsă cu succes',
    AppStrings.deleteallusersposts: 'Șterge toate postările utilizatorului',
    AppStrings.deletealluserscomments: 'Șterge toate comentariile utilizatorului',
    AppStrings.deleteposts: 'Șterge postările',
    AppStrings.deletecomments: 'Șterge comentariile',
    AppStrings.removethisuser: 'Elimină acest utilizator',
    AppStrings.delete: 'Șterge',
    AppStrings.editmemberdetails: 'EDITEAZĂ DETALIILE MEMBRULUI',
    AppStrings.availableroles: 'Roluri disponibile',
    AppStrings.groupmanger: 'Manager Grup',
    AppStrings.pagemanger: 'Manager Pagină',
    AppStrings.pagemangerdescription:
    'modifică detalii pagină, modifică membri pagină, modifică postări pagină, modifică comentarii postări pagină',
    AppStrings.groupmangerdescription:
    'modifică detalii grup, modifică membri grup, modifică postări grup, modifică comentarii postări grup',
    AppStrings.groupmoderatord: 'Moderator Grup',
    AppStrings.pagemoderatord: 'Moderator Pagină',
    AppStrings.pagemoderatorddescription:
    'modifică postări pagină, modifică comentarii postări pagină',
    AppStrings.groupmoderatorddescription:
    'modifică postări grup, modifică comentarii postări grup',
    AppStrings.none: 'Niciunul',
    AppStrings.availablepermission: 'Permisiuni disponibile',
    AppStrings.altergroupdetails: 'Modifică detalii grup',
    AppStrings.altergroupmembers: 'Modifică membri grup',
    AppStrings.altergroupposts: 'Modifică postări grup',
    AppStrings.altergrouppostscomments: 'Modifică comentarii postări grup',
    AppStrings.alterpagedetails: 'Modifică detalii pagină',
    AppStrings.alterpagemembers: 'Modifică membri pagină',
    AppStrings.alterpageposts: 'Modifică postări pagină',
    AppStrings.alterpagepostscomments: 'Modifică comentarii postări pagină',
    AppStrings.updateuser: 'Actualizează utilizator',
    AppStrings.editgroup: 'Editează Grup',
    AppStrings.editpage: 'Editează Pagină',
    AppStrings.deletegroup: 'Șterge Grup',
    AppStrings.deletepage: 'Șterge Pagină',
    AppStrings.groupmembers: 'Membri Grup',
    AppStrings.pagemembers: 'Membri Pagină',
    AppStrings.report: 'Raportează',
    AppStrings.areyousureyouwanttodeletegroup:
    'Ești sigur că vrei să ștergi grupul?',
    AppStrings.areyousureyouwanttodeletepage:
    'Ești sigur că vrei să ștergi pagina?',
    AppStrings.youremailisnotverified: 'Email-ul tău nu este verificat',
    AppStrings.unauthenticated: 'Neautentificat',
    AppStrings.failedtodeletepost: 'Eroare la ștergerea postării',
    AppStrings.addingapost: 'Adăugare postare',
    AppStrings.golive: 'Transmite live',
    AppStrings.location: 'Locație',
    AppStrings.timestamp: 'Marcaj temporal',
    AppStrings.votes: 'Voturi',
    AppStrings.short: 'Scurt',
    AppStrings.reply: 'Răspunde',
    AppStrings.shortvideopost: 'Postare video scurt',
    AppStrings.shares: 'Distribuiri',
    AppStrings.share: 'Distribuie',
    AppStrings.comment: 'Comentariu',
    AppStrings.hidecomments: 'Ascunde comentarii',
    AppStrings.viewmorecomments: 'Vezi mai multe comentarii',
    AppStrings.replytonamepost: 'Răspunde la postarea lui {name}',
    AppStrings.name: 'Nume',
    AppStrings.onedayago: 'Acum 1 zi',
    AppStrings.promote: 'Promovează',
    AppStrings.increaseyourpopularity: 'Crește-ți popularitatea',
    AppStrings.allocatecoinsforpromotions: 'Alocă monede pentru promoții',
    AppStrings.like: 'Apreciază',
    AppStrings.viewpost: 'Vezi postarea',
    AppStrings.replypost: 'Răspunde la postare',
    AppStrings.submitanewpost: 'TRIMITE O POSTARE NOUĂ',
    AppStrings.submitanewpostdescription:
    'Completează acest raport cu un conținut detaliat. Include cât mai multe detalii posibil pentru a obține o soluție adecvată.',
    AppStrings.content: 'Conținut',
    AppStrings.reportnow: 'Raportează acum',
    AppStrings.failedtoremovelock: 'Eroare la eliminarea blocajului',
    AppStrings.password: 'Parolă',
    AppStrings.unlock: 'Deblochează',
    AppStrings.thesecredentialsdonotmatch: 'Aceste date nu se potrivesc',
    AppStrings.login: 'Autentificare',
    AppStrings.signin: 'Intră',
    AppStrings.signup: 'Înregistrare',
    AppStrings.email: 'E-mail',
    AppStrings.rememberme: 'Ține-mă minte',
    AppStrings.forgetpassword: 'Ai uitat parola',
    AppStrings.notifications: 'Notificări',
    AppStrings.pages: 'Pagini',
    AppStrings.createnewpage: 'CREEAZĂ O PAGINĂ NOUĂ',
    AppStrings.members: 'Membri',
    AppStrings.creators: 'Creatori',
    AppStrings.page: 'Pagină',
    AppStrings.submitpage: 'Trimite Pagina',
    AppStrings.aboutthispage: 'Despre această Pagină',
    AppStrings.writemoreaboutthispage: 'Scrie mai multe despre această Pagină',
    AppStrings.pagename: 'Nume Pagină',
    AppStrings.private: 'Privat',
    AppStrings.public: 'Public',
    AppStrings.invite: 'INVITĂ',
    AppStrings.about: 'DESPRE',
    AppStrings.photos: 'FOTOGRAFII',
    AppStrings.events: 'EVENIMENTE',
    AppStrings.pagewillbepublic: 'Pagina va fi publică',
    AppStrings.pagefollowed: 'Pagina Urmărită',
    AppStrings.joinpage: 'Alăturați-vă paginii',
    AppStrings.pageleavedsuccessfully: 'Pagină părăsită cu succes',
    AppStrings.pagejoinedsuccessfully: 'Pagină alăturată cu succes',
    AppStrings.userspage: 'Pagina utilizatorului',
    AppStrings.paymentcompletedsuccessfully: 'Plata finalizată cu succes!',
    AppStrings.stripepayment: 'Plată Stripe',
    AppStrings.myphotos: 'Pozele mele',
    AppStrings.recentphotos: 'Poze recente',
    AppStrings.recentposts: 'Postări recente',
    AppStrings.savedshorts: 'Știri salvate',
    AppStrings.seeall: 'Vezi tot',
    AppStrings.groups: 'Grupuri',
    AppStrings.errorloadingaccountdetails: 'Eroare la încărcarea detaliilor contului',
    AppStrings.errorloadingprofile: 'Eroare la încărcarea profilului',
    AppStrings.timeline: 'Cronologie',
    AppStrings.saved: 'Salvat',
    AppStrings.restricted: 'Restricționat',
    AppStrings.blocked: 'Blocată',
    AppStrings.register: 'Înregistrează-te',
    AppStrings.date: 'Dată',
    AppStrings.find: 'Găsește',
    AppStrings.users: 'Utilizatori',
    AppStrings.status: 'Stare',
    AppStrings.open: 'Deschis',
    AppStrings.closed: 'Închis',
    AppStrings.title: 'Titlu',
    AppStrings.edittickets: 'Editează biletele',
    AppStrings.postareply: 'Postează un răspuns',
    AppStrings.createdat: 'Creat la',
    AppStrings.lastreplyby: 'Ultimul răspuns de',
    AppStrings.repliesintotal: 'Răspunsuri în total',
    AppStrings.supportTickets: 'Bilete de suport',
    AppStrings.ticketsummary: 'Rezumat bilet',
    AppStrings.availableactions: 'Acțiuni disponibile',
    AppStrings.retypepassword: 'Reintroduceți parola',
    AppStrings.yourname: 'Numele tău',
    AppStrings.selectyourcountry: 'Selectează țara ta',
    AppStrings.username: 'Nume utilizator',
    AppStrings.searchby: 'Căutare după',
    AppStrings.searchresults: 'Rezultate căutare',
    AppStrings.searchpeoplegrouporpage: 'Căutare persoane, grupuri sau pagini',
    AppStrings.followaddedsuccessfully: 'Urmărirea adăugată cu succes',
    AppStrings.followremovedsuccessfully: 'Urmărirea eliminată cu succes',
    AppStrings.pleaseverifyyuouremail: 'Vă rugăm să verificați emailul',
    AppStrings.verifyyouraccount: 'Verifică-ți contul',
    AppStrings.sendverificationlink: 'Trimite linkul de verificare',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
    'Dacă ai primit deja un link sau dacă ai un cont, autentifică-te acum',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere:
    'Dacă nu ai primit un link, te rugăm să dai click aici',
    AppStrings.videos: 'Videoclipuri',
    AppStrings.videoselected: 'Videoclip selectat!',
    AppStrings.donate: 'Donează',
    AppStrings.recentvideos: 'Videoclipuri recente',
    AppStrings.firstofallselectvideo: 'În primul rând, selectează un videoclip',
    AppStrings.shortdescriprtiontags: 'Scurtă descriere, #etichete',
    AppStrings.postshort: '↑ Postează un scurt',
    AppStrings.pleaseselectavideofile: 'Te rugăm să selectezi un fișier video',
    AppStrings.donations: 'Donații',
    AppStrings.topdonations: 'Cele mai mari donații',
    AppStrings.helptheshortcreator: 'Ajută creatorul de scurtmetraje.',
    AppStrings.sharethispostto: 'Distribuie această postare către',
    AppStrings.copylink: 'Copiază linkul',
    AppStrings.selectanuser: 'SELECTEAZĂ UN UTILIZATOR',
    AppStrings.user111: 'utilizator111',
    AppStrings.sharenow: 'Distribuie acum',
    AppStrings.reopenticket: 'Redeschide biletul',
    AppStrings.closeticket: 'Închide biletul',
    AppStrings.supportsticket: 'Bilet de suport',
    AppStrings.totalticket: 'TOTAL BILETE',
    AppStrings.solvedticket: 'BILETE SOLUȚIONATE',
    AppStrings.openedissues: 'PROBLEME DESCHISE',
    AppStrings.sendemail: 'Trimite email',
    AppStrings.support: 'Suport',
    AppStrings.openticket: 'Deschide bilet',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
    'Dacă preferi să ne contactezi prin email, te rugăm să ne trimiti solicitarea ta la:',
    AppStrings
        .ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
    'Dacă ai citit această linie, se pare că problema ta este foarte serioasă... te rugăm să ne spui mai multe despre asta, te vom ajuta cu siguranță.',
    AppStrings.createanewsupportticket: 'Creează un nou bilet de suport',
    AppStrings.newintervention: 'Nouă intervenție',
    AppStrings.interventiontitle: 'Titlul intervenției',
    AppStrings.typeherethetitle: 'Scrie titlul aici',
    AppStrings.submitticket: 'Trimite bilet',
    AppStrings.submitcomment: 'Trimite comentariu',
    AppStrings.contentmustnotbelessthentencharacters:
    'Conținutul nu trebuie să fie mai scurt de 10 caractere',
    AppStrings.completeinterventiontitle:
    'Completează această intervenție cu un conținut detaliat. Te rugăm să incluzi cât mai multe informații, în toate formele posibile, pentru a obține o soluție adecvată.',
    AppStrings.updatecomment: 'Actualizează comentariul',
    AppStrings.updatethereply: 'Actualizează răspunsul',
    AppStrings.commentcontent:
    'Completează acest răspuns cu un conținut detaliat. Te rugăm să incluzi cât mai multe informații, în toate formele posibile, pentru a obține o soluție adecvată.',
    AppStrings.thereisopeninterventionticketcloseitfirst:
    'Există un bilet de intervenție deschis, te rugăm să-l închizi mai întâi.',
    AppStrings.addanewcomment: 'Adaugă un comentariu nou',
    AppStrings.billingarea: 'Zona de facturare',
    AppStrings.billingareacap: 'ZONA DE FACTURARE',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount:
    'Căutare tranzacții și adăugare mai multe monede în contul tău',
    AppStrings.topup: 'REÎNCARCARE',
    AppStrings.gotopayment: 'Du-te la plată',
    AppStrings.paymentfailed: 'Plata a eșuat',
    AppStrings.pleaseselectanamount: 'Te rugăm să selectezi o sumă',
    AppStrings.showlatesttransactionscap: 'Afișează cele mai recente tranzacții',
    AppStrings.transactionscap: 'TRANZACȚII',
    AppStrings.transactionnote: 'Urmărește și vizualizează tranzacțiile intrate sau ieșite și pregătește-te pentru următoarele realizări.',
    AppStrings.searchtransactionsby: 'Căutare tranzacții după',
    AppStrings.searchtransactions: 'Căutare tranzacții',
    AppStrings.alltransactions: 'Toate tranzacțiile',
    AppStrings.transactionname: 'Numele tranzacției',
    AppStrings.transactionid: 'ID-ul tranzacției',
    AppStrings.querytobeexecuted: 'Interogare de executat',
    AppStrings.settingssaved: 'Setările au fost salvate',
    AppStrings.general: 'General',
    AppStrings.failedtosavesettigns: 'Eșec la salvarea setărilor',
    AppStrings.emailpreferences: 'Preferințe e-mail',
    AppStrings.emailnotificationscap: 'NOTIFICĂRI PE E-MAIL',
    AppStrings.savepreferences: 'Salvează preferințele',
    AppStrings.sendmeemailsaboutmyentireactivity: 'Trimite-mi e-mailuri despre întreaga mea activitate',
    AppStrings.selectpushandemailnotificationyouliketorecieve: 'Selectează notificările push și pe e-mail pe care vrei să le primești',
    AppStrings.onlysendmerequiredemails: 'Trimite-mi doar e-mailurile necesare',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges: 'Notă: Vei primi întotdeauna notificări pentru schimbările individuale ale contului.',
    AppStrings.enablefollowmecap: 'ACTIVEAZĂ URMEAZĂ-MĂ',
    AppStrings.sendmenotificationscap: 'TRIMITE-MI NOTIFICĂRI',
    AppStrings.enablethisifyouwantpeopletofollowyou: 'Activează asta dacă vrei ca oamenii să te urmeze',
    AppStrings.sendmenotificationaboutmyfriendlike: 'Trimite-mi notificări despre aprecierile prietenilor mei',
    AppStrings.shareormessageme: 'Împărtășește sau trimite-mi un mesaj',
    AppStrings.hideyourprofilefromsearchengine: 'Ascunde-ți profilul de la motoarele de căutare',
    AppStrings.searchprivacycap: 'CONFIDENȚIALITATEA CĂUTĂRILOR',
    AppStrings.hidegendercap: 'ASCUNDE GENUL',
    AppStrings.hideagecap: 'ASCUNDE VÂRSTA',
    AppStrings.hidelocationcap: 'ASCUNDE LOKAȚIA',
    AppStrings.profilecap: 'PROFIL',
    AppStrings.editprofilecap: 'EDITEAZĂ PROFILUL',
    AppStrings.changecap: 'SCHIMBĂ',
    AppStrings.displaynamecap: 'NUME AFIȘAT',
    AppStrings.peopleongenixwillgettoknowbybelowinfo: 'Oamenii de pe Genix vor afla despre tine din informațiile de mai jos',
    AppStrings.showingname: 'Nume afișat',
    AppStrings.usernamecap: 'NUME DE UTILIZATOR',
    AppStrings.emailaddressecap: 'ADRESĂ DE E-MAIL',
    AppStrings.youremailaddress: 'Adresa ta de e-mail',
    AppStrings.gendercap: 'GEN',
    AppStrings.male: 'Bărbat',
    AppStrings.female: 'Femeie',
    AppStrings.bio: 'Bio',
    AppStrings.tellusmoreaboutyou: 'Spune-ne mai multe despre tine',
    AppStrings.socialprofilelinks: 'Linkuri profil social',
    AppStrings.citycap: 'ORAȘ',
    AppStrings.countrycap: 'ȚARĂ',
    AppStrings.yourcity: 'Orașul tău',
    AppStrings.paypalemailaddress: 'ADRESĂ DE E-MAIL PAYPAL',
    AppStrings.enteryourpaypalemailaddress: 'Introdu adresa ta de e-mail PAYPAL',
    AppStrings.security: 'Securitate',
    AppStrings.accountpasswordcap: 'PAROLĂ CONTA',
    AppStrings.changeyourpasswordandalterothersecurityoptions: 'Schimbă-ți parola și modifică alte opțiuni de securitate',
    AppStrings.currentpasswordcap: 'PAROLĂ ACTUALĂ',
    AppStrings.currentpassword: 'Parola actuală',
    AppStrings.newpassword: 'Parola nouă',
    AppStrings.confirmpassword: 'Confirmați parola',
    AppStrings.repeatnewpassword: 'Repetați parola nouă',
    AppStrings.mineightcharacters: 'MINIM 8 CARACTERE',
    AppStrings.twofactorauthenticationcap: 'AUTENTIFICARE PE DOI FACTORI',
    AppStrings.twofactorauthentication: 'Autentificare pe doi factori',
    AppStrings.enable: 'Activează',
    AppStrings.enablecap: 'ACTIVEAZĂ',
    AppStrings.accountclosure: 'Închidere cont',
    AppStrings.deleteyouraccountanddata: 'Șterge-ți contul și datele',
    AppStrings.areyousureyouwanttodeleteyouraccount: 'Ești sigur că vrei să îți ștergi contul?',
    AppStrings.deletecap: 'ȘTERGE',
    AppStrings.settingscap: 'SETĂRI',
    AppStrings.emails: 'E-mailuri',
    AppStrings.billings: 'Facturări',
    AppStrings.profile: 'Profil',
    AppStrings.currentbalancecap: 'BALANȚA ACTUALĂ',
    AppStrings.revenuefromshortscap: 'VENITURI DIN SCURTE',
    AppStrings.withdrawcap: 'RETRAGE',
    AppStrings.coins: 'Monede',
    AppStrings.customamount: 'Sumă personalizată',
    AppStrings.selectlanguage: "Selectați limba",
    AppStrings.languagecap: "LIMBĂ",
    AppStrings.changinglanguage: "Schimbarea limbii...",
  };}