import 'all_app_strings.dart';

mixin AppLocaleSolovene {
  static const Map<String, dynamic> solovene = {
    AppStrings.somethingwentwrong: 'Nekaj je šlo narobe',
    AppStrings.nothingtodisplay: 'Ni ničesar za prikazati...',
    AppStrings.chat: 'Pogovor',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Video',
    AppStrings.active: 'Aktivno',
    AppStrings.inactive: 'Neaktivno',
    AppStrings.edit: 'Uredi',
    AppStrings.yes: 'Da',
    AppStrings.no: 'Ne',
    AppStrings.settings: 'Nastavitve',
    AppStrings.getcoins: 'Pridobi kovance',
    AppStrings.promotions: 'Promocije',
    AppStrings.errorloadingvideo: 'Napaka pri nalaganju videa',
    AppStrings.errorloadingpage: 'Napaka pri nalaganju strani',
    AppStrings.comments: 'Komentarji',
    AppStrings.replyto: 'Odgovori na',
    AppStrings.replytonamecomment: 'Odgovori na ime komentarja',
    AppStrings.replies: 'Odgovori',
    AppStrings.post: 'Objavi',
    AppStrings.nocommentsyet: 'Še ni komentarjev',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Vnesite sporočilo',
    AppStrings.nomessagesfound: 'Ni najdenih sporočil',
    AppStrings.failedtoloadthechatrroms: 'Napaka pri nalaganju klepetalnic',
    AppStrings.typeheretheusername: 'Tukaj vnesite uporabniško ime',
    AppStrings.lockscreen: 'Zakleni zaslon',
    AppStrings.logout: 'Odjava',
    AppStrings.darkmode: 'Temni način',
    AppStrings.followers: 'Spremljevalci',
    AppStrings.followings: 'Spremljanje',
    AppStrings.recentfollowings: 'Nedavne spremljane osebe',
    AppStrings.recentfollowers: 'Nedavni spremljevalci',
    AppStrings.groupnmae: 'Ime skupine',
    AppStrings.required: 'zadetno',
    AppStrings.website: 'Spletna stran',
    AppStrings.category: 'Kategorija',
    AppStrings.validwebsiteurl: 'Veljavna spletna povezava',
    AppStrings.aboutthisgroup: 'O tej skupini',
    AppStrings.areyousureyouwanttologout: 'Ste prepričani, da se želite odjaviti?',
    AppStrings.writemoreaboutthisgroup: 'Napišite več o tej skupini',
    AppStrings.sociallinks: 'Družbeni povezavi',
    AppStrings.facebookprofilelink: 'Povezava do Facebook profila',
    AppStrings.xprofilelink: 'Povezava do X profila',
    AppStrings.instagramprofilelink: 'Povezava do Instagram profila',
    AppStrings.tiktokprofilelink: 'Povezava do Tik Tok profila',
    AppStrings.pinterestprofilelink: 'Povezava do Pinterest profila',
    AppStrings.steamprofilelink: 'Povezava do Steam profila',
    AppStrings.linkedInprofilelink: 'Povezava do LinkedIn profila',
    AppStrings.selectprivacy: 'Izberite zasebnost',
    AppStrings.groupwillbepublic: 'Skupina bo javna',
    AppStrings.submitgroup: 'Oddajte skupino',
    AppStrings.allrequiredfieldsshouldbefilled: 'Vsa obvezna polja morajo biti izpolnjena',
    AppStrings.errorloadinggroupdata: 'Napaka pri nalaganju podatkov skupine',
    AppStrings.artAndCulture: 'Umetnost in kultura',
    AppStrings.scienceAndTechnology: 'Znanost in tehnologija',
    AppStrings.sport: 'Šport',
    AppStrings.music: 'Glasba',
    AppStrings.gastronomy: 'Gastronomija',
    AppStrings.fashionAndStyle: 'Moda in stil',
    AppStrings.travelAndPlaces: 'Potovanja in kraji',
    AppStrings.education: 'Izobraževanje',
    AppStrings.career: 'Kariera',
    AppStrings.businessAndFinance: 'Posel in finance',
    AppStrings.entertainment: 'Zabava',
    AppStrings.environmentAndEcology: 'Okolje in ekologija',
    AppStrings.agricultureAndHorticulture: 'Kmetijstvo in vrtnarjenje',
    AppStrings.languagesAndCommunication: 'Jeziki in komunikacija',
    AppStrings.technologyAndDigital: 'Tehnologija in digitalno',
    AppStrings.architectureAndDesign: 'Arhitektura in oblikovanje',
    AppStrings.mediaAndJournalism: 'Mediji in novinarstvo',
    AppStrings.buyAndSell: 'Nakup in prodaja',
    AppStrings.selectacategory: 'Izberite kategorijo',
    AppStrings.groupprofilepicture: 'Profilna slika skupine',
    AppStrings.selectaimage: 'Izberite sliko',
    AppStrings.groupcoverpicture: 'Slika naslovnice skupine',
    AppStrings.createpost: 'Ustvari objavo',
    AppStrings.writesomething: 'Napiši nekaj...',
    AppStrings.createapoll: 'Ustvari anketo',
    AppStrings.pollquestion: 'Vprašanje ankete',
    AppStrings.polloption: 'Možnost ankete',
    AppStrings.addoption: '+ Dodaj možnost',
    AppStrings.checkin: 'Check in',
    AppStrings.current: 'Trenutno',
    AppStrings.customLocation: 'Po meri lokacija',
    AppStrings.onlyforclosefriend: 'Samo za bližje prijatelje?',
    AppStrings.newsfeed: 'Novice',
    AppStrings.story: 'Zgodba',
    AppStrings.contentmustbefilled: 'Vsebina mora biti izpolnjena',
    AppStrings.polloptions: 'Možnosti ankete:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions: 'Anketa mora imeti vprašanje in vsaj dve možnosti',
    AppStrings.firstofallselectanimage: 'Najprej izberite sliko',
    AppStrings.browseondevice: 'Prebrskajte po napravi',
    AppStrings.joinedgroup: 'Pridružen skupini',
    AppStrings.leavegroupsuccessfully: 'Uspešno zapustite skupino',
    AppStrings.joingroup: 'Pridruži se skupini',
    AppStrings.groupjoinedsuccessfully: 'Skupina uspešno pridružena',
    AppStrings.postdeletedsuccessfully: 'Objava uspešno izbrisana',
    AppStrings.deleteallusersposts: 'Izbriši vse uporabnikove objave',
    AppStrings.deletealluserscomments: 'Izbriši vse uporabnikove komentarje',
    AppStrings.deleteposts: 'Izbriši objave',
    AppStrings.deletecomments: 'Izbriši komentarje',
    AppStrings.removethisuser: 'Odstrani tega uporabnika',
    AppStrings.delete: 'Izbriši',
    AppStrings.editmemberdetails: 'UREDI PODROBNOSTI ČLANA',
    AppStrings.availableroles: 'Razpoložljive vloge',
    AppStrings.groupmanger: 'Upravnik skupine',
    AppStrings.pagemanger: 'Upravnik strani',
    AppStrings.pagemangerdescription: 'spremenite podrobnosti strani, spremenite člane strani, spremenite objave strani, spremenite komentarje objav strani',
    AppStrings.groupmangerdescription: 'spremenite podrobnosti skupine, spremenite člane skupine, spremenite objave skupine, spremenite komentarje objav skupine',
    AppStrings.groupmoderatord: 'Moderator skupine',
    AppStrings.pagemoderatord: 'Moderator strani',
    AppStrings.pagemoderatorddescription: 'spremenite objave strani, spremenite komentarje objav strani',
    AppStrings.groupmoderatorddescription: 'spremenite objave skupine, spremenite komentarje objav skupine',
    AppStrings.none: 'Nič',
    AppStrings.availablepermission: 'Razpoložljivo dovoljenje',
    AppStrings.altergroupdetails: 'Spremenite podrobnosti skupine',
    AppStrings.altergroupmembers: 'Spremenite člane skupine',
    AppStrings.altergroupposts: 'Spremenite objave skupine',
    AppStrings.altergrouppostscomments: 'Spremenite komentarje objav skupine',
    AppStrings.alterpagedetails: 'Spremenite podrobnosti strani',
    AppStrings.alterpagemembers: 'Spremenite člane strani',
    AppStrings.alterpageposts: 'Spremenite objave strani',
    AppStrings.alterpagepostscomments: 'Spremenite komentarje objav strani',
    AppStrings.updateuser: 'Posodobi uporabnika',
    AppStrings.editgroup: 'Uredi skupino',
    AppStrings.editpage: 'Uredi stran',
    AppStrings.deletegroup: 'Izbriši skupino',
    AppStrings.deletepage: 'Izbriši stran',
    AppStrings.groupmembers: 'Člani skupine',
    AppStrings.pagemembers: 'Člani strani',
    AppStrings.report: 'Poročilo',
    AppStrings.areyousureyouwanttodeletegroup: 'Ste prepričani, da želite izbrisati skupino?',
    AppStrings.areyousureyouwanttodeletepage: 'Ste prepričani, da želite izbrisati stran?',
    AppStrings.youremailisnotverified: 'Vaš e-poštni naslov ni preverjen',
    AppStrings.unauthenticated: 'Neavtorizirano',
    AppStrings.failedtodeletepost: 'Napaka pri brisanju objave',
    AppStrings.addingapost: 'dodajanje objave',
    AppStrings.golive: 'Pojdi v živo',
    AppStrings.location: 'Lokacija',
    AppStrings.timestamp: 'Časovni žig',
    AppStrings.votes: 'glasovi',
    AppStrings.short: 'kratko',
    AppStrings.reply: 'odgovori',
    AppStrings.shortvideopost: 'kratka video objava',
    AppStrings.shares: 'Deli',
    AppStrings.share: 'Deli',
    AppStrings.comment: 'komentar',
    AppStrings.hidecomments: 'Skrij komentarje',
    AppStrings.viewmorecomments: 'Poglejte več komentarjev',
    AppStrings.replytonamepost: 'odgovori na ime objave',
    AppStrings.name: 'ime',
    AppStrings.onedayago: 'pred 1 dnem',
    AppStrings.promote: 'Promoviraj',
    AppStrings.increaseyourpopularity: 'Povečajte svojo priljubljenost',
    AppStrings.allocatecoinsforpromotions: 'Dodelite kovance za promocije',
    AppStrings.like: 'Všeč mi je',
    AppStrings.viewpost: 'Ogled objave',
    AppStrings.replypost: 'Odgovori na objavo',
    AppStrings.submitanewpost: 'POŠLJI NOVO OBJAVO',
    AppStrings.submitanewpostdescription: 'To poročilo napolnite s celovitim vsebinam. Prosimo vključite čim več podrobnosti v vseh možnih oblikah, da dobite ustrezno rešitev.',
    AppStrings.content: 'vsebina',
    AppStrings.reportnow: 'Porčaj zdaj',
    AppStrings.failedtoremovelock: 'Napaka pri odstranjevanju zaklepa',
    AppStrings.password: 'Geslo',
    AppStrings.unlock: 'Odkleni',
    AppStrings.thesecredentialsdonotmatch: 'Ti podatki se ne ujemajo',
    AppStrings.login: 'Prijava',
    AppStrings.signin: 'prijava',
    AppStrings.signup: 'registracija',
    AppStrings.email: 'E-pošta',
    AppStrings.rememberme: 'Zapomni si me',
    AppStrings.forgetpassword: 'Pozabljeno geslo',
    AppStrings.notifications: 'Obvestila',
    AppStrings.pages: 'strani',
    AppStrings.createnewpage: 'USTVARI NOVO STRAN',
    AppStrings.members: 'Člani',
    AppStrings.creators: 'Ustvarjalci',
    AppStrings.page: 'Stran',
    AppStrings.submitpage: 'Pošlji stran',
    AppStrings.aboutthispage: 'O tej strani',
    AppStrings.writemoreaboutthispage: 'Napišite več o tej strani',
    AppStrings.pagename: 'Ime strani',
    AppStrings.private: 'zasebno',
    AppStrings.public: 'javno',
    AppStrings.invite: 'POVABI',
    AppStrings.about: 'O',
    AppStrings.photos: 'FOTOGRAFIJE',
    AppStrings.events: 'DOGODKI',
    AppStrings.pagewillbepublic: 'Stran bo javna',
    AppStrings.pagefollowed: 'Stran sledena',
    AppStrings.joinpage: 'Pridruži se strani',
    AppStrings.pageleavedsuccessfully: 'Stran je bila uspešno zapuščena',
    AppStrings.pagejoinedsuccessfully: 'Stran je bila uspešno pridružena',
    AppStrings.userspage: 'Uporabnikova stran',
    AppStrings.paymentcompletedsuccessfully: 'Plačilo je bilo uspešno zaključeno!',
    AppStrings.stripepayment: 'Stripe Plačilo',
    AppStrings.myphotos: 'Moje slike',
    AppStrings.recentphotos: 'Nedavne slike',
    AppStrings.recentposts: 'Nedavni prispevki',
    AppStrings.savedshorts: 'Shranjeni kratki posnetki',
    AppStrings.seeall: 'Poglej vse',
    AppStrings.groups: 'Skupine',
    AppStrings.errorloadingaccountdetails: 'Napaka pri nalaganju podrobnosti računa',
    AppStrings.errorloadingprofile: 'Napaka pri nalaganju profila',
    AppStrings.timeline: 'Časovnica',
    AppStrings.saved: 'Shranjeno',
    AppStrings.restricted: 'Omejeno',
    AppStrings.blocked: 'Blokirano',
    AppStrings.register: 'Registriraj se',
    AppStrings.date: 'Datum',
    AppStrings.find: 'Poišči',
    AppStrings.users: 'Uporabniki',
    AppStrings.status: 'Status',
    AppStrings.open: 'Odprto',
    AppStrings.closed: 'Zaprto',
    AppStrings.title: 'Naslov',
    AppStrings.edittickets: 'Uredi vstopnice',
    AppStrings.postareply: 'Objavi odgovor',
    AppStrings.createdat: 'Ustvarjeno ob',
    AppStrings.lastreplyby: 'Zadnji odgovor s strani',
    AppStrings.repliesintotal: 'Skupaj odgovorov',
    AppStrings.supportTickets: 'Podporne vstopnice',
    AppStrings.ticketsummary: 'Povzetek vstopnice',
    AppStrings.availableactions: 'Na voljo dejanja',
    AppStrings.retypepassword: 'Ponovno vnesite geslo',
    AppStrings.yourname: 'Vaše ime',
    AppStrings.selectyourcountry: 'Izberite svojo državo',
    AppStrings.username: 'Uporabniško ime',
    AppStrings.searchby: 'Išči po',
    AppStrings.searchresults: 'Rezultati iskanja',
    AppStrings.searchpeoplegrouporpage: 'Išči ljudi, skupine ali strani',
    AppStrings.followaddedsuccessfully: 'Sledenje je bilo uspešno dodano',
    AppStrings.followremovedsuccessfully: 'Sledenje je bilo uspešno odstranjeno',
    AppStrings.pleaseverifyyuouremail: 'Prosimo, preverite vaš e-poštni naslov',
    AppStrings.verifyyouraccount: 'Preverite svoj račun',
    AppStrings.sendverificationlink: 'Pošlji povezavo za preverjanje',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow: 'Če ste že prejeli povezavo ali imate račun, se prijavite zdaj',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere: 'Če niste prejeli povezave, kliknite tukaj',
    AppStrings.videos: 'Videi',
    AppStrings.videoselected: 'Video izbran!',
    AppStrings.donate: 'Doniraj',
    AppStrings.recentvideos: 'Nedavni videi',
    AppStrings.firstofallselectvideo: 'Najprej izberite video',
    AppStrings.shortdescriprtiontags: 'Kratek opis, #oznake',
    AppStrings.postshort: '↑ Objavi kratek',
    AppStrings.pleaseselectavideofile: 'Prosimo, izberite video datoteko',
    AppStrings.donations: 'Donacije',
    AppStrings.topdonations: 'Največje donacije',
    AppStrings.helptheshortcreator: 'Pomagajte ustvarjalcu kratkega posnetka.',
    AppStrings.sharethispostto: 'Deli to objavo na',
    AppStrings.copylink: 'Kopiraj povezavo',
    AppStrings.selectanuser: 'Izberite uporabnika',
    AppStrings.user111: 'uporabnik111',
    AppStrings.sharenow: 'Deli zdaj',
    AppStrings.reopenticket: 'Ponovno odpri vstopnico',
    AppStrings.closeticket: 'Zapri vstopnico',
    AppStrings.supportsticket: 'Podporna vstopnica',
    AppStrings.totalticket: 'SKUPAJ VSTOPNIC',
    AppStrings.solvedticket: 'REŠENE VSTOPNICE',
    AppStrings.openedissues: 'ODPRTE TEŽAVE',
    AppStrings.sendemail: 'Pošlji e-pošto',
    AppStrings.support: 'Podpora',
    AppStrings.openticket: 'Odpri vstopnico',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto: 'Če bi želeli stopiti v stik z nami po e-pošti, pošljite svojo poizvedbo na:',
    AppStrings.ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure: 'Če berete to vrstico, izgleda, da je vaša težava resna... prosimo, povejte nam več o tem, zagotovo vam bomo pomagali.',
    AppStrings.createanewsupportticket: 'Ustvari novo podporno vstopnico',
    AppStrings.newintervention: 'Nova intervencija',
    AppStrings.interventiontitle: 'Naslov intervencije',
    AppStrings.typeherethetitle: 'Vnesite naslov tukaj',
    AppStrings.submitticket: 'Pošlji vstopnico',
    AppStrings.submitcomment: 'Pošlji komentar',
    AppStrings.contentmustnotbelessthentencharacters: 'Vsebina ne sme biti krajša od desetih znakov',
    AppStrings.completeinterventiontitle: 'Ta intervencija naj bo čim bolj podrobna. Prosimo, vključite vse podrobnosti, da bomo lahko našli ustrezno rešitev.',
    AppStrings.updatecomment: 'Posodobi komentar',
    AppStrings.updatethereply: 'Posodobi odgovor',
    AppStrings.commentcontent: 'Ta odgovor naj bo čim bolj podroben. Prosimo, vključite vse podrobnosti, da bomo lahko našli ustrezno rešitev.',
    AppStrings.thereisopeninterventionticketcloseitfirst: 'Obstaja odprta intervencijska vstopnica, najprej jo zaprite.',
    AppStrings.addanewcomment: 'Dodajte nov komentar',
    AppStrings.billingarea: 'Območje zaračunavanja',
    AppStrings.billingareacap: 'OBMOČJE ZARAČUNAVANJA',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount: 'Preglejte transakcije in dodajte več kovancev na vaš račun',
    AppStrings.topup: 'DODAJ DENAR',
    AppStrings.gotopayment: 'Pojdi na plačilo',
    AppStrings.paymentfailed: 'Plačilo ni uspelo',
    AppStrings.pleaseselectanamount: 'Prosimo, izberite znesek',
    AppStrings.showlatesttransactionscap: 'Pokaži najnovejše transakcije',
    AppStrings.transactionscap: 'TRANSAKCIJE',
    AppStrings.transactionnote: 'Spremljajte in si oglejte prihodnje ali odhodne transakcije ter se pripravite na svoje naslednje dosežke.',
    AppStrings.searchtransactionsby: 'Išči transakcije po',
    AppStrings.searchtransactions: 'Išči transakcije',
    AppStrings.alltransactions: 'Vse transakcije',
    AppStrings.transactionname: 'Ime transakcije',
    AppStrings.transactionid: 'ID transakcije',
    AppStrings.querytobeexecuted: 'Poizvedba, ki bo izvedena',
    AppStrings.settingssaved: 'Nastavitve shranjene',
    AppStrings.general: 'Splošno',
    AppStrings.failedtosavesettigns: 'Shranjevanje nastavitev ni uspelo',
    AppStrings.emailpreferences: 'Nastavitve e-pošte',
    AppStrings.emailnotificationscap: 'OBVESTILA O E-POŠTI',
    AppStrings.savepreferences: 'Shrani nastavitve',
    AppStrings.sendmeemailsaboutmyentireactivity: 'Pošljite mi e-pošto o moji celotni aktivnosti',
    AppStrings.selectpushandemailnotificationyouliketorecieve: 'Izberite obvestila o potisnih sporočilih in e-pošti, ki jih želite prejemati',
    AppStrings.onlysendmerequiredemails: 'Pošljite mi samo obvezna e-poštna sporočila',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges: 'Opomba: Vedno boste prejeli obvestila o posameznih spremembah računa.',
    AppStrings.enablefollowmecap: 'OMOGOČI SLEDI MI',
    AppStrings.sendmenotificationscap: 'POŠLJITE MI OBVESTILA',
    AppStrings.enablethisifyouwantpeopletofollowyou: 'Omogočite to, če želite, da vas ljudje sledijo',
    AppStrings.sendmenotificationaboutmyfriendlike: 'Pošljite mi obvestilo o všečkih mojih prijateljev',
    AppStrings.shareormessageme: 'Delite ali pošljite sporočilo z mano.',
    AppStrings.hideyourprofilefromsearchengine: 'Skrij svoj profil pred iskalniki',
    AppStrings.searchprivacycap: 'ZAŠČITA ISKANJA',
    AppStrings.hidegendercap: 'SKRIVAJ SPOLOP',
    AppStrings.hideagecap: 'SKRIVAJ STAROST',
    AppStrings.hidelocationcap: 'SKRIVAJ LOKACIJO',
    AppStrings.profilecap: 'PROFIL',
    AppStrings.editprofilecap: 'UREDI PROFIL',
    AppStrings.changecap: 'SPREMENI',
    AppStrings.displaynamecap: 'PRIKAZANO IME',
    AppStrings.peopleongenixwillgettoknowbybelowinfo: 'Ljudje na Genix-u vas bodo spoznali po spodnjih informacijah',
    AppStrings.showingname: 'Prikazano ime',
    AppStrings.usernamecap: 'UPORABNIŠKO IME',
    AppStrings.emailaddressecap: 'E-POŠTNI NASLOV',
    AppStrings.youremailaddress: 'Vaš e-poštni naslov',
    AppStrings.gendercap: 'SPOLOP',
    AppStrings.male: 'Moški',
    AppStrings.female: 'Ženska',
    AppStrings.bio: 'Biografija',
    AppStrings.tellusmoreaboutyou: 'Povej nam več o tebi',
    AppStrings.socialprofilelinks: 'Povezave do družbenih profilov',
    AppStrings.citycap: 'MESTO',
    AppStrings.countrycap: 'DRŽAVA',
    AppStrings.yourcity: 'Vaše mesto',
    AppStrings.paypalemailaddress: 'PAY-PAL e-poštni naslov',
    AppStrings.enteryourpaypalemailaddress: 'Vnesite svoj PAY-PAL e-poštni naslov',
    AppStrings.security: 'Varnost',
    AppStrings.accountpasswordcap: 'GESLO RAČUNA',
    AppStrings.changeyourpasswordandalterothersecurityoptions: 'Spremenite geslo in spremenite druge varnostne možnosti',
    AppStrings.currentpasswordcap: 'OBSTOJEČE GESLO',
    AppStrings.currentpassword: 'Trenutno geslo',
    AppStrings.newpassword: 'Novo geslo',
    AppStrings.confirmpassword: 'Potrdite geslo',
    AppStrings.repeatnewpassword: 'Ponovno vnesite novo geslo',
    AppStrings.mineightcharacters: 'MIN 8 ZNAKOV',
    AppStrings.twofactorauthenticationcap: 'DVOFOTRNA AVTENTIFIKACIJA',
    AppStrings.twofactorauthentication: 'Dvofaktorska avtentifikacija',
    AppStrings.enable: 'Omogoči',
    AppStrings.enablecap: 'OMOGOČI',
    AppStrings.accountclosure: 'Zaprtje računa',
    AppStrings.deleteyouraccountanddata: 'Izbriši svoj račun in podatke',
    AppStrings.areyousureyouwanttodeleteyouraccount: 'Ste prepričani, da želite izbrisati svoj račun?',
    AppStrings.deletecap: 'IZBriši',
    AppStrings.settingscap: 'NASTAVITVE',
    AppStrings.emails: 'E-pošta',
    AppStrings.billings: 'Računanje',
    AppStrings.profile: 'Profil',
    AppStrings.currentbalancecap: 'TRENUTNO STANJE',
    AppStrings.revenuefromshortscap: 'DOHODEK OD KRAJŠIH VIDEO POSNETKOV',
    AppStrings.withdrawcap: 'VZEMI DENAR',
    AppStrings.coins: 'Kovanci',
    AppStrings.customamount: 'Po meri nastavljen znesek',
    AppStrings.selectlanguage: "Izberite jezik",
    AppStrings.languagecap: "JEZIK",
    AppStrings.changinglanguage: "Spreminjanje jezika...",
  };}