import 'all_app_strings.dart';

mixin AppLocaleTurkish {
  static const Map<String, dynamic> turkish = {
    AppStrings.somethingwentwrong: 'Bir şeyler yanlış gitti',
    AppStrings.nothingtodisplay: "Görüntülenecek hiçbir şey yok...",
    AppStrings.chat: 'Sohbet',
    AppStrings.spam: 'Spam',
    AppStrings.video: 'Video',
    AppStrings.active: 'Aktif',
    AppStrings.inactive: 'Pasif',
    AppStrings.edit: 'Düzenle',
    AppStrings.yes: 'Evet',
    AppStrings.no: 'Hayır',
    AppStrings.settings: 'Ayarlar',
    AppStrings.getcoins: 'Jeton Al',
    AppStrings.promotions: 'Promosyonlar',
    AppStrings.errorloadingvideo: "Video yüklenirken hata oluştu",
    AppStrings.errorloadingpage: "Sayfa yüklenirken hata oluştu",
    AppStrings.comments: 'Yorumlar',
    AppStrings.replyto: 'Yanıtla',
    AppStrings.replytonamecomment: 'Yanıtla {name} Yorum',
    AppStrings.replies: 'Yanıtlar',
    AppStrings.post: 'Gönder',
    AppStrings.nocommentsyet: 'Henüz Yorum Yok',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Bir mesaj yazın',
    AppStrings.nomessagesfound: "Mesaj bulunamadı",
    AppStrings.failedtoloadthechatrroms: "Sohbet odaları yüklenemedi",
    AppStrings.typeheretheusername: 'Buraya kullanıcı adını yazın',
    AppStrings.lockscreen: 'Ekran Kilidi',
    AppStrings.logout: 'Çıkış Yap',
    AppStrings.darkmode: 'Karanlık Mod',
    AppStrings.followers: 'Takipçiler',
    AppStrings.followings: 'Takip Edilenler',
    AppStrings.recentfollowings: 'Son Takip Edilenler',
    AppStrings.recentfollowers: 'Son Takipçiler',
    AppStrings.groupnmae: 'Grup Adı',
    AppStrings.required: 'gerekli',
    AppStrings.website: 'Web Sitesi',
    AppStrings.category: 'Kategori',
    AppStrings.validwebsiteurl: 'Geçerli Web Sitesi URL\'si',
    AppStrings.aboutthisgroup: 'Bu Grup Hakkında',
    AppStrings.areyousureyouwanttologout: 'Çıkış yapmak istediğinizden emin misiniz?',
    AppStrings.writemoreaboutthisgroup: 'Bu grup hakkında daha fazla yazın',
    AppStrings.sociallinks: 'Sosyal Bağlantılar',
    AppStrings.facebookprofilelink: 'Facebook Profil Bağlantısı',
    AppStrings.xprofilelink: 'X Profil Bağlantısı',
    AppStrings.instagramprofilelink: 'Instagram Profil Bağlantısı',
    AppStrings.tiktokprofilelink: 'TikTok Profil Bağlantısı',
    AppStrings.pinterestprofilelink: 'Pinterest Profil Bağlantısı',
    AppStrings.steamprofilelink: 'Steam Profil Bağlantısı',
    AppStrings.linkedInprofilelink: 'LinkedIn Profil Bağlantısı',
    AppStrings.selectprivacy: 'Gizliliği Seçin',
    AppStrings.groupwillbepublic: 'Grup herkese açık olacak',
    AppStrings.submitgroup: 'Grubu Gönder',
    AppStrings.allrequiredfieldsshouldbefilled: 'Tüm gerekli alanlar doldurulmalıdır',
    AppStrings.errorloadinggroupdata: 'Grup verileri yüklenirken hata oluştu',
    AppStrings.artAndCulture: 'Sanat ve Kültür',
    AppStrings.scienceAndTechnology: 'Bilim ve Teknoloji',
    AppStrings.sport: 'Spor',
    AppStrings.music: 'Müzik',
    AppStrings.gastronomy: 'Gastronomi',
    AppStrings.fashionAndStyle: 'Moda ve Stil',
    AppStrings.travelAndPlaces: 'Seyahat ve Yerler',
    AppStrings.education: 'Eğitim',
    AppStrings.career: 'Kariyer',
    AppStrings.businessAndFinance: 'İş ve Finans',
    AppStrings.entertainment: 'Eğlence',
    AppStrings.environmentAndEcology: 'Çevre ve Ekoloji',
    AppStrings.agricultureAndHorticulture: 'Tarım ve Bahçecilik',
    AppStrings.languagesAndCommunication: 'Diller ve İletişim',
    AppStrings.technologyAndDigital: 'Teknoloji ve Dijital',
    AppStrings.architectureAndDesign: 'Mimarlık ve Tasarım',
    AppStrings.mediaAndJournalism: 'Medya ve Gazetecilik',
    AppStrings.buyAndSell: 'Alım Satım',
    AppStrings.selectacategory: 'Bir Kategori Seçin',
    AppStrings.groupprofilepicture: 'Grup Profil Resmi',
    AppStrings.selectaimage: 'Bir Resim Seçin',
    AppStrings.groupcoverpicture: 'Grup Kapak Resmi',
    AppStrings.createpost: 'Gönderi Oluştur',
    AppStrings.writesomething: 'Bir şeyler yazın...',
    AppStrings.createapoll: 'Anket Oluştur',
    AppStrings.pollquestion: 'Anket Sorusu',
    AppStrings.polloption: 'Anket Seçeneği',
    AppStrings.addoption: '+ Seçenek Ekle',
    AppStrings.checkin: 'Konum Bildir',
    AppStrings.current: 'Mevcut',
    AppStrings.customLocation: 'Özel Konum',
    AppStrings.onlyforclosefriend: 'Sadece Yakın Arkadaşlar İçin Mi?',
    AppStrings.newsfeed: 'Haber Kaynağı',
    AppStrings.story: 'Hikaye',
    AppStrings.contentmustbefilled: 'İçerik Doldurulmalıdır',
    AppStrings.polloptions: 'Anket Seçenekleri:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions: 'Anketin bir sorusu ve en az iki seçeneği olmalıdır',
    AppStrings.firstofallselectanimage: 'Öncelikle bir resim seçin',
    AppStrings.browseondevice: 'Cihaza göz atın',
    AppStrings.joinedgroup: 'Gruba Katıldı',
    AppStrings.leavegroupsuccessfully: 'Grup başarıyla terkedildi',
    AppStrings.joingroup: 'Gruba Katıl',
    AppStrings.groupjoinedsuccessfully: 'Grup Başarıyla Katılındı',
    AppStrings.postdeletedsuccessfully: 'Gönderi Başarıyla Silindi',
    AppStrings.deleteallusersposts: 'Tüm kullanıcı gönderilerini sil',
    AppStrings.deletealluserscomments: 'Tüm kullanıcı yorumlarını sil',
    AppStrings.deleteposts: 'Gönderileri Sil',
    AppStrings.deletecomments: 'Yorumları Sil',
    AppStrings.removethisuser: 'Bu kullanıcıyı kaldır',
    AppStrings.delete: 'Sil',
    AppStrings.editmemberdetails: 'Üye Ayrıntılarını Düzenle',
    AppStrings.availableroles: 'Mevcut Roller',
    AppStrings.groupmanger: 'Grup Yöneticisi',
    AppStrings.pagemanger: 'Sayfa Yöneticisi',
    AppStrings.pagemangerdescription: 'Sayfa ayrıntılarını değiştir, sayfa üyelerini değiştir, sayfa gönderilerini değiştir, sayfa gönderisi yorumlarını değiştir',
    AppStrings.groupmangerdescription: 'Grup ayrıntılarını değiştir, grup üyelerini değiştir, grup gönderilerini değiştir, grup gönderisi yorumlarını değiştir',
    AppStrings.groupmoderatord: 'Grup Moderatörü',
    AppStrings.pagemoderatord: 'Sayfa Moderatörü',
    AppStrings.pagemoderatorddescription: 'Sayfa gönderilerini değiştir, sayfa gönderisi yorumlarını değiştir',
    AppStrings.groupmoderatorddescription: 'Grup gönderilerini değiştir, grup gönderisi yorumlarını değiştir',
    AppStrings.none: 'Yok',
    AppStrings.availablepermission: 'Mevcut İzin',
    AppStrings.altergroupdetails: 'Grup ayrıntılarını değiştir',
    AppStrings.altergroupmembers: 'Grup üyelerini değiştir',
    AppStrings.altergroupposts: 'Grup gönderilerini değiştir',
    AppStrings.altergrouppostscomments: 'Grup gönderisi yorumlarını değiştir',
    AppStrings.alterpagedetails: 'Sayfa ayrıntılarını değiştir',
    AppStrings.alterpagemembers: 'Sayfa üyelerini değiştir',
    AppStrings.alterpageposts: 'Sayfa gönderilerini değiştir',
    AppStrings.alterpagepostscomments: 'Sayfa gönderisi yorumlarını değiştir',
    AppStrings.updateuser: 'Kullanıcıyı Güncelle',
    AppStrings.editgroup: 'Grubu Düzenle',
    AppStrings.editpage: 'Sayfayı Düzenle',
    AppStrings.deletegroup: 'Grubu Sil',
    AppStrings.deletepage: 'Sayfayı Sil',
    AppStrings.groupmembers: 'Grup Üyeleri',
    AppStrings.pagemembers: 'Sayfa Üyeleri',
    AppStrings.report: 'Raporla',
    AppStrings.areyousureyouwanttodeletegroup: 'Grubu silmek istediğinizden emin misiniz?',
    AppStrings.areyousureyouwanttodeletepage: 'Sayfayı silmek istediğinizden emin misiniz?',
    AppStrings.youremailisnotverified: 'E-posta adresiniz doğrulanmamış',
    AppStrings.unauthenticated: 'Kimlik doğrulama yapılmamış',
    AppStrings.failedtodeletepost: 'Gönderi silinemedi',
    AppStrings.addingapost: 'Bir gönderi ekleniyor',
    AppStrings.golive: 'Canlı Yayına Geç',
    AppStrings.location: 'Konum',
    AppStrings.timestamp: 'Zaman Damgası',
    AppStrings.votes: 'Oylar',
    AppStrings.short: 'Kısa',
    AppStrings.reply: 'Yanıtla',
    AppStrings.shortvideopost: 'Kısa video gönderisi',
    AppStrings.shares: 'Paylaşımlar',
    AppStrings.share: 'Paylaş',
    AppStrings.comment: 'Yorum',
    AppStrings.hidecomments: 'Yorumları Gizle',
    AppStrings.viewmorecomments: 'Daha Fazla Yorum Gör',
    AppStrings.replytonamepost: 'Yorum yapilacak gönderiye yanıtla',
    AppStrings.name: 'Ad',
    AppStrings.onedayago: '1 gün önce',
    AppStrings.promote: 'Tanıt',
    AppStrings.increaseyourpopularity: 'Popülerliğinizi Artırın',
    AppStrings.allocatecoinsforpromotions: 'Tanıtımlar için jeton ayırın',
    AppStrings.like: 'Beğen',
    AppStrings.viewpost: 'Gönderiyi Görüntüle',
    AppStrings.replypost: 'Gönderiye Yanıtla',
    AppStrings.submitanewpost: 'YENİ BİR GÖNDERİ GÖNDER',
    AppStrings.submitanewpostdescription: 'Bu raporu kapsamlı bir içerik ile gönderin. Lütfen olabildiğince fazla detay ekleyin, çözüm almak için tüm mümkün formlarda.',
    AppStrings.content: 'İçerik',
    AppStrings.reportnow: 'Hemen Raporla',
    AppStrings.failedtoremovelock: 'Kilidi kaldırma başarısız oldu',
    AppStrings.password: 'Şifre',
    AppStrings.unlock: 'Kilidi Kaldır',
    AppStrings.thesecredentialsdonotmatch: 'Bu kimlik bilgileri eşleşmiyor',
    AppStrings.login: 'Giriş Yap',
    AppStrings.signin: 'Giriş Yap',
    AppStrings.signup: 'Kayıt Ol',
    AppStrings.email: 'E-Posta',
    AppStrings.rememberme: 'Beni Hatırla',
    AppStrings.forgetpassword: 'Şifrenizi Unuttunuz?',
    AppStrings.notifications: 'Bildirimler',
    AppStrings.pages: 'Sayfalar',
    AppStrings.createnewpage: 'YENİ SAYFA OLUŞTUR',
    AppStrings.members: 'Üyeler',
    AppStrings.creators: 'Yaratıcılar',
    AppStrings.page: 'Sayfa',
    AppStrings.submitpage: 'Sayfayı Gönder',
    AppStrings.aboutthispage: 'Bu Sayfa Hakkında',
    AppStrings.writemoreaboutthispage: 'Bu Sayfa Hakkında Daha Fazla Yaz',
    AppStrings.pagename: 'Sayfa Adı',
    AppStrings.private: 'Özel',
    AppStrings.public: 'Genel',
    AppStrings.invite: 'DAVET ET',
    AppStrings.about: 'HAKKINDA',
    AppStrings.photos: 'FOTOLAR',
    AppStrings.events: 'ETKİNLİKLER',
    AppStrings.pagewillbepublic: 'Sayfa genel olacak',
    AppStrings.pagefollowed: 'Sayfa Takip Edildi',
    AppStrings.joinpage: 'Sayfaya Katıl',
    AppStrings.pageleavedsuccessfully: 'Sayfadan Başarıyla Çıkıldı',
    AppStrings.pagejoinedsuccessfully: 'Sayfaya Başarıyla Katılındı',
    AppStrings.userspage: 'Kullanıcının Sayfası',
    AppStrings.paymentcompletedsuccessfully: 'Ödeme Başarıyla Tamamlandı!',
    AppStrings.stripepayment: 'Stripe Ödemesi',
    AppStrings.myphotos: 'Fotoğraflarım',
    AppStrings.recentphotos: 'Son Fotoğraflar',
    AppStrings.recentposts: 'Son Paylaşımlar',
    AppStrings.savedshorts: 'Kaydedilen Kısa Videolar',
    AppStrings.seeall: 'Tümünü Gör',
    AppStrings.groups: 'Gruplar',
    AppStrings.errorloadingaccountdetails: 'Hesap Detayları Yüklenirken Hata',
    AppStrings.errorloadingprofile: 'Profil Yüklenirken Hata',
    AppStrings.timeline: 'Zaman Çizelgesi',
    AppStrings.saved: 'Kaydedildi',
    AppStrings.restricted: 'Kısıtlı',
    AppStrings.blocked: 'Engellenmiş',
    AppStrings.register: 'Kayıt Ol',
    AppStrings.date: 'Tarih',
    AppStrings.find: 'Bul',
    AppStrings.users: 'Kullanıcılar',
    AppStrings.status: 'Durum',
    AppStrings.open: 'Açık',
    AppStrings.closed: 'Kapalı',
    AppStrings.title: 'Başlık',
    AppStrings.edittickets: 'Biletleri Düzenle',
    AppStrings.postareply: 'Yanıt Gönder',
    AppStrings.createdat: 'Oluşturulma Tarihi',
    AppStrings.lastreplyby: 'Son Yanıtlayan',
    AppStrings.repliesintotal: 'Toplam Yanıt',
    AppStrings.supportTickets: 'Destek Biletleri',
    AppStrings.ticketsummary: 'Bilet Özeti',
    AppStrings.availableactions: 'Mevcut İşlemler',
    AppStrings.retypepassword: 'Şifreyi Tekrar Girin',
    AppStrings.yourname: 'Adınız',
    AppStrings.selectyourcountry: 'Ülkenizi Seçin',
    AppStrings.username: 'Kullanıcı Adı',
    AppStrings.searchby: 'Şuna Göre Ara',
    AppStrings.searchresults: 'Arama Sonuçları',
    AppStrings.searchpeoplegrouporpage: 'Kişileri, grupları veya sayfaları ara',
    AppStrings.followaddedsuccessfully: 'Takip Başarıyla Eklendi',
    AppStrings.followremovedsuccessfully: 'Takip Başarıyla Kaldırıldı',
    AppStrings.pleaseverifyyuouremail: 'Lütfen E-postanızı Doğrulayın',
    AppStrings.verifyyouraccount: 'Hesabınızı Doğrulayın',
    AppStrings.sendverificationlink: 'Doğrulama Bağlantısı Gönder',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow:
    'Eğer zaten bir bağlantı aldıysanız veya bir hesabınız varsa, şimdi giriş yapın',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere:
    'Eğer bağlantı almadıysanız, lütfen buraya tıklayın',
    AppStrings.videos: 'Videolar',
    AppStrings.videoselected: 'Video Seçildi!',
    AppStrings.donate: 'Bağış Yap',
    AppStrings.recentvideos: 'Son Videolar',
    AppStrings.firstofallselectvideo: 'Öncelikle bir video seçin',
    AppStrings.shortdescriprtiontags: 'Kısa Açıklama, #etiketler',
    AppStrings.postshort: '↑ Kısa Video Paylaş',
    AppStrings.pleaseselectavideofile: 'Lütfen bir video dosyası seçin',
    AppStrings.donations: 'Bağışlar',
    AppStrings.topdonations: 'En Yüksek Bağışlar',
    AppStrings.helptheshortcreator: 'Kısa video yaratıcısına yardım edin.',
    AppStrings.sharethispostto: 'Bu gönderiyi şuraya paylaş',
    AppStrings.copylink: 'Bağlantıyı Kopyala',
    AppStrings.selectanuser: 'BİR KULLANICI SEÇİN',
    AppStrings.user111: 'kullanıcı111',
    AppStrings.sharenow: 'Şimdi Paylaş',
    AppStrings.reopenticket: 'Bileti Yeniden Aç',
    AppStrings.closeticket: 'Bileti Kapat',
    AppStrings.supportsticket: 'Destek Bileti',
    AppStrings.totalticket: 'TOPLAM BİLET',
    AppStrings.solvedticket: 'ÇÖZÜLEN BİLETLER',
    AppStrings.openedissues: 'AÇIK KONULAR',
    AppStrings.sendemail: 'E-posta Gönder',
    AppStrings.support: 'Destek',
    AppStrings.openticket: 'Bilet Aç',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto:
    'E-posta ile bizimle iletişime geçmeyi tercih ediyorsanız, lütfen sorununuzu şu adrese gönderin:',
    AppStrings.ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure:
    'Bu satırı okuduysanız, sorununuz gerçekten ciddi görünüyor… Lütfen bununla ilgili daha fazla bilgi verin, kesinlikle size yardımcı olacağız.',
    AppStrings.createanewsupportticket: 'Yeni Bir Destek Bileti Oluştur',
    AppStrings.newintervention: 'Yeni Müdahale',
    AppStrings.interventiontitle: 'Müdahale Başlığı',
    AppStrings.typeherethetitle: 'Başlığı buraya yazın',
    AppStrings.submitticket: 'Bileti Gönder',
    AppStrings.submitcomment: 'Yorum Gönder',
    AppStrings.contentmustnotbelessthentencharacters: 'İçerik 10 karakterden az olmamalıdır',
    AppStrings.completeinterventiontitle: 'Bu müdahaleyi kapsamlı bir içerik ile doldurun. Lütfen mümkün olan tüm detayları içermeye çalışın, böylece doğru çözüm alabilirsiniz.',
    AppStrings.updatecomment: 'Yorumu Güncelle',
    AppStrings.updatethereply: 'Yanıtı Güncelle',
    AppStrings.commentcontent: 'Bu yanıtı kapsamlı bir içerik ile doldurun. Lütfen mümkün olan tüm detayları içermeye çalışın, böylece doğru çözüm alabilirsiniz.',
    AppStrings.thereisopeninterventionticketcloseitfirst: 'Açık bir müdahale bileti var, lütfen önce onu kapatın.',
    AppStrings.addanewcomment: 'Yeni Bir Yorum Ekle',
    AppStrings.billingarea: 'Fatura Alanı',
    AppStrings.billingareacap: 'FATURA ALANI',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount: 'İşlemleri gözden geçirin ve hesabınıza daha fazla coin ekleyin',
    AppStrings.topup: 'YÜKLE',
    AppStrings.gotopayment: 'Ödemeye Git',
    AppStrings.paymentfailed: 'Ödeme Başarısız',
    AppStrings.pleaseselectanamount: 'Lütfen bir miktar seçin',
    AppStrings.showlatesttransactionscap: 'SON İŞLEMLERİ GÖSTER',
    AppStrings.transactionscap: 'İŞLEMLER',
    AppStrings.transactionnote: 'Gelen veya giden işlemleri takip edin ve bir sonraki başarılarınız için hazırlanın.',
    AppStrings.searchtransactionsby: 'İşlemleri Şuna Göre Ara',
    AppStrings.searchtransactions: 'İşlemleri Ara',
    AppStrings.alltransactions: 'Tüm işlemler',
    AppStrings.transactionname: 'İşlem Adı',
    AppStrings.transactionid: 'İşlem ID',
    AppStrings.querytobeexecuted: 'Çalıştırılacak Sorgu',
    AppStrings.settingssaved: 'Ayarlar Kaydedildi',
    AppStrings.general: 'Genel',
    AppStrings.failedtosavesettigns: 'Ayarlar Kaydedilemedi',
    AppStrings.emailpreferences: 'E-posta Tercihleri',
    AppStrings.emailnotificationscap: 'E-POSTA BİLDİRİMLERİ',
    AppStrings.savepreferences: 'Tercihleri Kaydet',
    AppStrings.sendmeemailsaboutmyentireactivity: 'Bana tüm faaliyetlerimle ilgili e-postalar gönder',
    AppStrings.selectpushandemailnotificationyouliketorecieve: 'Aldığınız bildirim türlerini seçin',
    AppStrings.onlysendmerequiredemails: 'Sadece gerekli e-postaları gönder',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges: 'Not: Her zaman bireysel hesap değişiklikleri için bildirim alırsınız.',
    AppStrings.enablefollowmecap: 'BANA TAKİP ETMELERİNE İZİN VER',
    AppStrings.sendmenotificationscap: 'BANA BİLDİRİMLER GÖNDER',
    AppStrings.enablethisifyouwantpeopletofollowyou: 'Bunu etkinleştirirseniz, insanlar sizi takip edebilir',
    AppStrings.sendmenotificationaboutmyfriendlike: 'Arkadaşımın beğenisi hakkında bildirim gönder',
    AppStrings.shareormessageme: 'Paylaş veya mesaj at.',
    AppStrings.hideyourprofilefromsearchengine: 'Profilinizi arama motorlarından gizle',
    AppStrings.searchprivacycap: 'ARAMA GİZLİLİĞİ',
    AppStrings.hidegendercap: 'CİNSİYETİ GİZLE',
    AppStrings.hideagecap: 'YAŞI GİZLE',
    AppStrings.hidelocationcap: 'LOKASYONU GİZLE',
    AppStrings.profilecap: 'PROFİL',
    AppStrings.editprofilecap: 'PROFİLİ DÜZENLE',
    AppStrings.changecap: 'DEĞİŞTİR',
    AppStrings.displaynamecap: 'GÖSTERİLEN İSİM',
    AppStrings.peopleongenixwillgettoknowbybelowinfo: 'Genix üzerindeki insanlar aşağıdaki bilgilerle sizi tanıyacaklar',
    AppStrings.showingname: 'Gösterilen İsim',
    AppStrings.usernamecap: 'KULLANICI ADI',
    AppStrings.emailaddressecap: 'E-POSTA ADRESİ',
    AppStrings.youremailaddress: 'E-posta adresiniz',
    AppStrings.gendercap: 'CİNSİYET',
    AppStrings.male: 'Erkek',
    AppStrings.female: 'Kadın',
    AppStrings.bio: 'Biyografi',
    AppStrings.tellusmoreaboutyou: 'Bize kendiniz hakkında daha fazla bilgi verin',
    AppStrings.socialprofilelinks: 'Sosyal Profil Bağlantıları',
    AppStrings.citycap: 'ŞEHİR',
    AppStrings.countrycap: 'ÜLKE',
    AppStrings.yourcity: 'Şehriniz',
    AppStrings.paypalemailaddress: 'PAY-PAL E-posta Adresi',
    AppStrings.enteryourpaypalemailaddress: 'PAY-PAL E-posta Adresinizi Girin',
    AppStrings.security: 'Güvenlik',
    AppStrings.accountpasswordcap: 'HESAP ŞİFRESİ',
    AppStrings.changeyourpasswordandalterothersecurityoptions: 'Şifrenizi değiştirin ve diğer güvenlik seçeneklerini ayarlayın',
    AppStrings.currentpasswordcap: 'MEVCUT ŞİFRE',
    AppStrings.currentpassword: 'Mevcut Şifre',
    AppStrings.newpassword: 'Yeni Şifre',
    AppStrings.confirmpassword: 'Şifreyi Onayla',
    AppStrings.repeatnewpassword: 'Yeni Şifreyi Tekrar Girin',
    AppStrings.mineightcharacters: 'EN AZ 8 KARAKTER',
    AppStrings.twofactorauthenticationcap: 'İKİ AŞAMALI DOĞRULAMA',
    AppStrings.twofactorauthentication: 'İki faktörlü doğrulama',
    AppStrings.enable: 'Etkinleştir',
    AppStrings.enablecap: 'ETKİNLEŞTİR',
    AppStrings.accountclosure: 'Hesap Kapanışı',
    AppStrings.deleteyouraccountanddata: 'Hesabınızı ve verilerinizi silin',
    AppStrings.areyousureyouwanttodeleteyouraccount: 'Hesabınızı silmek istediğinizden emin misiniz?',
    AppStrings.deletecap: 'SİL',
    AppStrings.settingscap: 'AYARLAR',
    AppStrings.emails: 'E-postalar',
    AppStrings.billings: 'Faturalandırmalar',
    AppStrings.profile: 'Profil',
    AppStrings.currentbalancecap: 'MEVCUT BAKİYE',
    AppStrings.revenuefromshortscap: 'KISA VİDEOLARDAN GELİR',
    AppStrings.withdrawcap: 'ÇEKİLİŞ',
    AppStrings.coins: 'Jetonlar',
    AppStrings.customamount: 'Özel miktar',
    AppStrings.selectlanguage: "Dil Seçin",
    AppStrings.languagecap: "DİL",
    AppStrings.changinglanguage: "Dil değiştiriliyor...",

  };}