import 'all_app_strings.dart';

mixin AppLocaleUkranian {
  static const Map<String, dynamic> ukranian = {


    AppStrings.somethingwentwrong: 'Щось пішло не так',
    AppStrings.nothingtodisplay: "Нічого для відображення...",
    AppStrings.chat: 'Чат',
    AppStrings.spam: 'Спам',
    AppStrings.video: 'Відео',
    AppStrings.active: 'Активний',
    AppStrings.inactive: 'Неактивний',
    AppStrings.edit: 'Редагувати',
    AppStrings.yes: 'Так',
    AppStrings.no: 'Ні',
    AppStrings.settings: 'Налаштування',
    AppStrings.getcoins: 'Отримати монети',
    AppStrings.promotions: 'Акції',
    AppStrings.errorloadingvideo: "Помилка завантаження відео",
    AppStrings.errorloadingpage: "Помилка завантаження сторінки",
    AppStrings.comments: 'Коментарі',
    AppStrings.replyto: 'Відповісти на',
    AppStrings.replytonamecomment: 'Відповісти на коментар імені',
    AppStrings.replies: 'Відповіді',
    AppStrings.post: 'Пост',
    AppStrings.nocommentsyet: 'Ще немає коментарів',
    AppStrings.hommeeeeee: 'hommeeeeee',
    AppStrings.typeamessage: 'Напишіть повідомлення',
    AppStrings.nomessagesfound: "Повідомлень не знайдено",
    AppStrings.failedtoloadthechatrroms: "Не вдалося завантажити кімнати чату",
    AppStrings.typeheretheusername: 'Введіть ім\'я користувача тут',
    AppStrings.lockscreen: 'Екран блокування',
    AppStrings.logout: 'Вийти',
    AppStrings.darkmode: 'Темний режим',
    AppStrings.followers: 'Послідовники',
    AppStrings.followings: 'Ті, хто слідують',
    AppStrings.recentfollowings: 'Нещодавні підписки',
    AppStrings.recentfollowers: 'Нещодавні послідовники',
    AppStrings.groupnmae: 'Назва групи',
    AppStrings.required: '  обов\'язкове',
    AppStrings.website: 'Вебсайт',
    AppStrings.category: 'Категорія',
    AppStrings.validwebsiteurl: 'Дійсне посилання на вебсайт',
    AppStrings.aboutthisgroup: 'Про цю групу',
    AppStrings.areyousureyouwanttologout: 'Ви впевнені, що хочете вийти?',
    AppStrings.writemoreaboutthisgroup: 'Напишіть більше про цю групу',
    AppStrings.sociallinks: 'Соціальні посилання',
    AppStrings.facebookprofilelink: 'Посилання на профіль Facebook',
    AppStrings.xprofilelink: 'Посилання на профіль X',
    AppStrings.instagramprofilelink: 'Посилання на профіль Instagram',
    AppStrings.tiktokprofilelink: 'Посилання на профіль TikTok',
    AppStrings.pinterestprofilelink: 'Посилання на профіль Pinterest',
    AppStrings.steamprofilelink: 'Посилання на профіль Steam',
    AppStrings.linkedInprofilelink: 'Посилання на профіль LinkedIn',
    AppStrings.selectprivacy: 'Виберіть конфіденційність',
    AppStrings.groupwillbepublic: 'Група буде публічною',
    AppStrings.submitgroup: 'Надіслати групу',
    AppStrings.allrequiredfieldsshouldbefilled:
    'Всі обов\'язкові поля повинні бути заповнені',
    AppStrings.errorloadinggroupdata: 'Помилка завантаження даних групи',
    AppStrings.artAndCulture: 'Мистецтво та культура',
    AppStrings.scienceAndTechnology: 'Наука та технології',
    AppStrings.sport: 'Спорт',
    AppStrings.music: 'Музика',
    AppStrings.gastronomy: 'Гастрономія',
    AppStrings.fashionAndStyle: 'Мода та стиль',
    AppStrings.travelAndPlaces: 'Подорожі та місця',
    AppStrings.education: 'Освіта',
    AppStrings.career: 'Кар\'єра',
    AppStrings.businessAndFinance: 'Бізнес та фінанси',
    AppStrings.entertainment: 'Розваги',
    AppStrings.environmentAndEcology: 'Навколишнє середовище та екологія',
    AppStrings.agricultureAndHorticulture: 'Сільське господарство та садівництво',
    AppStrings.languagesAndCommunication: 'Мови та комунікація',
    AppStrings.technologyAndDigital: 'Технології та цифрові',
    AppStrings.architectureAndDesign: 'Архітектура та дизайн',
    AppStrings.mediaAndJournalism: 'Медіа та журналістика',
    AppStrings.buyAndSell: 'Купити та продати',
    AppStrings.selectacategory: 'Виберіть категорію',
    AppStrings.groupprofilepicture: 'Зображення профілю групи',
    AppStrings.selectaimage: 'Виберіть зображення',
    AppStrings.groupcoverpicture: 'Обкладинка групи',
    AppStrings.createpost: 'Створити пост',
    AppStrings.writesomething: 'Напишіть щось...',
    AppStrings.createapoll: 'Створити опитування',
    AppStrings.pollquestion: 'Запитання опитування',
    AppStrings.polloption: 'Опція опитування',
    AppStrings.addoption: '+ Додати опцію',
    AppStrings.checkin: 'Зареєструватися',
    AppStrings.current: 'Поточний',
    AppStrings.customLocation: 'Користувацьке місце',
    AppStrings.onlyforclosefriend: 'Тільки для близьких друзів?',
    AppStrings.newsfeed: 'Новини',
    AppStrings.story: 'Історія',
    AppStrings.contentmustbefilled: 'Контент має бути заповнений',
    AppStrings.polloptions: 'Опції опитування:',
    AppStrings.pollmusthaveaquestionandatleasttwooptions:
    'Опитування повинно містити запитання та хоча б дві опції',
    AppStrings.firstofallselectanimage: 'Спочатку виберіть зображення',
    AppStrings.browseondevice: 'Переглядати на пристрої',
    AppStrings.joinedgroup: 'Приєднано до групи',
    AppStrings.leavegroupsuccessfully: 'Ви успішно залишили групу',
    AppStrings.joingroup: 'Приєднатися до групи',
    AppStrings.groupjoinedsuccessfully: 'Група успішно приєднана',
    AppStrings.postdeletedsuccessfully: 'Пост успішно видалено',
    AppStrings.deleteallusersposts: 'Видалити всі пости користувача',
    AppStrings.deletealluserscomments: 'Видалити всі коментарі користувача',
    AppStrings.deleteposts: 'Видалити пости',
    AppStrings.deletecomments: 'Видалити коментарі',
    AppStrings.removethisuser: 'Видалити цього користувача',
    AppStrings.delete: 'Видалити',
    AppStrings.editmemberdetails: 'Редагувати деталі учасника',
    AppStrings.availableroles: 'Доступні ролі',
    AppStrings.groupmanger: 'Менеджер групи',
    AppStrings.pagemanger: 'Менеджер сторінки',
    AppStrings.pagemangerdescription: 'Змінювати деталі сторінки, змінювати учасників сторінки, змінювати пости сторінки, змінювати коментарі постів сторінки',
    AppStrings.groupmangerdescription: 'Змінювати деталі групи, змінювати учасників групи, змінювати пости групи, змінювати коментарі постів групи',
    AppStrings.groupmoderatord: 'Модератор групи',
    AppStrings.pagemoderatord: 'Модератор сторінки',
    AppStrings.pagemoderatorddescription: 'Змінювати пости сторінки, змінювати коментарі постів сторінки',
    AppStrings.groupmoderatorddescription: 'Змінювати пости групи, змінювати коментарі постів групи',
    AppStrings.none: 'Немає',
    AppStrings.availablepermission: 'Доступні дозволи',
    AppStrings.altergroupdetails: 'Змінювати деталі групи',
    AppStrings.altergroupmembers: 'Змінювати учасників групи',
    AppStrings.altergroupposts: 'Змінювати пости групи',
    AppStrings.altergrouppostscomments: 'Змінювати коментарі постів групи',
    AppStrings.alterpagedetails: 'Змінювати деталі сторінки',
    AppStrings.alterpagemembers: 'Змінювати учасників сторінки',
    AppStrings.alterpageposts: 'Змінювати пости сторінки',
    AppStrings.alterpagepostscomments: 'Змінювати коментарі постів сторінки',
    AppStrings.updateuser: 'Оновити користувача',
    AppStrings.editgroup: 'Редагувати групу',
    AppStrings.editpage: 'Редагувати сторінку',
    AppStrings.deletegroup: 'Видалити групу',
    AppStrings.deletepage: 'Видалити сторінку',
    AppStrings.groupmembers: 'Учасники групи',
    AppStrings.pagemembers: 'Учасники сторінки',
    AppStrings.report: 'Повідомити',
    AppStrings.areyousureyouwanttodeletegroup: 'Ви впевнені, що хочете видалити групу?',
    AppStrings.areyousureyouwanttodeletepage: 'Ви впевнені, що хочете видалити сторінку?',
    AppStrings.youremailisnotverified: 'Вашу електронну пошту не підтверджено',
    AppStrings.unauthenticated: 'Неавторизований',
    AppStrings.failedtodeletepost: 'Не вдалося видалити пост',
    AppStrings.addingapost: 'додається пост',
    AppStrings.golive: 'Стартуйте в прямому ефірі',
    AppStrings.location: 'Місцезнаходження',
    AppStrings.timestamp: 'Часова мітка',
    AppStrings.votes: 'голоси',
    AppStrings.short: 'короткий',
    AppStrings.reply: 'відповісти',
    AppStrings.shortvideopost: 'короткий відеопост',
    AppStrings.shares: 'Поширення',
    AppStrings.share: 'Поділитися',
    AppStrings.comment: 'коментар',
    AppStrings.hidecomments: 'Приховати коментарі',
    AppStrings.viewmorecomments: 'Переглянути більше коментарів',
    AppStrings.replytonamepost: 'відповісти на пост імені',
    AppStrings.name: 'ім\'я',
    AppStrings.onedayago: '1 день тому',
    AppStrings.promote: 'Просувати',
    AppStrings.increaseyourpopularity: 'Збільшіть свою популярність',
    AppStrings.allocatecoinsforpromotions: 'Виділяйте монети на просування',
    AppStrings.like: 'Подобається',
    AppStrings.viewpost: 'Переглянути пост',
    AppStrings.replypost: 'Відповісти на пост',
    AppStrings.submitanewpost: 'НАДІСЛАТИ НОВИЙ ПОСТ',
    AppStrings.submitanewpostdescription: 'Заповніть цей звіт детальним змістом. Будь ласка, надайте якомога більше деталей у всіх можливих формах для належного вирішення.',
    AppStrings.content: 'Зміст',
    AppStrings.reportnow: 'Повідомити зараз',
    AppStrings.failedtoremovelock: 'Не вдалося зняти блокування',
    AppStrings.password: 'Пароль',
    AppStrings.unlock: 'Розблокувати',
    AppStrings.thesecredentialsdonotmatch: 'Ці дані не збігаються',
    AppStrings.login: 'Увійти',
    AppStrings.signin: 'Увійти',
    AppStrings.signup: 'Зареєструватися',
    AppStrings.email: 'Електронна пошта',
    AppStrings.rememberme: 'Запам\'ятати мене',
    AppStrings.forgetpassword: 'Забули пароль',
    AppStrings.notifications: 'Сповіщення',
    AppStrings.pages: 'Сторінки',
    AppStrings.createnewpage: 'СТВОРИТИ НОВУ СТОРІНКУ',
    AppStrings.members: 'Учасники',
    AppStrings.creators: 'Творці',
    AppStrings.page: 'Сторінка',
    AppStrings.submitpage: 'Подати сторінку',
    AppStrings.aboutthispage: 'Про цю сторінку',
    AppStrings.writemoreaboutthispage: 'Напишіть більше про цю сторінку',
    AppStrings.pagename: 'Назва сторінки',
    AppStrings.private: 'Приватний',
    AppStrings.public: 'Публічний',
    AppStrings.invite: 'ЗАПРОСИТИ',
    AppStrings.about: 'Про',
    AppStrings.photos: 'Фотографії',
    AppStrings.events: 'Події',
    AppStrings.pagewillbepublic: 'Сторінка буде публічною',
    AppStrings.pagefollowed: 'Сторінка підписана',
    AppStrings.joinpage: 'Приєднатися до сторінки',
    AppStrings.pageleavedsuccessfully: 'Ви успішно покинули сторінку',
    AppStrings.pagejoinedsuccessfully: 'Ви успішно приєдналися до сторінки',
    AppStrings.userspage: 'Сторінка користувача',
    AppStrings.paymentcompletedsuccessfully: 'Платіж успішно завершено!',
    AppStrings.stripepayment: 'Платіж через Stripe',
    AppStrings.myphotos: 'Мої фотографії',
    AppStrings.recentphotos: 'Останні фотографії',
    AppStrings.recentposts: 'Останні пости',
    AppStrings.savedshorts: 'Збережені шорти',
    AppStrings.seeall: 'Показати всі',
    AppStrings.groups: 'Групи',
    AppStrings.errorloadingaccountdetails: 'Помилка при завантаженні деталей облікового запису',
    AppStrings.errorloadingprofile: 'Помилка при завантаженні профілю',
    AppStrings.timeline: 'Таймлайн',
    AppStrings.saved: 'Збережено',
    AppStrings.restricted: 'Обмежено',
    AppStrings.blocked: 'Заблоковано',
    AppStrings.register: 'Реєстрація',
    AppStrings.date: 'Дата',
    AppStrings.find: 'Знайти',
    AppStrings.users: 'Користувачі',
    AppStrings.status: 'Статус',
    AppStrings.open: 'Відкрито',
    AppStrings.closed: 'Закрито',
    AppStrings.title: 'Назва',
    AppStrings.edittickets: 'Редагувати квитки',
    AppStrings.postareply: 'Опублікувати відповідь',
    AppStrings.createdat: 'Створено',
    AppStrings.lastreplyby: 'Остання відповідь від',
    AppStrings.repliesintotal: 'Всього відповідей',
    AppStrings.supportTickets: 'Підтримка квитків',
    AppStrings.ticketsummary: 'Резюме квитка',
    AppStrings.availableactions: 'Доступні дії',
    AppStrings.retypepassword: 'Повторіть пароль',
    AppStrings.yourname: 'Ваше ім\'я',
    AppStrings.selectyourcountry: 'Оберіть вашу країну',
    AppStrings.username: 'Ім\'я користувача',
    AppStrings.searchby: 'Шукати за',
    AppStrings.searchresults: 'Результати пошуку',
    AppStrings.searchpeoplegrouporpage: 'Шукати людей, групи або сторінки',
    AppStrings.followaddedsuccessfully: 'Підписка успішно додана',
    AppStrings.followremovedsuccessfully: 'Підписка успішно видалена',
    AppStrings.pleaseverifyyuouremail: 'Будь ласка, перевірте вашу електронну пошту',
    AppStrings.verifyyouraccount: 'Перевірте ваш обліковий запис',
    AppStrings.sendverificationlink: 'Відправити посилання для перевірки',
    AppStrings.ifyouhavealreadyreceivedalinkorifyouhaveanaccountloginnow: 'Якщо ви вже отримали посилання або маєте обліковий запис, увійдіть зараз',
    AppStrings.ifyouhavetreceivedalinkpleaseclickhere: 'Якщо ви не отримали посилання, будь ласка, натисніть тут',
    AppStrings.videos: 'Відео',
    AppStrings.videoselected: 'Відео вибрано!',
    AppStrings.donate: 'Пожертвувати',
    AppStrings.recentvideos: 'Останні відео',
    AppStrings.firstofallselectvideo: 'Спочатку виберіть відео',
    AppStrings.shortdescriprtiontags: 'Короткий опис, #теги',
    AppStrings.postshort: '↑ Опублікувати коротке',
    AppStrings.pleaseselectavideofile: 'Будь ласка, виберіть відеофайл',
    AppStrings.donations: 'Пожертви',
    AppStrings.topdonations: 'Топ пожертв',
    AppStrings.helptheshortcreator: 'Допоможіть творцю шортів.',
    AppStrings.sharethispostto: 'Поділитися цим постом в',
    AppStrings.copylink: 'копіювати посилання',
    AppStrings.selectanuser: 'ОБРАТИ КОРИСТУВАЧА',
    AppStrings.user111: 'user111',
    AppStrings.sharenow: 'Поділитися зараз',
    AppStrings.reopenticket: 'Відкрити квиток',
    AppStrings.closeticket: 'Закрити квиток',
    AppStrings.supportsticket: 'Підтримка квитків',
    AppStrings.totalticket: 'ВСЬОГО КВИТКІВ',
    AppStrings.solvedticket: 'ВИРІШЕНІ КВИТКИ',
    AppStrings.openedissues: 'ВІДКРИТІ ПРОБЛЕМИ',
    AppStrings.sendemail: 'Відправити електронну пошту',
    AppStrings.support: 'Підтримка',
    AppStrings.openticket: 'Відкрити квиток',
    AppStrings.ifyouwouldprefertocontactusbyemailpleasesendusyourinquiryto: 'Якщо ви віддаєте перевагу контактувати з нами через електронну пошту, будь ласка, надішліть нам ваш запит на:',
    AppStrings.ifyoureadthislineitlookslikeyourissueisreallyseriouspleaseletusknowmoreaboutthiswewillhelpyouforsure: 'Якщо ви прочитали цей рядок, здається, ваша проблема справді серйозна… будь ласка, поділіться більше інформацією, ми допоможемо вам.',
    AppStrings.createanewsupportticket: 'Створити новий квиток підтримки',
    AppStrings.newintervention: 'Нове втручання',
    AppStrings.interventiontitle: 'Заголовок втручання',
    AppStrings.typeherethetitle: 'Введіть заголовок',
    AppStrings.submitticket: 'Подати квиток',
    AppStrings.submitcomment: 'Подати коментар',
    AppStrings.contentmustnotbelessthentencharacters: 'Контент не повинен бути менше 10 символів',
    AppStrings.completeinterventiontitle: 'Заповніть це втручання детальним описом. Включіть стільки деталей, скільки зможете, щоб отримати належне вирішення.',
    AppStrings.updatecomment: 'Оновити коментар',
    AppStrings.updatethereply: 'Оновити відповідь',
    AppStrings.commentcontent: 'Заповніть цю відповідь детальним описом. Включіть стільки деталей, скільки зможете, щоб отримати належне вирішення.',
    AppStrings.thereisopeninterventionticketcloseitfirst: 'Є відкритий квиток втручання, будь ласка, закрийте його спочатку.',
    AppStrings.addanewcomment: 'Додати новий коментар',
    AppStrings.billingarea: 'Білінгова зона',
    AppStrings.billingareacap: 'БІЛІНГОВА ЗОНА',
    AppStrings.browsetransactionsandaddmorecoinstoyouraccount: 'Перегляньте транзакції та додайте більше монет до вашого облікового запису',
    AppStrings.topup: 'ПОПОВНИТИ',
    AppStrings.gotopayment: 'Перейти до платежу',
    AppStrings.paymentfailed: 'Платіж не вдався',
    AppStrings.pleaseselectanamount: 'Будь ласка, виберіть суму',
    AppStrings.showlatesttransactionscap: 'ПОКАЗАТИ ОСТАННІ ТРАНСАКЦІЇ',
    AppStrings.transactionscap: 'ТРАНСАКЦІЇ',
    AppStrings.transactionnote: 'Відстежуйте та переглядайте вхідні або вихідні транзакції та готуйтеся до наступних досягнень.',
    AppStrings.searchtransactionsby: 'Шукати транзакції за',
    AppStrings.searchtransactions: 'Шукати транзакції',
    AppStrings.alltransactions: 'Усі транзакції',
    AppStrings.transactionname: 'Назва транзакції',
    AppStrings.transactionid: 'ID транзакції',
    AppStrings.querytobeexecuted: 'Запит для виконання',
    AppStrings.settingssaved: 'Налаштування збережено',
    AppStrings.general: 'Загальні',
    AppStrings.failedtosavesettigns: 'Не вдалося зберегти налаштування',
    AppStrings.emailpreferences: 'Налаштування електронної пошти',
    AppStrings.emailnotificationscap: 'ЕЛЕКТРОННІ ПОВІДОМЛЕННЯ',
    AppStrings.savepreferences: 'Зберегти налаштування',
    AppStrings.sendmeemailsaboutmyentireactivity: 'Надсилати мені електронні листи про мою активність',
    AppStrings.selectpushandemailnotificationyouliketorecieve: 'Виберіть push-сповіщення та електронні листи, які ви хочете отримувати',
    AppStrings.onlysendmerequiredemails: 'Надсилати лише обов\'язкові електронні листи',
    AppStrings.noteYouwillalwaysgetnotificationsforindividualaccountchanges: 'Примітка: Ви завжди будете отримувати повідомлення про окремі зміни акаунту.',
    AppStrings.enablefollowmecap: 'УВІМКНУТИ СЛІДКУВАННЯ',
    AppStrings.sendmenotificationscap: 'НАДСИЛАТИ МЕНІ ПОВІДОМЛЕННЯ',
    AppStrings.enablethisifyouwantpeopletofollowyou: 'Увімкніть це, якщо хочете, щоб люди вас слідували',
    AppStrings.sendmenotificationaboutmyfriendlike: 'Надсилати мені сповіщення про лайки моїх друзів',
    AppStrings.shareormessageme: 'Поділитися або надіслати повідомлення',
    AppStrings.hideyourprofilefromsearchengine: 'Приховати ваш профіль від пошукових систем',
    AppStrings.searchprivacycap: 'ПРИВАТНІСТЬ ПОШУКУ',
    AppStrings.hidegendercap: 'ПРИХОВАТИ СТАТЬ',
    AppStrings.hideagecap: 'ПРИХОВАТИ ВІК',
    AppStrings.hidelocationcap: 'ПРИХОВАТИ ЛОКАЦІЮ',
    AppStrings.profilecap: 'ПРОФІЛЬ',
    AppStrings.editprofilecap: 'РЕДАГУВАТИ ПРОФІЛЬ',
    AppStrings.changecap: 'ЗМІНИТИ',
    AppStrings.displaynamecap: 'ПОКАЗУВАТИ ІМ\'Я',
    AppStrings.peopleongenixwillgettoknowbybelowinfo: 'Люди в Genix дізнаються про вас за наступною інформацією',
    AppStrings.showingname: 'Показується ім\'я',
    AppStrings.usernamecap: 'КОРИСТУВАЧЕВСЬКЕ ІМ\'Я',
    AppStrings.emailaddressecap: 'ЕЛЕКТРОННА ПОШТА',
    AppStrings.youremailaddress: 'Ваша електронна пошта',
    AppStrings.gendercap: 'СТАТЬ',
    AppStrings.male: 'Чоловік',
    AppStrings.female: 'Жінка',
    AppStrings.bio: 'Біо',
    AppStrings.tellusmoreaboutyou: 'Розкажіть більше про себе',
    AppStrings.socialprofilelinks: 'Посилання на соціальні профілі',
    AppStrings.citycap: 'МІСТО',
    AppStrings.countrycap: 'КРАЇНА',
    AppStrings.yourcity: 'Ваше місто',
    AppStrings.paypalemailaddress: 'Е-МЕЙЛ PAYPAL',
    AppStrings.enteryourpaypalemailaddress: 'Введіть вашу електронну пошту PAYPAL',
    AppStrings.security: 'Безпека',
    AppStrings.accountpasswordcap: 'ПАРОЛЬ АКАУНТА',
    AppStrings.changeyourpasswordandalterothersecurityoptions: 'Змініть пароль та налаштування безпеки',
    AppStrings.currentpasswordcap: 'Поточний пароль',
    AppStrings.currentpassword: 'Поточний пароль',
    AppStrings.newpassword: 'Новий пароль',
    AppStrings.confirmpassword: 'Підтвердьте пароль',
    AppStrings.repeatnewpassword: 'Повторіть новий пароль',
    AppStrings.mineightcharacters: 'МІНІМУМ 8 ЗНАКІВ',
    AppStrings.twofactorauthenticationcap: 'ДВОФАКТОРНА АУТЕНТИФІКАЦІЯ',
    AppStrings.twofactorauthentication: 'Двофакторна аутентифікація',
    AppStrings.enable: 'Увімкнути',
    AppStrings.enablecap: 'УВІМКНУТИ',
    AppStrings.accountclosure: 'ЗАКРИТТЯ АКАУНТА',
    AppStrings.deleteyouraccountanddata: 'Видалити ваш акаунт і дані',
    AppStrings.areyousureyouwanttodeleteyouraccount: 'Ви впевнені, що хочете видалити свій акаунт?',
    AppStrings.deletecap: 'ВИДАЛИТИ',
    AppStrings.settingscap: 'НАЛАШТУВАННЯ',
    AppStrings.emails: 'Електронні листи',
    AppStrings.billings: 'Білінг',
    AppStrings.profile: 'Профіль',
    AppStrings.currentbalancecap: 'ПОТОЧНИЙ БАЛАНС',
    AppStrings.revenuefromshortscap: 'ДОХІД З КОРОТКИХ ВІДЕО',
    AppStrings.withdrawcap: 'ВИЗНАТИ',
    AppStrings.coins: 'Монети',
    AppStrings.customamount: 'Індивідуальна сума',
    AppStrings.selectlanguage: "Виберіть мову",
    AppStrings.languagecap: "МОВА",
    AppStrings.changinglanguage: "Зміна мови...",
  };}